<script>
export const page={name:"sales-import-detail",path:"/sales/imports/:id",title:"匯入批次結果",requires:{permissions:["sales.view"]}};
</script>
<script setup>
import {computed,onBeforeUnmount,ref,watch} from "vue";
import {useRoute,useRouter} from "vue-router";
import PageHeader from "@/framework/layout/PageHeader.vue";
import DataTable from "@/framework/ui/DataTable.vue";
import EllipsisCell from "@/framework/ui/EllipsisCell.vue";
import FormPanel from "@/framework/ui/FormPanel.vue";
import Summary from "@/components/sales/SalesImportSummary.vue";
import {useImportJobPolling} from "@/composables/sales/useImportJobPolling.js";
import {can} from "@/framework/authorization/can.js";
import {useSessionStore} from "@/stores/session.js";
import {notifyError} from "@/framework/ui/notify.js";
import sales from "@/services/sales.js";
const route=useRoute(),router=useRouter(),session=useSessionStore(),id=computed(()=>Number(route.params.id)),actor=computed(()=>session.user?.id),write=computed(()=>can(session,{permissions:["sales.import"]}));
const {job,error,loading,refresh}=useImportJobPolling({jobId:id,actorId:actor});
const status=ref(route.query.status??null),errorCode=ref(route.query.errorCode??""),externalOrderId=ref(route.query.externalOrderId??"");
const dialog=ref(false),intent=ref(null),busy=ref(false),message=ref(""),table=ref(null);let controller=new AbortController();
const storageKey=computed(()=>`sales.import:${actor.value}:${id.value}`);
function reset(){controller.abort();controller=new AbortController();intent.value=null;dialog.value=false;busy.value=false;message.value="";try{const saved=JSON.parse(sessionStorage.getItem(storageKey.value));if(saved&&['confirm','cancel'].includes(saved.action)&&/^[0-9a-f-]{36}$/u.test(saved.eventId)&&Number.isSafeInteger(saved.version)&&saved.version>0)intent.value=saved;}catch{/* Invalid stored intent is ignored. */}}
watch(storageKey,reset,{immediate:true});onBeforeUnmount(()=>controller.abort());
const columns=[{name:"sourceOrderKey",label:"來源訂單",field:"sourceOrderKey",align:"left"},{name:"firstRowNo",label:"來源首行",field:"firstRowNo",sortable:true},{name:"status",label:"來源狀態",field:"status",sortable:true},{name:"resultCode",label:"結果",field:"resultCode"},{name:"salesOrderNumber",label:"銷售訂單",field:"salesOrderNumber"},{name:"actions",label:"操作",align:"right"}];
function apply(){router.replace({query:Object.fromEntries(Object.entries({status:status.value,errorCode:errorCode.value,externalOrderId:externalOrderId.value}).filter(([,value])=>value))});}
function fetchRows(params){return sales.listImportOrders(id.value,{...params,status:route.query.status,errorCode:route.query.errorCode,externalOrderId:route.query.externalOrderId,signal:controller.signal});}
watch(()=>job.value?.version,()=>table.value?.reload());
function closeDialog(){if(!sessionStorage.getItem(storageKey.value))intent.value=null;dialog.value=false;}
function choose(action){if(intent.value)return;intent.value={action,eventId:crypto.randomUUID(),version:job.value.version};dialog.value=true;}
async function submit(){const signal=controller.signal,key=storageKey.value,current=intent.value;busy.value=true;sessionStorage.setItem(key,JSON.stringify(current));try{await sales[current.action==='confirm'?'confirmImport':'cancelImport'](id.value,{eventId:current.eventId,version:current.version},{signal});if(signal.aborted)return;sessionStorage.removeItem(key);intent.value=null;dialog.value=false;message.value=current.action==='confirm'?"已確認匯入，等待處理結果。":"已取消匯入。";await refresh();}catch(cause){if(signal.aborted)return;if(!['TIMEOUT','NETWORK_ERROR','DATABASE_TRANSACTION_FAILED'].includes(cause.code)&&cause.status<500){sessionStorage.removeItem(key);intent.value=null;await refresh();}throw Error("操作未完成；請重新讀取批次。結果未確定時，重試會沿用原事件。");}finally{if(!signal.aborted)busy.value=false;}}
async function result(){const signal=controller.signal;busy.value=true;try{const {blob,fileName}=await sales.downloadImportResult(id.value,{signal});if(signal.aborted)return;const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=fileName??'sales-import-result.csv';link.click();URL.revokeObjectURL(url);}catch{if(!signal.aborted)notifyError("結果下載失敗或已到期；結構化結果仍可查閱。");}finally{if(!signal.aborted)busy.value=false;}}
</script>
<template><div><PageHeader :subtitle="job?.batchNumber"><template #actions><q-btn flat label="返回批次" to="/sales/imports" /><q-btn flat label="重新讀取批次" @click="refresh" /></template></PageHeader><div class="q-px-md q-pb-md" :aria-busy="loading"><p v-if="loading&&!job" role="status">正在讀取批次…</p><q-banner v-if="error" role="alert" class="bg-negative text-white q-mb-md">無法讀取批次；請重試或確認查閱權限。</q-banner><p v-if="message" role="status">{{ message }}</p><template v-if="job"><Summary :job="job" :can-import="write&&!intent" :busy="busy" @action="choose" /><div class="row q-gutter-sm q-my-md"><q-btn v-if="write&&intent" label="重試原匯入操作" color="primary" :disable="busy" @click="dialog=true" /><q-btn label="查看來源例外" :to="{path:'/sales/imports/exceptions',query:{jobId:String(id)}}" /><q-btn v-if="['COMPLETED','PARTIAL_SUCCESS','FAILED'].includes(job.status)&&!job.filesPurgedAt" label="下載結果 CSV" :loading="busy" @click="result" /></div><h2 class="text-h6 q-mb-sm">來源訂單結果</h2><div class="row q-col-gutter-md q-mb-md"><div class="col-12 col-md-3"><q-select v-model="status" label="來源狀態" :options="['VALID','INVALID','QUEUED','PROCESSING','SUCCEEDED','DUPLICATE','FAILED']" clearable outlined dense /></div><div class="col-12 col-md-3"><q-input v-model="errorCode" label="錯誤代碼（精確）" maxlength="80" outlined dense /></div><div class="col-12 col-md-4"><q-input v-model="externalOrderId" label="External ID（精確）" maxlength="190" outlined dense /></div><div class="col-12 col-md-2"><q-btn label="篩選來源" color="primary" @click="apply" /></div></div><DataTable :key="`${id}:${JSON.stringify(route.query)}`" ref="table" :fetch="fetchRows" :columns="columns" sticky-actions :initial-pagination="{page:1,rowsPerPage:20,rowsNumber:0,sortBy:'firstRowNo',descending:false}"><template #body-cell-sourceOrderKey="{value}"><EllipsisCell :text="value" /></template><template #body-cell-salesOrderNumber="{row}"><q-td><q-btn v-if="row.salesOrderId&&!row.isArchived" flat :label="row.salesOrderNumber" :to="`/sales/orders/${row.salesOrderId}`" /><span v-else>{{ row.salesOrderNumber }}{{ row.isArchived?'（已封存）':'' }}</span></q-td></template><template #body-cell-actions="{row}"><q-td><q-btn flat label="查看欄位錯誤" :to="{path:'/sales/imports/exceptions',query:{jobId:String(id),orderId:String(row.id)}}" /></q-td></template><template #no-data><p role="status">來源結果尚未建立。</p></template></DataTable></template></div><q-dialog v-model="dialog" :persistent="busy"><q-card><q-card-section><h2 class="text-h6 q-ma-none">{{ intent?.action==='confirm'?'確認匯入':'取消匯入' }}</h2><p>確認會處理有效來源；無效及重複來源會保留結果。取消只適用於尚未開始處理的批次。</p><FormPanel :on-submit="submit" v-slot="{submitting}"><div class="row q-gutter-sm"><q-btn flat label="返回" :disable="submitting" @click="closeDialog" /><q-btn type="submit" label="提交匯入操作" color="primary" :loading="submitting" :disable="!intent" /></div></FormPanel></q-card-section></q-card></q-dialog></div></template>
