import { describe, expect, it } from "vitest";
import { ERROR_CODE_MESSAGES } from "@/framework/http/errorMessages.js";

describe("Inventory foundation", () => {
  it("maps every stable Inventory error code to Traditional Chinese", () => {
    for (const code of [
      "INVENTORY_INPUT_INVALID", "INVENTORY_QUANTITY_INVALID", "WAREHOUSE_INVALID",
      "BIN_INVALID", "BIN_WAREHOUSE_MISMATCH", "SKU_NOT_INVENTORY_TRACKED",
      "SERIAL_TRACKING_UNSUPPORTED", "LOT_REQUIRED", "EXPIRY_REQUIRED", "LOT_DATA_CONFLICT",
      "WAREHOUSE_CODE_TAKEN", "BIN_CODE_TAKEN", "WAREHOUSE_IN_USE", "BIN_IN_USE",
      "INSUFFICIENT_STOCK", "INSUFFICIENT_ATP", "ALLOCATION_INSUFFICIENT",
      "RESERVATION_STATE_CONFLICT", "ALLOCATION_STATE_CONFLICT", "CONCURRENT_OPERATION",
      "INVENTORY_SOURCE_CONFLICT", "PICK_SEQUENCE_REASON_REQUIRED", "FEFO_OVERRIDE_REQUIRED",
      "FEFO_OVERRIDE_DENIED", "PERMISSION_STALE", "LOT_EXPIRED",
      "LOT_MINIMUM_LIFE_FAILED", "STOCK_STATUS_INELIGIBLE", "BIN_LOCKED_BY_STOCKTAKE",
      "TRANSFER_STATE_CONFLICT", "TRANSFER_PARTIAL_NOT_SUPPORTED", "STOCKTAKE_STATE_CONFLICT",
      "STOCKTAKE_INCOMPLETE", "STOCKTAKE_SNAPSHOT_MISMATCH", "MOVEMENT_ALREADY_REVERSED",
      "MOVEMENT_TYPE_NOT_REVERSIBLE", "REVERSAL_NOT_ALLOWED", "OPENING_PRECHECK_STALE",
      "OPENING_STATE_CONFLICT", "OPENING_CLOSED", "INVENTORY_RESOURCE_NOT_FOUND",
      "OPENING_RESULT_EXPIRED", "INVENTORY_DEPENDENCY_UNAVAILABLE"
    ]) {
      expect(ERROR_CODE_MESSAGES[code], code).toMatch(/[\u3400-\u9fff]/u);
    }
  });
});
