import assert from "node:assert/strict";
import test from "node:test";
import { SalesBackorderAllocationJob } from "../../../src/services/salesJobs/jobs/SalesBackorderAllocationJob.js";
import { SalesJobRuntimeService } from "../../../src/services/salesJobs/SalesJobRuntimeService.js";

test("Backorder registration binds fixed cluster job and live reserve-only principal; disabled/stopped/unregistered/aborted fail closed",async()=>{
 const logs=[],controller=new AbortController(),job={name:"sales.backorderAllocate",serviceName:"job.salesBackorderAllocation",method:"run",scope:"cluster",enabled:true},scheduler={jobs:new Map(),running:new Map(),owner:"test-owner",started:true,stopped:false,schedulerConfig:{enabled:true},register(instance){assert.ok(instance instanceof SalesBackorderAllocationJob);this.jobs.set(job.name,job);}};
 const database={query(){throw Error("Unexpected SQL");},withTransaction(){throw Error("Unexpected transaction");}},time={nowMs:()=>100,fileDate:()=>"2026-10-07"};const runtime=new SalesJobRuntimeService({services:{require:name=>({mysqldatabase:database,time,logging:{logger:{info:async(...args)=>logs.push(args),error:async(...args)=>logs.push(args)}}})[name]}});
 const service=new SalesBackorderAllocationJob({services:{require:name=>({scheduler,salesJobs:runtime})[name]}});await service.initialize();assert.deepEqual(SalesBackorderAllocationJob.service.dependencies,["scheduler","salesJobs"]);assert.equal(SalesBackorderAllocationJob.jobs[0].scope,"cluster");assert.equal(runtime.backorderPrincipal(),null);scheduler.running.set(job.name,{controller});assert.deepEqual(runtime.backorderPrincipal(),{leaseOwner:"test-owner",signal:controller.signal});
 for(const change of [()=>job.enabled=false,()=>scheduler.stopped=true,()=>scheduler.started=false,()=>scheduler.schedulerConfig.enabled=false,()=>scheduler.jobs.delete(job.name)]){change();assert.equal(runtime.backorderPrincipal(),null);job.enabled=true;scheduler.stopped=false;scheduler.started=true;scheduler.schedulerConfig.enabled=true;scheduler.jobs.set(job.name,job);}
 let received;runtime.backorder.runBatch=async options=>{received=options;return {openCount:2,oldestAgeMs:500,deferred:0,allocatedEntries:1};};assert.equal((await service.run(controller.signal)).allocatedEntries,1);assert.equal(received.signal,controller.signal);assert.equal(logs[0][0],"sales.backorder_allocation_completed");
 runtime.backorder.runBatch=async()=>({openCount:2,oldestAgeMs:500,deferred:1});await assert.rejects(()=>service.run(controller.signal),/incomplete/u);controller.abort();assert.equal(runtime.backorderPrincipal(),null);await assert.rejects(()=>service.run(controller.signal));
});
test("Manual wake uses the actual registered enabled Scheduler execute path and reports no immediate allocation promise",async()=>{
 const calls=[],job={name:"sales.backorderAllocate",serviceName:"job.salesBackorderAllocation",method:"run",scope:"cluster",enabled:true},scheduler={jobs:new Map([[job.name,job]]),running:new Map(),owner:"test-owner",started:true,stopped:false,schedulerConfig:{enabled:true},execute(value){calls.push(value);return Promise.resolve();}},database={query(){throw Error("Unexpected SQL");},withTransaction(){throw Error("Unexpected transaction");}},time={nowMs:()=>100,fileDate:()=>"2026-10-07"};const runtime=new SalesJobRuntimeService({services:{require:name=>({mysqldatabase:database,time,logging:{logger:{info:async()=>{},error:async()=>{}}}})[name]}});runtime.bindBackorderScheduler(scheduler);runtime.backorder.wake=async()=>({accepted:true});assert.deepEqual(await runtime.wakeBackorders({claims:{},input:{orderId:1}}),{accepted:true});assert.deepEqual(calls,[job]);scheduler.stopped=true;await assert.rejects(()=>runtime.wakeBackorders({claims:{},input:{orderId:1}}),{code:"SALES_DEPENDENCY_UNAVAILABLE"});assert.equal(calls.length,1);
});
