import process from "node:process";
import { test,expect } from "@playwright/test";
import { createServer } from "vite";
import { randomUUID,randomInt } from "node:crypto";
import { fileURLToPath } from "node:url";
import { migrationFixture } from "../../../server/test/sales/phase1/fixtures.js";
import { createApplication } from "../../../server/src/framework/application/createApplication.js";
import { defaultConfigurationSource } from "../../../server/src/framework/configuration/applicationConfiguration.js";
import { formatDateForFile } from "../../../server/src/services/time/timeFormat.js";
let app,vite,f,origin,operatorToken,viewerToken,customerCode,skuCode,warehouseCode;
const callbacks=[];
test.beforeAll(async()=>{
 if(process.env.DB_INTEGRATION_TESTS!=="1"||!/^erp_sales_phase1_/u.test(process.env.DB_NAME??""))throw new Error("Sales browser tests require the approved isolated synthetic Phase1 database");
 f=await migrationFixture({after(fn){callbacks.push(fn);}},[]);
 const source=defaultConfigurationSource(),port=randomInt(32000,59000);origin=`http://127.0.0.1:${port}`;
 app=await createApplication({configurationSource:{...source,application:{...source.application,port:0},security:{...source.security,cors:{...source.security.cors,allowedOrigins:origin}}}});
 async function actor(permissions){const role=`sales-e2e-${randomUUID().slice(0,8)}`,roleId=await f.insert("roles",{name:role,created_at:f.now}),userId=await f.insert("users",{username:role,password_hash:"synthetic-only",display_name:"Synthetic Sales browser",created_at:f.now,updated_at:f.now});
  await f.db.execute("INSERT INTO user_roles (user_id,role_id) VALUES (?,?)",[userId,roleId]);for(const permission of permissions)await f.db.execute("INSERT INTO role_permissions (role_id,permission_id) SELECT ?,id FROM permissions WHERE name=?",[roleId,permission]);
  f.beforeParents.push(async()=>{await f.db.execute("DELETE FROM sales_audit_logs WHERE actor_user_id=?",[userId]);await f.db.execute("DELETE FROM sales_operation_requests WHERE actor_user_id=?",[userId]);await f.db.execute("DELETE FROM fr_token_versions WHERE subject=?",[String(userId)]);await f.db.execute("DELETE FROM user_roles WHERE user_id=?",[userId]);await f.db.execute("DELETE FROM role_permissions WHERE role_id=?",[roleId]);});
  return app.services.require("jwt").issue({roles:[role],permissions},{subject:String(userId),version:await app.services.require("tokenRevocation").currentVersion(String(userId)),authTime:Math.floor(f.now/1000)});
 }
 operatorToken=await actor(["sales.view","sales.mgmt"]);viewerToken=await actor(["sales.view"]);
 f.beforeParents.push(async()=>{await f.db.execute("DELETE FROM sales_quotation_conversions WHERE quotation_id IN (SELECT id FROM sales_quotations WHERE customer_id=?)",[f.customerId]);await f.db.execute("DELETE FROM sales_orders WHERE customer_id=?",[f.customerId]);await f.db.execute("DELETE FROM sales_quotations WHERE customer_id=?",[f.customerId]);});
 await f.db.execute("UPDATE currencies SET status='ACTIVE' WHERE code=?",[f.currency]);await f.db.execute("UPDATE item_skus SET sellable=1,suggested_price_amount='3.3333' WHERE id=?",[f.skuId]);
 customerCode=(await f.db.query("SELECT customer_code FROM customers WHERE id=?",[f.customerId]))[0][0].customer_code;skuCode=(await f.db.query("SELECT sku_code FROM item_skus WHERE id=?",[f.skuId]))[0][0].sku_code;warehouseCode=(await f.db.query("SELECT warehouse_code FROM inventory_warehouses WHERE id=?",[f.warehouseId]))[0][0].warehouse_code;
 await f.insert("item_sku_barcodes",{sku_id:f.skuId,sku_uom_id:f.skuUomId,barcode:"8712345678901",normalized_barcode:"8712345678901",barcode_type:"internal",created_at:f.now,updated_at:f.now});
 const {url}=await app.start();process.env.VITE_API_BASE_URL=url;
 vite=await createServer({root:fileURLToPath(new URL("../..",import.meta.url)),configFile:fileURLToPath(new URL("../../vite.config.js",import.meta.url)),server:{host:"127.0.0.1",port,strictPort:true}});await vite.listen();
});
test.afterAll(async()=>{try{if(vite)await vite.close();if(app)await app.shutdown("sales_phase1_browser_complete");}finally{for(const callback of callbacks.reverse())await callback();}});
function monitor(page,expected=[]){const errors=[],network=[];let offline=false;
 page.on("pageerror",error=>errors.push(error.message));page.on("console",message=>{if(message.text().startsWith("[Vue warn]")||(message.type()==="error"&&!message.text().includes("Failed to load resource")&&!message.text().includes("net::ERR_INTERNET_DISCONNECTED")))errors.push(message.text());});
 page.on("requestfailed",request=>{const error=request.failure()?.errorText;if(!offline&&error!=="net::ERR_ABORTED")network.push(error);});
 page.on("response",response=>{if(response.status()>=400&&!expected.some(([status,path])=>response.status()===status&&new URL(response.url()).pathname.startsWith(path)))network.push(response.status());});
 return {offline(value){offline=value;},verify(){expect(errors).toEqual([]);expect(network).toEqual([]);}};
}
async function authenticate(page,token=operatorToken){await page.goto(origin+"/login");await page.evaluate(async value=>{const {setToken}=await import("/src/framework/auth/tokenStorage.js");setToken(value,900,3600);},token);}
async function choose(page,label,search,text){await page.getByRole("combobox",{name:label,exact:true}).fill(search);await page.getByRole("option").filter({hasText:text}).first().click();await expect(page.getByRole("listbox")).toBeHidden();}
async function command(page,method,...args){return page.evaluate(async({method,args})=>{const {default:sales}=await import("/src/services/sales.js");return sales[method](...args);},{method,args});}
function orderInput(){return {eventId:randomUUID(),customerId:f.customerId,currencyCode:f.currency,fulfillmentWarehouseId:f.warehouseId,orderDate:formatDateForFile(new Date(f.now),"Asia/Hong_Kong"),lines:[{skuId:f.skuId,skuUomId:f.skuUomId,quantity:"2.000000",unitSellingPrice:"3.3333"}]};}
function editable(order){return {customerId:order.customerId,currencyCode:order.currencyCode,paymentTermId:order.paymentTermId,fulfillmentWarehouseId:order.fulfillmentWarehouseId,orderDate:order.orderDate,requestedDeliveryDate:order.requestedDeliveryDate,customerPoReference:order.customerPoReference,notes:order.notes,lines:order.lines.map(line=>({id:line.id,skuId:line.skuId,skuUomId:line.skuUomId,quantity:line.quantity,unitSellingPrice:line.unitSellingPrice,lineNote:line.lineNote}))};}
async function seedOrder(page){await page.goto(origin+"/sales/orders");return (await command(page,"createOrder",orderInput())).salesOrder;}
async function fillOrder(page){await choose(page,"客戶 *",customerCode,customerCode);await choose(page,"履約倉庫 *",warehouseCode,warehouseCode);await choose(page,"搜尋 SKU",skuCode,skuCode);await page.getByRole("button",{name:"新增明細",exact:true}).click();await page.getByLabel("數量 1 *",{exact:true}).fill("2.000000");await page.getByLabel("售價 1 *",{exact:true}).fill("3.3333");}

test("TC-019 Manual Draft create validates input and focuses duplicate SKU/UOM",async({page})=>{
 const check=monitor(page);let writes=0;page.on("request",request=>{if(new URL(request.url()).pathname==="/api/v1/sales-orders/create")writes++;});await authenticate(page);await page.goto(origin+"/sales/orders/new");await fillOrder(page);await page.getByLabel("數量 1 *",{exact:true}).fill("0");await page.getByRole("button",{name:"儲存 Draft 銷售訂單",exact:true}).click();await expect(page.getByText("數量必須大於零，最多六位小數",{exact:true})).toBeVisible();await page.getByLabel("數量 1 *",{exact:true}).fill("2.000000");
 await choose(page,"搜尋 SKU",skuCode,skuCode);await page.getByRole("combobox",{name:"搜尋 SKU",exact:true}).press("Enter");await expect(page.getByTestId("sales-order-line")).toHaveCount(1);await expect(page.getByLabel("數量 1 *",{exact:true})).toBeFocused();expect(writes).toBe(0);
 await page.getByRole("button",{name:"儲存 Draft 銷售訂單",exact:true}).click();await expect(page).toHaveURL(/\/sales\/orders\/\d+$/u);await expect(page.getByRole("heading",{level:1})).toHaveText(/^SO-/u);await expect(page.getByText(`${f.currency} 6.6666`,{exact:true})).toBeVisible();await expect(page.getByRole("link",{name:"編輯 Draft",exact:true})).toBeVisible();check.verify();
});
test("TC-019 Manual edit preserves stale inputs and replays one immutable uncertain intent",async({page,context})=>{
 const check=monitor(page,[[409,"/api/v1/sales-orders/"]]);await authenticate(page);const order=await seedOrder(page);await page.goto(origin+`/sales/orders/${order.id}/edit`);await expect(page.getByLabel("數量 1 *",{exact:true})).toHaveValue("2.000000");
 await command(page,"updateOrder",order.id,{...editable(order),eventId:randomUUID(),version:order.version,notes:"another editor"});await page.getByLabel("備註",{exact:true}).fill("retained stale input");await page.getByRole("button",{name:"儲存 Draft 銷售訂單",exact:true}).click();await expect(page.getByText("版本已更改；你的輸入仍保留，請載入最新資料後再修改。",{exact:true})).toBeVisible();await expect(page.getByLabel("備註",{exact:true})).toHaveValue("retained stale input");
 page.once("dialog",dialog=>dialog.accept());await page.getByRole("button",{name:"載入最新資料",exact:true}).click();await expect(page.getByLabel("備註",{exact:true})).toHaveValue("another editor");
 await page.getByLabel("備註",{exact:true}).fill("uncertain recovery");check.offline(true);await context.setOffline(true);await page.getByRole("button",{name:"儲存 Draft 銷售訂單",exact:true}).click();await expect(page.getByText("結果尚未確認；保留原提交，請重試確認結果。",{exact:true})).toBeVisible();await expect(page.getByLabel("備註",{exact:true})).toBeDisabled();await context.setOffline(false);check.offline(false);
 await page.getByRole("button",{name:"重試確認結果",exact:true}).click();await expect(page.getByRole("status").filter({hasText:"銷售訂單已儲存"})).toContainText("最新版本 3");await page.reload();await expect(page.getByLabel("備註",{exact:true})).toHaveValue("uncertain recovery");check.verify();
});
test("TC-019 Barcode, zero price and current master validation remain operable",async({page})=>{
 const check=monitor(page,[[409,"/api/v1/sales-orders/create"]]);await authenticate(page);await page.goto(origin+"/sales/orders/new");await choose(page,"客戶 *",customerCode,customerCode);await choose(page,"履約倉庫 *",warehouseCode,warehouseCode);await page.getByLabel("條碼（精確搜尋）",{exact:true}).fill("8712345678901");await page.getByRole("button",{name:"搜尋條碼",exact:true}).click();await expect(page.getByRole("button",{name:"新增明細",exact:true})).toBeEnabled();await page.getByRole("button",{name:"新增明細",exact:true}).click();await page.getByLabel("售價 1 *",{exact:true}).fill("0.0000");await expect(page.getByText("注意：此明細為零售價。",{exact:true})).toBeVisible();
 try{await f.db.execute("UPDATE item_skus SET status='inactive' WHERE id=?",[f.skuId]);await page.getByRole("button",{name:"儲存 Draft 銷售訂單",exact:true}).click();await expect(page.getByRole("alert").first()).toBeVisible();await expect(page.getByLabel("售價 1 *",{exact:true})).toHaveValue("0.0000");}finally{await f.db.execute("UPDATE item_skus SET status='active' WHERE id=?",[f.skuId]);}
 await page.getByRole("button",{name:"儲存 Draft 銷售訂單",exact:true}).click();await expect(page).toHaveURL(/\/sales\/orders\/\d+$/u);await expect(page.getByText(`${f.currency} 0.0000`,{exact:true})).toBeVisible();check.verify();
});
test("TC-019 Issued quotation converts an edited complete Draft SO and links both directions",async({page})=>{
 const check=monitor(page);await authenticate(page);await page.goto(origin+"/sales/quotations");const input=orderInput(),{eventId:_event,fulfillmentWarehouseId:_warehouse,orderDate,...fields}=input;
 const created=await command(page,"createQuotation",{...fields,eventId:randomUUID(),quotationDate:orderDate,validUntil:formatDateForFile(new Date(f.now+30*86400000),"Asia/Hong_Kong")});const issued=await command(page,"issueQuotation",created.quotation.id,{eventId:randomUUID(),version:1});
 await page.goto(origin+`/sales/quotations/${issued.quotation.id}/edit?convert=1`);await choose(page,"履約倉庫 *",warehouseCode,warehouseCode);await page.getByLabel("數量 1 *",{exact:true}).fill("3.000000");await page.getByRole("button",{name:"建立 Draft 銷售訂單",exact:true}).click();await expect(page.getByRole("status")).toContainText("已建立 SO-");await page.getByRole("link",{name:"查看銷售訂單",exact:true}).click();await expect(page.getByText("報價轉單",{exact:true})).toBeVisible();await expect(page.getByRole("cell",{name:/3\.000000/u})).toBeVisible();await expect(page.getByText(`${f.currency} 9.9999`,{exact:true})).toBeVisible();await page.getByRole("link",{name:"返回來源報價",exact:true}).click();await expect(page.getByText("已轉單",{exact:true})).toBeVisible();await expect(page.getByRole("link",{name:/^SO-/u})).toBeVisible();check.verify();
});
test("TC-019 Quotation read actions, validation and browser print reflect server state",async({page})=>{
 const check=monitor(page);await authenticate(page);await page.goto(origin+"/sales/quotations");const input=orderInput(),{eventId:_event,fulfillmentWarehouseId:_warehouse,orderDate,...fields}=input;const created=await command(page,"createQuotation",{...fields,eventId:randomUUID(),quotationDate:orderDate,validUntil:formatDateForFile(new Date(f.now+30*86400000),"Asia/Hong_Kong")});
 await page.goto(origin+`/sales/quotations/${created.quotation.id}`);await page.getByRole("button",{name:"發出報價",exact:true}).click();await page.getByRole("button",{name:"確認發出",exact:true}).click();await page.getByRole("link",{name:"列印",exact:true}).click();await expect(page.getByRole("table")).toBeVisible();await expect(page.getByRole("article")).toContainText("6.6666");await page.emulateMedia({media:"print"});await expect(page.locator(".q-header")).toBeHidden();await page.emulateMedia({media:"screen"});
 await page.goto(origin+`/sales/quotations/${created.quotation.id}`);await page.getByRole("button",{name:"取消報價",exact:true}).click();await page.getByLabel("取消原因 *",{exact:true}).fill("no");await page.getByRole("button",{name:"確認取消",exact:true}).click();await expect(page.getByText("最少五個字元",{exact:true})).toBeVisible();await page.getByLabel("取消原因 *",{exact:true}).fill("合成取消原因");await page.getByRole("button",{name:"確認取消",exact:true}).click();await expect(page.getByText("已取消",{exact:true})).toBeVisible();check.verify();
});
test("TC-019 Active list retains exact filters and server pagination across refresh",async({page})=>{
 const check=monitor(page);await authenticate(page);const order=await seedOrder(page);await page.goto(origin+`/sales/orders?customerId=${f.customerId}&page=2`);await expect(page.getByRole("status").filter({hasText:"沒有符合條件"})).toBeVisible();await page.getByLabel("訂單編號（精確）",{exact:true}).fill(order.number);await page.getByRole("button",{name:"搜尋",exact:true}).click();await expect(page.getByRole("link",{name:`查看 ${order.number}`,exact:true})).toBeVisible();await page.reload();await expect(page.getByLabel("訂單編號（精確）",{exact:true})).toHaveValue(order.number);await page.getByRole("link",{name:`查看 ${order.number}`,exact:true}).click();await expect(page.getByRole("heading",{level:1})).toHaveText(order.number);check.verify();
});
test("TC-019 Viewer reads snapshots/current masters and cannot open Draft writes",async({page})=>{
 const check=monitor(page,[[403,"/api/v1/sales-orders/create"]]);await authenticate(page);const order=await seedOrder(page);await authenticate(page,viewerToken);
 try{await f.db.execute("UPDATE customers SET legal_name='Current Synthetic Customer' WHERE id=?",[f.customerId]);await f.db.execute("UPDATE item_skus SET sku_name='Current Synthetic SKU' WHERE id=?",[f.skuId]);await page.goto(origin+`/sales/orders/${order.id}`);await expect(page.getByText(`客戶：${customerCode} — Current Synthetic Customer（active）`,{exact:true})).toBeVisible();await expect(page.getByRole("cell",{name:`${skuCode} — ${order.lines[0].skuName}`,exact:true})).toBeVisible();await expect(page.getByRole("link",{name:"編輯 Draft",exact:true})).toHaveCount(0);await expect(page.getByText("人工",{exact:true})).toBeVisible();}finally{await f.db.execute("UPDATE customers SET legal_name=? WHERE id=?",[order.customerName,f.customerId]);await f.db.execute("UPDATE item_skus SET sku_name=? WHERE id=?",[order.lines[0].skuName,f.skuId]);}
 await page.goto(origin+"/sales/orders");await expect(page.getByRole("link",{name:"新增銷售訂單",exact:true})).toHaveCount(0);await page.goto(origin+"/sales/orders/new");await expect(page.getByRole("heading",{name:"冇權限",exact:true})).toBeVisible();const result=await page.evaluate(async input=>{const {default:sales}=await import("/src/services/sales.js");try{await sales.createOrder(input);return "unexpected";}catch(error){return error.status;}},orderInput());expect(result).toBe(403);check.verify();
});
test("TC-019 Mobile form/detail, dirty route guard and explicit missing Active result",async({page})=>{
 const check=monitor(page,[[404,"/api/v1/sales-orders/"]]);await authenticate(page);await page.goto(origin+"/sales/orders/new");await fillOrder(page);await page.setViewportSize({width:375,height:812});await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.getByRole("button",{name:"開關側邊欄",exact:true}).click();page.once("dialog",dialog=>dialog.dismiss());await page.getByRole("link",{name:"銷售訂單",exact:true}).click();await page.locator(".q-drawer__backdrop").click({position:{x:340,y:100}});await expect(page.locator(".q-drawer__backdrop")).toBeHidden();await expect(page).toHaveURL(/\/sales\/orders\/new$/u);await expect(page.getByLabel("數量 1 *",{exact:true})).toHaveValue("2.000000");await page.getByRole("button",{name:"儲存 Draft 銷售訂單",exact:true}).click();await expect(page).toHaveURL(/\/sales\/orders\/\d+$/u);await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.getByRole("link",{name:"返回訂單列表",exact:true}).click();await page.getByLabel("訂單編號（精確）",{exact:true}).fill("SO-190001-999999");await page.getByRole("button",{name:"搜尋",exact:true}).click();await expect(page.getByRole("status").filter({hasText:"沒有符合條件的 Active"})).toBeVisible();await page.goto(origin+"/sales/orders/9007199254740991");await page.locator(".q-drawer__backdrop").click({position:{x:340,y:100}});await expect(page.getByRole("alert")).toBeVisible();await expect(page.getByRole("button",{name:"重試",exact:true})).toBeVisible();check.verify();
});
