import process from "node:process";
import {Buffer} from "node:buffer";
import path from "node:path";
import {rm,readFile} from "node:fs/promises";
import {randomUUID,randomInt} from "node:crypto";
import {fileURLToPath} from "node:url";
import {test,expect} from "@playwright/test";
import {createServer} from "vite";
import {stringify} from "csv-stringify/sync";
import {migrationFixture} from "../../../server/test/sales/phase1/fixtures.js";
import {SALES_CSV_COLUMNS} from "../../../server/src/modules/sales/salesCsv.js";
import {createApplication} from "../../../server/src/framework/application/createApplication.js";
import {defaultConfigurationSource} from "../../../server/src/framework/configuration/applicationConfiguration.js";
let f,app,vite,origin,operator,viewer,operatorId,row,completedId;const cleanup=[];
test.beforeAll(async()=>{
 if(process.env.DB_INTEGRATION_TESTS!=="1"||!/^erp_sales_p3_[a-f0-9]+_t038$/u.test(process.env.DB_NAME??""))throw Error("P3 browser tests require the approved owned synthetic schema");
 f=await migrationFixture({after(fn){cleanup.push(fn);}},[]);const source=defaultConfigurationSource(),port=randomInt(32000,59000);origin=`http://127.0.0.1:${port}`;
 app=await createApplication({configurationSource:{...source,application:{...source.application,port:0},sales:{...source.sales,importChannelCodes:["SYNTHETIC"]},scheduler:{...source.scheduler,jobs:{...source.scheduler.jobs,"sales.confirmationRecovery":{enabled:false},"sales.backorderAllocate":{enabled:false},"sales.importWorker":{enabled:true}}},security:{...source.security,cors:{...source.security.cors,allowedOrigins:origin}}}});
 async function actor(permissions){const label="p3-browser-"+randomUUID().slice(0,8),roleId=await f.insert("roles",{name:label,created_at:f.now}),id=await f.insert("users",{username:label,password_hash:"synthetic-only",display_name:"Synthetic browser",created_at:f.now,updated_at:f.now});await f.db.execute("INSERT INTO user_roles (user_id,role_id) VALUES (?,?)",[id,roleId]);for(const name of permissions)await f.db.execute("INSERT INTO role_permissions (role_id,permission_id) SELECT ?,id FROM permissions WHERE name=?",[roleId,name]);
 f.beforeParents.push(async()=>{const [jobs]=await f.db.query("SELECT batch_number FROM sales_import_jobs WHERE created_by=?",[id]);await f.db.execute("DELETE FROM sales_orders WHERE customer_id=?",[f.customerId]);await f.db.execute("DELETE FROM sales_external_order_keys WHERE channel_code='SYNTHETIC' AND external_order_id LIKE ?",['p3-browser-'+f.customerId+'-%']);await f.db.execute("DELETE FROM sales_import_jobs WHERE created_by=?",[id]);for(const job of jobs)await rm(path.join('storage/sales-imports',job.batch_number),{recursive:true,force:true});await f.db.execute("DELETE FROM sales_audit_logs WHERE actor_user_id=?",[id]);await f.db.execute("DELETE FROM sales_operation_requests WHERE actor_user_id=?",[id]);await f.db.execute("DELETE FROM fr_token_versions WHERE subject=?",[String(id)]);await f.db.execute("DELETE FROM role_permissions WHERE role_id=?",[roleId]);await f.db.execute("DELETE FROM user_roles WHERE user_id=?",[id]);});
 if(permissions.includes('sales.import'))operatorId=id;return app.services.require('jwt').issue({roles:[label],permissions},{subject:String(id),version:await app.services.require('tokenRevocation').currentVersion(String(id)),authTime:Math.floor(f.now/1000)});}
 operator=await actor(['sales.view','sales.import']);viewer=await actor(['sales.view']);
 await f.db.execute("UPDATE currencies SET status='ACTIVE' WHERE code=?",[f.currency]);await f.db.execute("UPDATE item_skus SET sellable=1,inventory_tracked=1 WHERE id=?",[f.skuId]);
 const [[sku]]=await f.db.query('SELECT sku_code FROM item_skus WHERE id=?',[f.skuId]),[[uom]]=await f.db.query('SELECT code FROM item_uoms WHERE id=(SELECT uom_id FROM item_sku_uoms WHERE id=?)',[f.skuUomId]),[[warehouse]]=await f.db.query('SELECT warehouse_code FROM inventory_warehouses WHERE id=?',[f.warehouseId]);
 row={templateVersion:'1.0',sourceOrderKey:'A',channelCode:'SYNTHETIC',externalOrderId:'',customerId:String(f.customerId),warehouseCode:warehouse.warehouse_code,orderDate:'2026-10-09',requestedDeliveryDate:'',currencyCode:f.currency,paymentTermCode:'',customerPoReference:'',orderNotes:'',skuCode:sku.sku_code,salesUomCode:uom.code,quantity:'1',unitSellingPrice:'1',lineNote:''};
 const binId=await f.insert("inventory_bins",{warehouse_id:f.warehouseId,bin_code:"browser",normalized_code:"browser",created_at:f.now,updated_at:f.now});await f.db.execute("INSERT INTO inventory_stock_balances (warehouse_id,bin_id,sku_id,stock_status,on_hand_quantity,created_at,updated_at) VALUES (?,?,?,'AVAILABLE',1000,?,?)",[f.warehouseId,binId,f.skuId,f.now,f.now]);
 f.beforeParents.push(async()=>{await f.db.execute("DELETE FROM sales_orders WHERE customer_id=?",[f.customerId]);await f.db.execute("DELETE FROM inventory_reservations WHERE warehouse_id=?",[f.warehouseId]);await f.db.execute("DELETE FROM inventory_stock_balances WHERE warehouse_id=?",[f.warehouseId]);await f.db.execute("DELETE FROM inventory_stock_controls WHERE warehouse_id=?",[f.warehouseId]);});
 const [[lease]]=await f.db.query("SELECT * FROM fr_job_leases WHERE job_name='sales.importWorker'");f.beforeParents.push(async()=>{if(lease)await f.db.execute("UPDATE fr_job_leases SET owner=?,acquired_at=?,expires_at=? WHERE job_name='sales.importWorker'",[lease.owner,lease.acquired_at,lease.expires_at]);else await f.db.execute("DELETE FROM fr_job_leases WHERE job_name='sales.importWorker'");});
 const {url}=await app.start();process.env.VITE_API_BASE_URL=url;vite=await createServer({root:fileURLToPath(new URL('../..',import.meta.url)),configFile:fileURLToPath(new URL('../../vite.config.js',import.meta.url)),server:{host:'127.0.0.1',port,strictPort:true}});await vite.listen();
});
test.afterAll(async()=>{try{await vite?.close();await app?.shutdown('sales_p3_browser_complete');}finally{for(const fn of cleanup.reverse())await fn();}});
function monitor(page,expected=[]){const errors=[],network=[];let offline=false;page.on('pageerror',error=>errors.push(error.message));page.on('console',m=>{if(m.text().startsWith('[Vue warn]')||(m.type()==='error'&&!m.text().includes('Failed to load resource')&&!m.text().includes('net::ERR_INTERNET_DISCONNECTED')))errors.push(m.text());});page.on('requestfailed',r=>{if(!offline&&!['net::ERR_ABORTED'].includes(r.failure()?.errorText))network.push(r.failure()?.errorText);});page.on('response',r=>{if(r.status()>=400&&!expected.some(([status,part])=>r.status()===status&&new URL(r.url()).pathname.startsWith(part)))network.push(r.status());});return {offline(value){offline=value;},verify(){expect(errors).toEqual([]);expect(network).toEqual([]);}};}
async function authenticate(page,token=operator){await page.goto(origin+'/login');await page.evaluate(async token=>{const {setToken}=await import('/src/framework/auth/tokenStorage.js');setToken(token,900,3600);},token);}
function csv(rows){return stringify([SALES_CSV_COLUMNS.map(c=>c.name),...rows.map(r=>SALES_CSV_COLUMNS.map(c=>r[c.name]))]);}
async function upload(page,rows){await page.goto(origin+'/sales/imports/new');await page.getByLabel('銷售 CSV 檔案').setInputFiles({name:'synthetic.csv',mimeType:'text/csv',buffer:Buffer.from(csv(rows))});await page.getByRole('button',{name:'上傳並預檢',exact:true}).click();await expect(page).toHaveURL(/\/sales\/imports\/\d+$/u);await expect(page.getByRole('status').filter({hasText:'預檢完成'})).toBeVisible();return Number(new URL(page.url()).pathname.split('/').at(-1));}
const external=()=>`p3-browser-${f.customerId}-${randomUUID()}`;
async function ensureCompleted(page){if(completedId)return;completedId=await upload(page,[{...row,externalOrderId:external()},{...row,sourceOrderKey:'Bad',externalOrderId:external(),quantity:'bad'}]);await page.getByRole('button',{name:'確認匯入',exact:true}).click();await page.getByRole('button',{name:'提交匯入操作',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'部分成功'})).toBeVisible();}
test('TC-034 TC-035 TC-038 actual template/upload/precheck/confirm/partial result/exception/SO navigation',async({page})=>{
 const check=monitor(page);await authenticate(page);await page.goto(origin+'/sales/imports/new');const download=page.waitForEvent('download');await page.getByRole('button',{name:'下載 CSV 範本',exact:true}).click();expect((await download).suggestedFilename()).toMatch(/\.csv$/u);
 await page.getByRole('button',{name:'上傳並預檢',exact:true}).click();await expect(page.getByText('請選擇 CSV 檔案',{exact:true})).toBeVisible();
 completedId=await upload(page,[{...row,externalOrderId:external()},{...row,sourceOrderKey:'<img src=x>',externalOrderId:external(),quantity:'bad'},{...row,sourceOrderKey:'C',externalOrderId:external()}]);await expect(page.getByRole('status').filter({hasText:'預檢完成'})).toContainText('有效 2');await expect(page.getByRole('status').filter({hasText:'預檢完成'})).toContainText('無效 1');
 await page.getByRole('button',{name:'確認匯入',exact:true}).click();await page.getByRole('button',{name:'提交匯入操作',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'部分成功'})).toBeVisible();await expect(page.getByRole('status').filter({hasText:'部分成功'})).toContainText('成功 2');
 const result=page.waitForEvent('download');await page.getByRole('button',{name:'下載結果 CSV',exact:true}).click();expect((await result).suggestedFilename()).toMatch(/-result.csv$/u);await page.reload();await expect(page.getByRole('status').filter({hasText:'部分成功'})).toBeVisible();
 const [[invalidSource]]=await f.db.query("SELECT external_order_id FROM sales_intake_orders WHERE import_job_id=? AND status='INVALID'",[completedId]);await page.getByLabel('錯誤代碼（精確）').fill('SALES_QUANTITY_INVALID');await page.getByRole('button',{name:'篩選來源',exact:true}).click();await expect(page.getByRole('cell',{name:'<img src=x>',exact:true})).toBeVisible();await page.getByLabel('External ID（精確）').fill(invalidSource.external_order_id);await page.getByRole('button',{name:'篩選來源',exact:true}).click();await expect(page.getByRole('cell',{name:'<img src=x>',exact:true})).toBeVisible();await page.getByLabel('External ID（精確）').fill('missing');await page.getByRole('button',{name:'篩選來源',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'來源結果尚未建立'})).toBeVisible();await page.getByLabel('錯誤代碼（精確）').fill('');await page.getByLabel('External ID（精確）').fill('');await page.getByRole('button',{name:'篩選來源',exact:true}).click();
 await page.getByRole('link',{name:'查看來源例外',exact:true}).click();await expect(page.getByRole('cell',{name:'<img src=x>',exact:true})).toBeVisible();expect(await page.locator('img[src=x]').count()).toBe(0);await page.getByRole('link',{name:'欄位錯誤 <img src=x>',exact:true}).click();await expect(page.getByRole('cell',{name:'SALES_QUANTITY_INVALID',exact:true})).toBeVisible();
 await page.goto(origin+`/sales/imports/${completedId}`);const [[order]]=await f.db.query('SELECT sales_order_id,sales_order_number FROM sales_intake_orders WHERE import_job_id=? AND status=\'SUCCEEDED\' ORDER BY id LIMIT 1',[completedId]);await page.getByRole('link',{name:order.sales_order_number,exact:true}).click();await expect(page).toHaveURL(new RegExp(`/sales/orders/${order.sales_order_id}$`));check.verify();
});
test('TC-039 offline unknown confirm retains original event across refresh and cancel uses actual CAS',async({page,context})=>{
 const check=monitor(page);await authenticate(page);const id=await upload(page,[{...row,externalOrderId:external()}]);await page.getByRole('button',{name:'確認匯入',exact:true}).click();check.offline(true);await context.setOffline(true);await page.getByRole('button',{name:'提交匯入操作',exact:true}).click();await expect(page.getByRole('dialog').getByRole('alert').first()).toBeVisible();const saved=await page.evaluate(key=>sessionStorage.getItem(key),`sales.import:${operatorId}:${id}`);expect(saved).not.toBeNull();await context.setOffline(false);check.offline(false);await page.reload();await page.getByRole('button',{name:'重試原匯入操作',exact:true}).click();await page.getByRole('button',{name:'提交匯入操作',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'已完成'})).toBeVisible();const [[op]]=await f.db.query("SELECT event_id FROM sales_operation_requests WHERE target_id=? AND command_type='CONFIRM_IMPORT'",[id]);expect(op.event_id).toBe(JSON.parse(saved).eventId);
 await upload(page,[{...row,externalOrderId:external()}]);await page.getByRole('button',{name:'取消匯入',exact:true}).click();await page.getByRole('button',{name:'提交匯入操作',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'來源訂單'}).filter({hasText:'已取消'})).toBeVisible();check.verify();
});
test('TC-043 view-only results, responsive keyboard and empty source state',async({page})=>{
 const check=monitor(page);await authenticate(page);await ensureCompleted(page);await authenticate(page,viewer);await page.goto(origin+'/sales/imports');await expect(page.getByRole('button',{name:'上傳 CSV',exact:true})).toHaveCount(0);await page.goto(origin+`/sales/imports/${completedId}`);await expect(page.getByRole('button',{name:'下載結果 CSV',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'確認匯入',exact:true})).toHaveCount(0);
 for(const width of [375,768,1024,1440]){await page.setViewportSize({width,height:900});await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
 await page.getByRole('button',{name:'重新讀取批次',exact:true}).focus();await expect(page.getByRole('button',{name:'重新讀取批次',exact:true})).toBeFocused();await page.keyboard.press('Enter');await expect(page.getByRole('status').filter({hasText:'部分成功'})).toBeVisible();
 await page.goto(origin+`/sales/imports/exceptions?jobId=${completedId}&status=FAILED`);await expect(page.getByRole('status').filter({hasText:'沒有符合條件的來源'})).toBeVisible();await page.goto(origin+'/sales/imports/new');await expect(page).toHaveURL(/\/403$/u);check.verify();
});

test('TC-034 importer downloads exact V1 template through authenticated blob',async({page})=>{const check=monitor(page);await authenticate(page);await page.goto(origin+'/sales/imports');const result=await page.evaluate(async()=>{const {default:sales}=await import('/src/services/sales.js');const value=await sales.downloadImportTemplate();return {text:await value.blob.text(),type:value.contentType};});expect(result.text.replace(/^\uFEFF/u,'').split('\r\n')[0].split(',')).toEqual(SALES_CSV_COLUMNS.map(c=>c.name));expect(result.type).toContain('text/csv');check.verify();});
test('TC-034 invalid filename is rejected before upload with field validation',async({page})=>{const check=monitor(page);await authenticate(page);await page.goto(origin+'/sales/imports/new');let posts=0;page.on('request',r=>{if(new URL(r.url()).pathname.endsWith('/sales-imports/upload'))posts++;});await page.getByLabel('銷售 CSV 檔案').setInputFiles({name:'orders.txt',mimeType:'text/plain',buffer:Buffer.from('bad')});await page.getByRole('button',{name:'上傳並預檢',exact:true}).click();await expect(page.getByRole('alert').first()).toContainText('請選擇 CSV 檔案');expect(posts).toBe(0);check.verify();});
test('TC-034 empty CSV is rejected without admission',async({page})=>{const check=monitor(page);await authenticate(page);await page.goto(origin+'/sales/imports/new');await page.getByLabel('銷售 CSV 檔案').setInputFiles({name:'empty.csv',mimeType:'text/csv',buffer:Buffer.alloc(0)});await page.getByRole('button',{name:'上傳並預檢',exact:true}).click();await expect(page.getByRole('alert').first()).toContainText('非空 CSV');check.verify();});
test('TC-039 actual stale confirmation refreshes cancelled facts without retrying a new event',async({page})=>{const check=monitor(page,[[409,'/api/v1/sales-imports/']]);await authenticate(page);const id=await upload(page,[{...row,externalOrderId:external()}]);await page.getByRole('button',{name:'確認匯入',exact:true}).click();await page.evaluate(async id=>{const {default:sales}=await import('/src/services/sales.js');const job=await sales.getImport(id);await sales.cancelImport(id,{eventId:crypto.randomUUID(),version:job.version});},id);await page.getByRole('button',{name:'提交匯入操作',exact:true}).click();await expect(page.getByRole('dialog').getByRole('alert').first()).toBeVisible();await expect(page.getByRole('status').filter({hasText:'來源訂單'}).filter({hasText:'已取消'})).toBeVisible();expect(await page.evaluate(key=>sessionStorage.getItem(key),`sales.import:${operatorId}:${id}`)).toBeNull();const [[effects]]=await f.db.query('SELECT COUNT(*) AS n FROM sales_orders WHERE source_intake_order_id IN (SELECT id FROM sales_intake_orders WHERE import_job_id=?)',[id]);expect(Number(effects.n)).toBe(0);check.verify();});
test('TC-035 existing external source prechecks duplicate without a second Sales effect',async({page})=>{const check=monitor(page);await authenticate(page);await ensureCompleted(page);const [[source]]=await f.db.query("SELECT external_order_id FROM sales_intake_orders WHERE import_job_id=? AND status='SUCCEEDED' ORDER BY id LIMIT 1",[completedId]);const id=await upload(page,[{...row,externalOrderId:source.external_order_id}]);await expect(page.getByRole('status').filter({hasText:'預檢完成'})).toContainText('重複 1');await expect(page.getByRole('status').filter({hasText:'預檢完成'})).toContainText('有效 0');const [[effects]]=await f.db.query('SELECT COUNT(*) AS n FROM sales_orders WHERE source_intake_order_id IN (SELECT id FROM sales_intake_orders WHERE import_job_id=?)',[id]);expect(Number(effects.n)).toBe(0);await page.getByRole('button',{name:'取消匯入',exact:true}).click();await page.getByRole('button',{name:'提交匯入操作',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'來源訂單'}).filter({hasText:'已取消'})).toBeVisible();check.verify();});
test('TC-035 READY and dismissed keyboard confirmation have no Sales or Inventory effects',async({page})=>{const check=monitor(page);await authenticate(page);const id=await upload(page,[{...row,externalOrderId:external()}]);await page.getByRole('button',{name:'確認匯入',exact:true}).focus();await page.keyboard.press('Enter');await expect(page.getByRole('dialog')).toBeVisible();await page.getByRole('button',{name:'返回',exact:true}).focus();await page.keyboard.press('Enter');await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByRole('button',{name:'確認匯入',exact:true})).toBeVisible();const [[effects]]=await f.db.query('SELECT COUNT(*) AS n FROM sales_orders WHERE source_intake_order_id IN (SELECT id FROM sales_intake_orders WHERE import_job_id=?)',[id]);expect(Number(effects.n)).toBe(0);check.verify();});
test('TC-038 structured completed results survive refresh and actual missing batch shows safe error',async({page})=>{const check=monitor(page,[[404,'/api/v1/sales-imports/']]);await authenticate(page);await ensureCompleted(page);await authenticate(page,viewer);await page.goto(origin+`/sales/imports/${completedId}`);await page.reload();await expect(page.getByRole('status').filter({hasText:'部分成功'})).toBeVisible();const download=page.waitForEvent('download');await page.getByRole('button',{name:'下載結果 CSV',exact:true}).click();const file=await (await download).path();const content=await readFile(file,'utf8');expect(content).toContain('SUCCEEDED');expect(content).toContain('INVALID');await page.goto(origin+`/sales/imports/${Number.MAX_SAFE_INTEGER}`);await expect(page.getByRole('alert')).toContainText('無法讀取批次');check.verify();});
