import assert from "node:assert/strict";
import test from "node:test";
import {randomUUID,createHash} from "node:crypto";
import {InventoryReservationService} from "../../../src/modules/inventory/InventoryReservationService.js";
import {inventoryOperationHash} from "../../../src/modules/inventory/InventoryOperationService.js";
const name="sales.importWorker",signal=new AbortController().signal,eventId=randomUUID(),line={sourceLineId:1,skuId:12,orderedBaseQuantity:5,minimumRemainingDays:0},command={actor:{userId:null,serviceName:name,claimedRoles:[],claimedPermissions:[name]},source:{documentId:"42",eventId},correlationId:eventId,payload:{warehouseId:2,expectedOrderVersion:1,lines:[line]}};
function fixture({principal={leaseOwner:"owner",signal},lease={owner:"owner",expires_at:101},owner=true,lines=[{id:1,sku_id:12,ordered_base_quantity:5}],changedSignal=false}={}){
 const calls=[];let checks=0;
 const tx={async query(sql){calls.push(sql);if(sql.includes("fr_job_leases"))return [lease?[lease]:[]];if(sql.includes("FROM sales_orders o"))return [owner?[{id:42,warehouse_id:2,version:1}]:[]];if(sql.includes("UNIX_TIMESTAMP"))return [[{now:100,now_ms:100000}]];if(sql.includes("FROM sales_order_lines"))return [lines];throw Error("Unexpected SQL");},async execute(){throw Error("Unexpected effect");}};
 const s=new InventoryReservationService({database:{withTransaction(){throw Error("Caller owns transaction");}},time:{nowMs:()=>100000,fileDate:()=>"2026-10-08"},authorize(){throw Error("Intake must not impersonate human");},authorizeSalesIntake:principal===null?undefined:()=>{checks++;return changedSignal&&checks>1?{...principal,signal:new AbortController().signal}:principal;},itemLookup:{},audit:{},locks:{},operations:{claim(){calls.push("claim");throw Error("claim reached");}}});return {s,tx,calls};
}
test("TC-038 Intake reserve-only sibling requires fixed live principal, matching signal and DB-clock lease before any claim",async()=>{
 for(const options of [{principal:null},{principal:{}},{principal:{leaseOwner:"owner",signal:AbortSignal.abort()}},{lease:null},{lease:{owner:"wrong",expires_at:101}},{lease:{owner:"owner",expires_at:100}},{changedSignal:true}]){const f=fixture(options);await assert.rejects(()=>f.s.reserveAvailableForSalesIntakeInTransaction(f.tx,command),{code:"PERMISSION_STALE"});assert.ok(!f.calls.includes("claim"));}
 const f=fixture();await assert.rejects(()=>f.s.reserveAvailableForSalesIntakeInTransaction(f.tx,command),/claim reached/u);assert.match(f.calls[0],/fr_job_leases.*FOR UPDATE/u);
});
test("TC-038 Intake reservation rejects human/backorder/arbitrary authority, source and owner membership before effect",async()=>{
 for(const patch of [{actor:{...command.actor,userId:1}},{actor:{...command.actor,serviceName:"sales.backorderAllocate"}},{actor:{...command.actor,claimedRoles:["admin"]}},{actor:{...command.actor,claimedPermissions:[name,"inventory.operation"]}},{source:{...command.source,eventId:"not-uuid"}},{source:{...command.source,module:"OTHER"}},{leaseOwner:"owner"}]){const f=fixture();await assert.rejects(()=>f.s.reserveAvailableForSalesIntakeInTransaction(f.tx,{...command,...patch}));assert.ok(!f.calls.includes("claim"));}
 for(const options of [{owner:false},{lines:[]},{lines:[{id:2,sku_id:12,ordered_base_quantity:5}]},{lines:[{id:1,sku_id:13,ordered_base_quantity:5}]},{lines:[{id:1,sku_id:12,ordered_base_quantity:6}]}]){const f=fixture(options);await assert.rejects(()=>f.s.reserveAvailableForSalesIntakeInTransaction(f.tx,command),{code:"INVENTORY_SOURCE_CONFLICT"});assert.ok(!f.calls.includes("claim"));}
});
test("TC-038 Intake replay verifies distinct exact root/child membership without ATP or manual authorization",async()=>{
 const f=fixture(),rootHash=inventoryOperationHash({commandType:"SALES_INTAKE_BATCH_RESERVE",payload:command.payload}),childHash=inventoryOperationHash({commandType:"SALES_INTAKE_LINE_RESERVE",payload:{rootOperationId:8,rootRequestHash:rootHash,...line}}),member={operationId:9,commandType:"SALES_INTAKE_LINE_RESERVE",sourceLineId:"1",requestHash:childHash,completedAt:100000,resultSummary:{...line,rootOperationId:8,rootRequestHash:rootHash,reservedBaseQuantity:3,uncoveredBaseQuantity:2,reservationId:10,version:1}},summary={operationId:8,warehouseId:2,expectedOrderVersion:1,lineCount:1,membershipDigest:createHash("sha256").update(`1:${childHash}\n`).digest("hex")};
 f.s.operations={async claim(_tx,input){assert.equal(input.commandType,"SALES_INTAKE_BATCH_RESERVE");assert.equal(input.actorUserId,null);assert.equal(input.actorLabel,name);return {operationId:8,replay:{resultType:"SALES_RESERVATION_BATCH",resultId:"42",resultSummary:summary}};},async listSalesBatchMembers(_tx,{afterId}){return afterId?[]:[member];}};assert.deepEqual((await f.s.reserveAvailableForSalesIntakeInTransaction(f.tx,command)).lines,[member.resultSummary]);member.commandType="SALES_BACKORDER_LINE_RESERVE";await assert.rejects(()=>f.s.reserveAvailableForSalesIntakeInTransaction(f.tx,command),{code:"INVENTORY_SOURCE_CONFLICT"});
});
test("TC-038 original running signal stays pinned across owner validation, claim and completed replay",async()=>{
 const f=fixture(),a=new AbortController(),b=new AbortController();let checks=0;f.s.authorizeSalesIntake=()=>{checks++;if(checks===5)a.abort();return {leaseOwner:"owner",signal:checks<5?a.signal:b.signal};};await assert.rejects(()=>f.s.reserveAvailableForSalesIntakeInTransaction(f.tx,command),{code:"PERMISSION_STALE"});assert.ok(!f.calls.includes("claim"));
});
