import assert from "node:assert/strict";
import test from "node:test";
import {SalesImportQueryService,validateSalesImportQuery,toSalesImportSummary} from "../../../src/modules/sales/SalesImportQueryService.js";
import {ListSalesImportsHandler,GetSalesImportHandler} from "../../../src/handlers/sales-imports/salesImportQueryHandlers.js";
import {ListSalesImportOrdersHandler,ListSalesImportErrorsHandler} from "../../../src/handlers/sales-imports/salesImportOrderQueryHandlers.js";
import {salesImportQueryRequest,SALES_IMPORT_JOB_RESPONSE,SALES_IMPORT_ORDERS_RESPONSE,SALES_IMPORT_ERRORS_RESPONSE} from "../../../src/handlers/sales-imports/salesImportSchemas.js";
const claims={actorId:1,claimedRoles:["viewer"],claimedPermissions:["sales.view"]};
function database(rows={}){const calls=[],tx={async query(sql,params){calls.push({sql,params});if(sql.startsWith("SELECT username FROM users"))return [[{username:"viewer"}]];if(sql.includes("FROM roles r JOIN user_roles"))return [[{name:"viewer"}]];if(sql.includes("SELECT DISTINCT p.name"))return [[{name:"sales.view"}]];if(sql.includes("FROM sales_import_jobs"))return [rows.jobs??[]];if(sql.includes("FROM sales_intake_orders"))return [rows.orders??[]];if(sql.includes("FROM sales_intake_errors"))return [rows.errors??[]];throw Error("Unexpected query");}},db={query:tx.query,withTransaction:work=>work(tx)};return {db,calls};}
test("TC-036 Import queries bound page/offset, reject sort injection and unknown filters before SQL",()=>{
 assert.equal(validateSalesImportQuery({}).pageSize,20);
 for(const input of [{extra:1},{pageSize:101},{page:Number.MAX_SAFE_INTEGER,pageSize:100},{page:1.1},{sortBy:"constructor"},{sortBy:"created_at DESC;"},{descending:"false"},{createdFrom:2,createdTo:1},{actorId:0},{status:"UNKNOWN"},{fileName:"x".repeat(256)}])assert.throws(()=>validateSalesImportQuery(input),{code:"SALES_INPUT_INVALID"});
 const req={auth:{claims:{sub:"1",roles:["viewer"],permissions:["sales.view"]}},input:{query:{page:"2",pageSize:"10",descending:"false"}}},r=salesImportQueryRequest(req,"jobs");assert.equal(r.input.page,2);assert.equal(r.input.descending,false);assert.equal(req.input.query.page,"2");
});
test("TC-036 safe Import summary permits writes only from fresh import permissions and explicit states",()=>{
 const row={id:1,batch_number:"SI-261008-000001",status:"READY",version:1,original_file_name:"synthetic.csv",template_version:"1.0",total_row_count:2,source_order_count:2,valid_count:1,invalid_count:1,duplicate_count:0,warning_count:1,success_count:0,failed_count:0,created_by:1,confirmed_by:null,created_at:1,updated_at:1,completed_at:null,files_purged_at:null,source_file_path:"private.csv",file_sha256:"private",lease_owner:"private",safe_payload:{secret:"private"}};
 const summary=toSalesImportSummary(row,{permissions:["sales.view"]});assert.deepEqual(summary.allowedActions,[]);assert.doesNotMatch(JSON.stringify(summary),/private|safe_payload|lease_owner|file_sha256/);assert.deepEqual(toSalesImportSummary(row,{permissions:["sales.view","sales.import"]}).allowedActions,["confirm","cancel"]);assert.deepEqual(toSalesImportSummary({...row,status:"PROCESSING"},{permissions:["sales.view","sales.import"]}).allowedActions,[]);
});
test("TC-036 absent parent and wrong-parent child errors expose the same404 before reading errors",async()=>{
 for(const rows of [{jobs:[]},{jobs:[{id:1}],orders:[]}]){const f=database(rows),service=new SalesImportQueryService({database:f.db});await assert.rejects(()=>service.errors({claims,id:1,orderId:2,input:{}}),{code:"SALES_IMPORT_NOT_FOUND",statusCode:404});assert.ok(f.calls.every(call=>!call.sql.includes("FROM sales_intake_errors")));const child=f.calls.find(call=>call.sql.includes("FROM sales_intake_orders"));if(child)assert.deepEqual(child.params,[2,1]);}
});
test("TC-036 four read handlers require view and closed safe bounded response contracts",()=>{
 for(const Handler of [ListSalesImportsHandler,GetSalesImportHandler,ListSalesImportOrdersHandler,ListSalesImportErrorsHandler]){assert.equal(Handler.api.method,"GET");assert.ok(Handler.api.path.startsWith("/api/v1/sales-imports"));assert.deepEqual(Handler.api.authorizationPolicies[0].options.permissions,["sales.view"]);}
 for(const schema of [SALES_IMPORT_JOB_RESPONSE,SALES_IMPORT_ORDERS_RESPONSE,SALES_IMPORT_ERRORS_RESPONSE]){assert.equal(schema.additionalProperties,false);assert.doesNotMatch(JSON.stringify(schema),/safe_payload|file_sha256|lease_owner|source_file_path|value_summary/);}
 assert.equal(SALES_IMPORT_ORDERS_RESPONSE.properties.items.maxItems,100);assert.equal(SALES_IMPORT_ERRORS_RESPONSE.properties.items.maxItems,100);
});
test("TC-036 source result filters validate errorCode and bind exact error/source identity before pagination",async()=>{assert.equal(validateSalesImportQuery({errorCode:'SALES_QUANTITY_INVALID',externalOrderId:'exact'},'orders').errorCode,'SALES_QUANTITY_INVALID');for(const value of ['x'.repeat(81),'bad\ncode'])assert.throws(()=>validateSalesImportQuery({errorCode:value},'orders'),{code:'SALES_INPUT_INVALID'});const f=database({jobs:[{id:1}],orders:[{total:0}]});await new SalesImportQueryService({database:f.db}).orders({claims,id:1,input:{errorCode:'SALES_QUANTITY_INVALID',externalOrderId:'exact'}});const source=f.calls.find(call=>call.sql.includes('COUNT(*)')&&call.sql.includes('sales_intake_orders'));assert.match(source.sql,/EXISTS.*sales_intake_errors/u);assert.ok(source.params.includes('SALES_QUANTITY_INVALID'));assert.ok(source.params.includes('exact'));assert.ok(!source.sql.includes('SALES_QUANTITY_INVALID'));const result=salesImportQueryRequest({auth:{claims:{sub:'1',roles:['viewer'],permissions:['sales.view']}},input:{query:{errorCode:'SALES_QUANTITY_INVALID'}}},'orders');assert.equal(result.input.errorCode,'SALES_QUANTITY_INVALID');});
