import assert from "node:assert/strict";
import test from "node:test";
import {mkdtemp,mkdir,writeFile,readFile,lstat,symlink,rm} from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import {SalesFileRetentionJob} from "../../../src/services/salesJobs/jobs/SalesFileRetentionJob.js";
async function fixture(t,{unsafe=false,missing=false,expired=false}={}){const root=await mkdtemp(path.join(os.tmpdir(),'sales-retention-')),batch='SI-202607-000001',directory=path.join(root,batch);t.after(()=>rm(root,{recursive:true,force:true}));await mkdir(directory,{mode:0o700});const outside=path.join(root,'keep');await writeFile(outside,'keep',{mode:0o600});if(unsafe)await symlink(outside,path.join(directory,'source.csv'));else if(!missing)await writeFile(path.join(directory,'source.csv'),'source',{mode:0o600});await writeFile(path.join(directory,'result.csv'),'result',{mode:0o600});const signal=new AbortController().signal,job={name:'sales.fileRetention',serviceName:'job.salesFileRetention',method:'run',scope:'cluster',enabled:true},scheduler={started:true,stopped:false,schedulerConfig:{enabled:true},owner:'owner',jobs:new Map([['sales.fileRetention',job]]),running:new Map([['sales.fileRetention',{controller:{signal}}]])},writes=[];
 const tx={async query(sql){if(sql.includes('fr_job_leases'))return [[{owner:'owner',expires_at:expired?1:9999999999}]];if(sql.includes('UNIX_TIMESTAMP'))return [[{now:100000000,now_ms:100000000000}]];if(sql.includes('FROM sales_import_jobs'))return [[{id:1,batch_number:batch,source_file_path:batch+'/source.csv',result_file_path:batch+'/result.csv',status:'COMPLETED',completed_at:1}]];if(sql.includes('FROM sales_intake_orders'))return [[{id:2}]];throw Error('unexpected query');},async execute(sql,args){writes.push({sql,args});return [{affectedRows:1}];}},database={withTransaction:fn=>fn(tx)},services={require:key=>({scheduler,mysqldatabase:database,time:{nowMs:()=>100000000000},logging:{logger:{info:async()=>{}}}})[key]},instance=new SalesFileRetentionJob({config:{sales:{importFileRetentionDays:90,intakePayloadRetentionDays:90}},services,options:{root}});return {root,directory,outside,signal,instance,scheduler,writes};}
test('TC-041 retention refuses missing actual running signal before SQL or files',async()=>{let queries=0;const services={require:key=>({scheduler:{},mysqldatabase:{withTransaction(){queries++;}},logging:{logger:{}},time:{}})[key]},job=new SalesFileRetentionJob({config:{sales:{}},services});await assert.rejects(()=>job.run(new AbortController().signal));assert.equal(queries,0);assert.equal(SalesFileRetentionJob.jobs[0].scope,'cluster');assert.equal(SalesFileRetentionJob.jobs[0].intervalMs,86400000);});
test('TC-041 retention deletes only owned source/result and clears payload without deleting structured facts',async t=>{const f=await fixture(t);const result=await f.instance.run(f.signal);assert.equal(result.filesPurged,1);assert.equal(result.payloadsPurged,1);await assert.rejects(()=>lstat(path.join(f.directory,'source.csv')),{code:'ENOENT'});assert.equal(await readFile(f.outside,'utf8'),'keep');assert.ok(f.writes.some(r=>r.sql.includes('safe_payload=NULL')));assert.ok(f.writes.some(r=>r.sql.includes('files_purged_at')));assert.ok(f.writes.every(r=>!/^DELETE /u.test(r.sql)));});
test('TC-041 retention preserves symlink target and marker on unsafe path',async t=>{const f=await fixture(t,{unsafe:true});await assert.rejects(()=>f.instance.run(f.signal),/Sales file retention incomplete/u);assert.equal(await readFile(f.outside,'utf8'),'keep');assert.equal((await lstat(path.join(f.directory,'source.csv'))).isSymbolicLink(),true);assert.ok(!f.writes.some(r=>r.sql.includes('files_purged_at')));});
test('TC-041 retention tolerates missing artifacts after interrupted deletion',async t=>{const f=await fixture(t,{missing:true});assert.equal((await f.instance.run(f.signal)).filesPurged,1);});
test('TC-041 expired DB lease preserves all files and payload',async t=>{const f=await fixture(t,{expired:true});await assert.rejects(()=>f.instance.run(f.signal));assert.equal(await readFile(path.join(f.directory,'source.csv'),'utf8'),'source');assert.equal(f.writes.length,0);});
