import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync, readdirSync } from "node:fs";
import { lstat, mkdir, mkdtemp, rm, symlink, writeFile } from "node:fs/promises";
import { randomBytes } from "node:crypto";
import os from "node:os";
import path from "node:path";

import {
  defaultConfigurationSource,
  validateApplicationConfiguration
} from "../src/framework/configuration/applicationConfiguration.js";
import { normalizeSupplierConfig } from "../src/modules/supplier/normalizeSupplierConfig.js";
import { JOB_NAME_PATTERN } from "../src/services/scheduler/normalizeSchedulerConfig.js";
import {
  listSupplierImportFiles,
  newSupplierImportStoredName,
  SUPPLIER_IMPORT_JOB_NAMES,
  supplierImportFilePath
} from "../src/services/supplierImport/supplierImportFiles.js";

/**
 * TASK-041（T41）：import 嘅容量、路徑同背景工作邊界，喺開機或者第一次用嗰陣就驗到。
 * 上限本身（maxFileBytes／maxRows／fileRetentionDays）嘅邊界喺 supplierConfig.test.js。
 */

test("the import root is optional until import is deployed, and must be absolute when given", () => {
  assert.equal(normalizeSupplierConfig({}).import.root, null, "no root: import is not deployed, startup is not blocked");
  assert.equal(normalizeSupplierConfig({ import: { root: "  " } }).import.root, null);
  assert.equal(normalizeSupplierConfig({ import: { root: "/var/lib/erp/supplier-imports/../imports/" } }).import.root,
    "/var/lib/erp/imports", "normalised, so an overlap check compares real paths");
  assert.throws(() => normalizeSupplierConfig({ import: { root: "var/lib/erp/imports" } }),
    /"import.root" must be an absolute path/u, "a relative root would follow the process's working directory");
  for (const root of ["/", "//", "/srv/.."]) {
    assert.throws(() => normalizeSupplierConfig({ import: { root } }), /must not be a filesystem root/u, root);
  }
});

test("the Supplier import root may not overlap a Customer import or attachment root", () => {
  const source = defaultConfigurationSource();
  const configure = (supplierRoot, customerRoot = "/srv/erp/customer-imports") => validateApplicationConfiguration({
    ...source,
    customer: { ...source.customer, import: { root: customerRoot } },
    supplier: { ...source.supplier, import: { root: supplierRoot } }
  });

  assert.equal(configure("/srv/erp/supplier-imports").supplier.import.root, "/srv/erp/supplier-imports");
  assert.doesNotThrow(() => configure("/srv/erp/customer-imports-2"), "a shared prefix is not containment");
  for (const [label, root] of [["the same root", "/srv/erp/customer-imports"],
    ["inside it", "/srv/erp/customer-imports/supplier"], ["around it", "/srv/erp"]]) {
    assert.throws(() => configure(root), /import.root must not contain, or sit inside, a Customer/u, label);
  }
  assert.doesNotThrow(() => configure("/srv/erp", null), "no Customer import root, nothing to collide with");

  // 附件嘅三個 root 一樣計（HD-039 C；REV-059 L-1）。附件要 Customer encryption ring 同 clamd。
  const key = () => ({ activeKeyId: "k", keyRing: { k: randomBytes(32).toString("base64") } });
  const bankEncryption = key();
  const bankLookup = key();
  const withAttachments = (supplierRoot) => validateApplicationConfiguration({
    ...source,
    customer: { bankEncryption, bankLookup, attachment: {
      generalRoot: "/srv/att/general", bankSensitiveRoot: "/srv/att/bank", tempRoot: "/srv/att/temp",
      malwareScanner: { mode: "clamd", host: "127.0.0.1", port: 3310 } } },
    supplier: { ...source.supplier, bankEncryption, bankLookup, import: { root: supplierRoot } }
  });
  assert.doesNotThrow(() => withAttachments("/srv/supplier-imports"));
  for (const root of ["/srv/att/general/supplier", "/srv/att/bank", "/srv/att/temp/supplier", "/srv/att"]) {
    assert.throws(() => withAttachments(root), /import.root must not contain, or sit inside, a Customer/u, root);
  }
});

test("the Supplier import root may not overlap an Item media or import directory (HD-040)", () => {
  // Item 嘅 media 清理會刪目錄入面一日以上冇人引用嘅檔 —— 重疊就會刪走 Supplier 嘅 import 原檔。
  const source = defaultConfigurationSource();
  const configure = (supplierRoot, item) => validateApplicationConfiguration({
    ...source,
    item: { ...source.item, mediaDirectory: "/srv/item/media", importDirectory: "/srv/item/imports", ...item },
    supplier: { ...source.supplier, import: { root: supplierRoot } }
  });
  assert.doesNotThrow(() => configure("/srv/supplier-imports"));
  for (const [label, supplierRoot, item] of [
    ["media inside the Supplier root", "/srv/supplier", { mediaDirectory: "/srv/supplier/source" }],
    ["Supplier root inside media", "/srv/item/media/supplier", {}],
    ["same as the Item import directory", "/srv/item/imports", {}]
  ]) {
    assert.throws(() => configure(supplierRoot, item), /or an Item media or import directory/u, label);
  }
});

test("stored names are generated by the server, and a path cannot be steered out of its kind directory", () => {
  const first = newSupplierImportStoredName();
  assert.match(first, /^[0-9a-f]{64}$/u);
  assert.notEqual(newSupplierImportStoredName(), first);

  assert.equal(supplierImportFilePath("/srv/imports", "source", first), `/srv/imports/source/${first}`);
  assert.equal(supplierImportFilePath("/srv/imports", "result", first), `/srv/imports/result/${first}`);
  for (const [label, args] of [
    ["an uploader's file name", ["/srv/imports", "source", "suppliers.csv"]],
    ["a traversal", ["/srv/imports", "source", `../${first}`]],
    ["a traversal after the name", ["/srv/imports", "source", `${first}/../../x`]],
    ["an unknown kind", ["/srv/imports", "..", first]],
    ["a relative root", ["imports", "source", first]]
  ]) {
    assert.throws(() => supplierImportFilePath(...args), TypeError, label);
  }
});

test("listing for cleanup never follows a symlink or leaves the root", async (t) => {
  const base = await mkdtemp(path.join(os.tmpdir(), "supplier-import-"));
  t.after(() => rm(base, { recursive: true, force: true }));
  const root = path.join(base, "root");
  const outside = path.join(base, "outside");
  await mkdir(path.join(root, "source"), { recursive: true });
  await mkdir(outside);
  const kept = newSupplierImportStoredName();
  const victim = newSupplierImportStoredName();
  await writeFile(path.join(root, "source", kept), "a");
  await writeFile(path.join(outside, victim), "must survive");
  await symlink(path.join(outside, victim), path.join(root, "source", newSupplierImportStoredName()));
  await symlink(outside, path.join(root, "source", newSupplierImportStoredName()));
  await mkdir(path.join(root, "source", newSupplierImportStoredName()));
  await writeFile(path.join(root, "source", "notes.txt"), "not ours");

  assert.deepEqual(await listSupplierImportFiles(root, "source"),
    [{ storedName: kept, path: path.join(root, "source", kept) }], "only the regular file the server named");
  assert.deepEqual(await listSupplierImportFiles(root, "result"), [], "a kind directory not created yet holds nothing");

  // Root 或者 kind 目錄本身係 symlink：拒絕，唔會跟去 outside。
  await symlink(outside, path.join(base, "linked-root"));
  for (const spelling of ["linked-root", "linked-root/", "linked-root/."]) {
    await assert.rejects(() => listSupplierImportFiles(path.join(base, spelling), "source"), /not a regular directory/u,
      `${spelling}: a trailing slash must not make lstat follow the link (REV-059 L-4)`);
  }
  await symlink(outside, path.join(root, "result"));
  await assert.rejects(() => listSupplierImportFiles(root, "result"), /not a regular directory/u);
  await assert.rejects(() => listSupplierImportFiles(root, "../outside"), TypeError);

  // 另一個 filesystem mount 喺 kind 目錄：拒絕。真 mount 要 root 權限，所以注入 lstat（REV-059 L-3）。
  const mounted = async (target) => {
    const info = await lstat(target);
    return target === path.join(root, "source") ? Object.assign(Object.create(info), { dev: info.dev + 1 }) : info;
  };
  await assert.rejects(() => listSupplierImportFiles(root, "source", { lstat: mounted }), /must be on the root's filesystem/u);
});

// 只證到三個名唔同、合法。分開控制要等 T42／T48 嘅 service 真係用呢三個名宣告 job
// （REV-059 M-1，見 implementation/62_task_041_carry_forward.md）。
test("precheck, worker and purge have three distinct, valid job names", () => {
  const names = Object.values(SUPPLIER_IMPORT_JOB_NAMES);
  assert.equal(new Set(names).size, 3);
  for (const name of names) assert.match(name, JOB_NAME_PATTERN);
});

test("CSV is parsed by one locked csv-parse / csv-stringify, never by splitting on commas", () => {
  const repo = new URL("../../", import.meta.url);
  const lock = JSON.parse(readFileSync(new URL("package-lock.json", repo), "utf8"));
  for (const name of ["csv-parse", "csv-stringify"]) {
    const entries = Object.entries(lock.packages).filter(([key]) => key === `node_modules/${name}` || key.endsWith(`/node_modules/${name}`));
    assert.equal(entries.length, 1, `${name} is locked exactly once`);
    assert.ok(entries[0][1].integrity, `${name} is pinned by integrity`);
    const declared = JSON.parse(readFileSync(new URL("server/package.json", repo), "utf8")).dependencies[name];
    assert.ok(declared, `${name} is a declared server dependency`);
  }

  // RFC 4180 欄位可以有引號包住嘅逗號同換行；自己 split 會切錯。Supplier 嘅 code 一律唔准，
  // 字串同 regex 兩種寫法都算（REV-059 M-2）。
  const naiveSplit = /\.split\(\s*(?:(["'`])(?:,|\\n|\\r\\n)\1|\/[^/\n]*(?:,|\\n)[^/\n]*\/[a-z]*)\s*\)/u;
  for (const sample of ['line.split(",")', "line.split(',')", "text.split(\"\\n\")", "text.split('\\r\\n')", "line.split(/,/)",
    "line.split(/\\s*,\\s*/u)", "text.split(/\\r?\\n/)"]) {
    assert.match(sample, naiveSplit, `the scan recognises ${sample}`);
  }
  assert.doesNotMatch('code.split("-")', naiveSplit);

  // 掃模組 manifest 嘅全部 source_paths —— 將來嘅 import／export handler 會放喺嗰度。
  const { scope } = JSON.parse(readFileSync(new URL("docs/supplier_management/00_module_manifest.json", repo), "utf8"));
  const offenders = [];
  let scanned = 0;
  for (const glob of scope.source_paths) {
    assert.match(glob, /\/\*\*$/u, `${glob}: the scan only knows directory globs; teach it before adding another shape`);
    const directory = new URL(`${glob.slice(0, -3)}/`, repo);
    let entries;
    try { entries = readdirSync(directory, { recursive: true, withFileTypes: true }); }
    catch (error) { if (error.code === "ENOENT") continue; throw error; }   // 未建立嘅目錄（例如 supplier-imports）
    for (const entry of entries) {
      if (!entry.isFile() || !/\.(?:js|vue)$/u.test(entry.name)) continue;
      const file = path.join(entry.parentPath, entry.name);
      scanned += 1;
      if (naiveSplit.test(readFileSync(file, "utf8"))) offenders.push(file);
    }
  }
  assert.ok(scanned > 50, `the scan read ${scanned} files; fewer means it is looking in the wrong place`);
  assert.deepEqual(offenders, []);
});
