import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync, readdirSync } from "node:fs";
import { mkdir, mkdtemp, rm, symlink, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";

import {
  defaultConfigurationSource,
  validateApplicationConfiguration
} from "../src/framework/configuration/applicationConfiguration.js";
import { normalizeSupplierConfig } from "../src/modules/supplier/normalizeSupplierConfig.js";
import { JOB_NAME_PATTERN, normalizeSchedulerConfig } from "../src/services/scheduler/normalizeSchedulerConfig.js";
import {
  listSupplierImportFiles,
  newSupplierImportStoredName,
  SUPPLIER_IMPORT_JOB_NAMES,
  supplierImportFilePath
} from "../src/services/supplierImport/supplierImportFiles.js";

/**
 * TASK-041（T41）：import 嘅容量、路徑同背景工作邊界，喺開機或者第一次用嗰陣就驗到。
 * 上限本身（maxFileBytes／maxRows／fileRetentionDays）嘅邊界喺 supplierConfig.test.js。
 */

test("the import root is optional until import is deployed, and must be absolute when given", () => {
  assert.equal(normalizeSupplierConfig({}).import.root, null, "no root: import is not deployed, startup is not blocked");
  assert.equal(normalizeSupplierConfig({ import: { root: "  " } }).import.root, null);
  assert.equal(normalizeSupplierConfig({ import: { root: "/var/lib/erp/supplier-imports/../imports/" } }).import.root,
    "/var/lib/erp/imports", "normalised, so an overlap check compares real paths");
  assert.throws(() => normalizeSupplierConfig({ import: { root: "var/lib/erp/imports" } }),
    /"import.root" must be an absolute path/u, "a relative root would follow the process's working directory");
});

test("the Supplier import root may not overlap a Customer import or attachment root", () => {
  const source = defaultConfigurationSource();
  const configure = (supplierRoot, customerRoot = "/srv/erp/customer-imports") => validateApplicationConfiguration({
    ...source,
    customer: { ...source.customer, import: { root: customerRoot } },
    supplier: { ...source.supplier, import: { root: supplierRoot } }
  });

  assert.equal(configure("/srv/erp/supplier-imports").supplier.import.root, "/srv/erp/supplier-imports");
  assert.doesNotThrow(() => configure("/srv/erp/customer-imports-2"), "a shared prefix is not containment");
  for (const [label, root] of [["the same root", "/srv/erp/customer-imports"],
    ["inside it", "/srv/erp/customer-imports/supplier"], ["around it", "/srv/erp"]]) {
    assert.throws(() => configure(root), /import.root must not contain, or sit inside, a Customer/u, label);
  }
  assert.doesNotThrow(() => configure("/srv/erp", null), "no Customer import root, nothing to collide with");
});

test("stored names are generated by the server, and a path cannot be steered out of its kind directory", () => {
  const first = newSupplierImportStoredName();
  assert.match(first, /^[0-9a-f]{64}$/u);
  assert.notEqual(newSupplierImportStoredName(), first);

  assert.equal(supplierImportFilePath("/srv/imports", "source", first), `/srv/imports/source/${first}`);
  assert.equal(supplierImportFilePath("/srv/imports", "result", first), `/srv/imports/result/${first}`);
  for (const [label, args] of [
    ["an uploader's file name", ["/srv/imports", "source", "suppliers.csv"]],
    ["a traversal", ["/srv/imports", "source", `../${first}`]],
    ["an unknown kind", ["/srv/imports", "..", first]],
    ["a relative root", ["imports", "source", first]]
  ]) {
    assert.throws(() => supplierImportFilePath(...args), TypeError, label);
  }
});

test("listing for cleanup never follows a symlink or leaves the root", async (t) => {
  const base = await mkdtemp(path.join(os.tmpdir(), "supplier-import-"));
  t.after(() => rm(base, { recursive: true, force: true }));
  const root = path.join(base, "root");
  const outside = path.join(base, "outside");
  await mkdir(path.join(root, "source"), { recursive: true });
  await mkdir(outside);
  const kept = newSupplierImportStoredName();
  const victim = newSupplierImportStoredName();
  await writeFile(path.join(root, "source", kept), "a");
  await writeFile(path.join(outside, victim), "must survive");
  await symlink(path.join(outside, victim), path.join(root, "source", newSupplierImportStoredName()));
  await symlink(outside, path.join(root, "source", newSupplierImportStoredName()));
  await mkdir(path.join(root, "source", newSupplierImportStoredName()));
  await writeFile(path.join(root, "source", "notes.txt"), "not ours");

  assert.deepEqual(await listSupplierImportFiles(root, "source"),
    [{ storedName: kept, path: path.join(root, "source", kept) }], "only the regular file the server named");
  assert.deepEqual(await listSupplierImportFiles(root, "result"), [], "a kind directory not created yet holds nothing");

  // Root 或者 kind 目錄本身係 symlink：拒絕，唔會跟去 outside。
  await symlink(outside, path.join(base, "linked-root"));
  await assert.rejects(() => listSupplierImportFiles(path.join(base, "linked-root"), "source"), /not a regular directory/u);
  await symlink(outside, path.join(root, "result"));
  await assert.rejects(() => listSupplierImportFiles(root, "result"), /not a regular directory/u);
  await assert.rejects(() => listSupplierImportFiles(root, "../outside"), TypeError);
});

test("precheck, worker and purge have their own job names, so the scheduler controls each one separately", () => {
  const names = Object.values(SUPPLIER_IMPORT_JOB_NAMES);
  assert.equal(new Set(names).size, 3);
  for (const name of names) assert.match(name, JOB_NAME_PATTERN);

  const scheduler = normalizeSchedulerConfig({ jobs: { [SUPPLIER_IMPORT_JOB_NAMES.purge]: { enabled: false } } });
  assert.equal(scheduler.jobs[SUPPLIER_IMPORT_JOB_NAMES.purge].enabled, false);
  assert.equal(scheduler.jobs[SUPPLIER_IMPORT_JOB_NAMES.precheck], undefined, "turning purge off leaves precheck alone");
  assert.equal(scheduler.jobs[SUPPLIER_IMPORT_JOB_NAMES.worker], undefined);
});

test("CSV is parsed by one locked csv-parse / csv-stringify, never by splitting on commas", () => {
  const repo = new URL("../../", import.meta.url);
  const lock = JSON.parse(readFileSync(new URL("package-lock.json", repo), "utf8"));
  for (const name of ["csv-parse", "csv-stringify"]) {
    const entries = Object.entries(lock.packages).filter(([key]) => key === `node_modules/${name}` || key.endsWith(`/node_modules/${name}`));
    assert.equal(entries.length, 1, `${name} is locked exactly once`);
    assert.ok(entries[0][1].integrity, `${name} is pinned by integrity`);
    const declared = JSON.parse(readFileSync(new URL("server/package.json", repo), "utf8")).dependencies[name];
    assert.ok(declared, `${name} is a declared server dependency`);
  }

  // RFC 4180 欄位可以有引號包住嘅逗號同換行；自己 split 會切錯。Supplier 嘅 code 一律唔准。
  const naiveSplit = /\.split\(\s*(["'`]),\1\s*\)/u;
  assert.match('line.split(",")', naiveSplit, "the scan recognises the pattern it forbids");
  const offenders = [];
  for (const directory of ["server/src/modules/supplier", "server/src/services/supplierImport", "server/src/handlers/suppliers"]) {
    for (const entry of readdirSync(new URL(`${directory}/`, repo), { recursive: true, withFileTypes: true })) {
      if (!entry.isFile() || !entry.name.endsWith(".js")) continue;
      const file = path.join(entry.parentPath, entry.name);
      if (naiveSplit.test(readFileSync(file, "utf8"))) offenders.push(file);
    }
  }
  assert.deepEqual(offenders, []);
});
