import { flushPromises, mount } from "@vue/test-utils";
import { createPinia, setActivePinia } from "pinia";
import { QSelect, Quasar } from "quasar";
import { h } from "vue";
import { createMemoryHistory, createRouter, RouterView } from "vue-router";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
vi.mock("@/services/sales.js", () => ({ default: { lookupCustomers: vi.fn(), lookupSkus: vi.fn(), lookupWarehouses: vi.fn(), getQuotation: vi.fn(), createQuotation: vi.fn(), updateQuotation: vi.fn(), convertQuotation: vi.fn() } }));
import sales from "@/services/sales.js";
import DifferencePanel from "@/components/sales/QuotationDifferencePanel.vue";
import Form from "@/components/sales/SalesQuotationForm.vue";
import { page as createPage } from "@/pages/sales/SalesQuotationCreatePage.vue";
import EditPage, { page as editPage } from "@/pages/sales/SalesQuotationEditPage.vue";
const customer = { customerId: 2, customerCode: "C2", displayName: "合成客戶", defaultCurrencyCode: "HKD", defaultPaymentTermId: 4, credit: { status: "normal", creditLimit: "10000.0000", currencyCode: "HKD" } };
const sku = { skuId: 3, skuCode: "SKU3", skuName: "合成貨品", itemName: "貨品", suggestedPrice: { amount: "3.3333", currency: "HKD" }, uoms: [{ skuUomId: 5, uomCode: "EA", uomName: "件", isDefaultSale: true }] };
const document = { id: 8, number: "QT-202610-000008", version: 2, status: "DRAFT", customerId: 2, customerCode: "C2", customerName: "合成客戶", currencyCode: "HKD", paymentTermId: 4, paymentTermName: "30 天", quotationDate: "2026-10-06", validUntil: "2026-10-30", externalReference: "", notes: "", totalAmount: "6.6666", lines: [{ id: 11, skuId: 3, skuUomId: 5, skuCode: "SKU3", skuName: "合成貨品", uomCode: "EA", quantity: "2.000000", unitSellingPrice: "3.3333", lineNote: "" }] };
let wrapper;
async function mountForm(props = {}) {
 const router = createRouter({ history: createMemoryHistory(), routes: [{ path: "/edit", component: { render: () => h(Form, props) } }, { path: "/other", component: { template: "<div>other</div>" } }] });
 await router.push("/edit");await router.isReady();wrapper=mount({ render: () => h(RouterView) }, { global: { plugins: [Quasar, router] }, attachTo: window.document.body });await flushPromises();return { form: wrapper.findComponent(Form), router };
}
const input = label => wrapper.findAll(".q-field").find(field => field.text().includes(label)).find("input, textarea");
const select = label => wrapper.findAllComponents(QSelect).find(field => field.props("label") === label);
async function submit(){ await wrapper.find("form").trigger("submit"); await flushPromises(); }
beforeEach(() => { setActivePinia(createPinia());vi.clearAllMocks();sales.lookupCustomers.mockResolvedValue({items:[customer],total:1});sales.lookupSkus.mockResolvedValue({items:[sku],total:1});sales.lookupWarehouses.mockResolvedValue({items:[{id:6,code:"W6",name:"倉庫"}],total:1}); });
afterEach(() => { wrapper?.unmount();wrapper=null;vi.restoreAllMocks();window.document.body.innerHTML=""; });
describe("TC-019 Quotation editor", () => {
 it("protects direct create/edit routes with both Sales permissions", () => { expect(createPage.requires.permissions).toEqual(["sales.view","sales.mgmt"]);expect(editPage.requires.permissions).toEqual(["sales.view","sales.mgmt"]); });
 it("retains exact editable decimal strings and existing IDs, excludes server-owned fields", async () => { const save=vi.fn().mockResolvedValue({quotation:document,warnings:[]});await mountForm({document,onSave:save});await submit();expect(save).toHaveBeenCalledWith(expect.objectContaining({version:2,lines:[{id:11,skuId:3,skuUomId:5,quantity:"2.000000",unitSellingPrice:"3.3333",lineNote:""}]}));expect(save.mock.calls[0][0]).not.toHaveProperty("totalAmount");expect(wrapper.text()).toContain("6.6666"); });
 it("reuses the same immutable event and payload after an uncertain outcome", async () => { const save=vi.fn().mockRejectedValueOnce(Object.assign(new Error("逾時"),{code:"TIMEOUT"})).mockResolvedValue({quotation:document,warnings:[]});await mountForm({document,onSave:save});await submit();expect(wrapper.text()).toContain("結果尚未確認");expect(input("數量 1").element.matches(":disabled")).toBe(true);await submit();expect(save.mock.calls[1][0]).toEqual(save.mock.calls[0][0]); });
 it("surfaces object-shaped domain errors safely and retains stale inputs until explicit reload", async () => { const save=vi.fn().mockRejectedValue(Object.assign(new Error("版本已更改"),{code:"VERSION_CONFLICT",details:{currentVersion:3}}));const {form}=await mountForm({document,onSave:save});await input("備註").setValue("保留輸入");await submit();expect(wrapper.text()).toContain("保留");expect(form.emitted("reload")).toBeUndefined();vi.spyOn(window,"confirm").mockReturnValue(true);await wrapper.findAll("button").find(b=>b.text()==="載入最新資料").trigger("click");expect(form.emitted("reload")).toHaveLength(1); });
 it("takes Customer defaults and never invents an FX price for another currency", async () => { await mountForm({onSave:vi.fn()});select("客戶 *").vm.$emit("update:modelValue",customer);await flushPromises();expect(input("貨幣 *").element.value).toBe("HKD");select("搜尋 SKU").vm.$emit("update:modelValue",sku);await flushPromises();await wrapper.findAll("button").find(b=>b.text()==="新增明細").trigger("click");await flushPromises();expect(input("售價 1").element.value).toBe("3.3333");await input("貨幣 *").setValue("USD");await flushPromises();expect(input("售價 1").element.value).toBe("");expect(wrapper.text()).toContain("不自動換算"); });
 it("focuses an existing SKU/UOM instead of adding a duplicate", async () => { await mountForm({document,onSave:vi.fn()});select("搜尋 SKU").vm.$emit("update:modelValue",sku);await flushPromises();await wrapper.findAll("button").find(b=>b.text()==="新增明細").trigger("click");await flushPromises();expect(wrapper.findAll('[data-testid="quotation-line"]')).toHaveLength(1);expect(window.document.activeElement).toBe(input("數量 1").element); });
 it("conversion submits the complete editable Draft SO and strips Quotation IDs", async () => { const save=vi.fn().mockResolvedValue({salesOrder:{id:9,number:"SO-202610-000009"},differenceSummary:{added:[],removed:[],quantityChanged:[],priceChanged:[]}});await mountForm({document,conversion:true,onSave:save});select("履約倉庫 *").vm.$emit("update:modelValue",6);await flushPromises();await input("數量 1").setValue("3.000000");await submit();expect(save).toHaveBeenCalledWith(expect.objectContaining({version:2,order:expect.objectContaining({fulfillmentWarehouseId:6,customerId:2,lines:[{skuId:3,skuUomId:5,quantity:"3.000000",unitSellingPrice:"3.3333",lineNote:""}]})}));expect(save.mock.calls[0][0].order).not.toHaveProperty("quotationDate"); });
 it("searches barcode through the exact route and selects its current sale UOM", async () => { await mountForm({onSave:vi.fn()});await input("條碼（精確搜尋）").setValue("8712345678901");await wrapper.findAll("button").find(b=>b.text()==="搜尋條碼").trigger("click");await flushPromises();expect(sales.lookupSkus).toHaveBeenCalledWith(expect.objectContaining({q:"",barcode:"8712345678901",pageSize:20}));await wrapper.findAll("button").find(b=>b.text()==="新增明細").trigger("click");expect(wrapper.findAll('[data-testid="quotation-line"]')).toHaveLength(1); });
 it("blocks invalid financial input and guards dirty navigation", async () => { const save=vi.fn();const {router}=await mountForm({document,onSave:save});await input("數量 1").setValue("0");await submit();expect(save).not.toHaveBeenCalled();const confirm=vi.spyOn(window,"confirm").mockReturnValue(false);await router.push("/other");expect(confirm).toHaveBeenCalled();expect(router.currentRoute.value.path).toBe("/edit"); });
});

async function mountEditPage(){const router=createRouter({history:createMemoryHistory(),routes:[{path:editPage.path,component:EditPage}]});await router.push("/sales/quotations/8/edit");await router.isReady();wrapper=mount({render:()=>h(RouterView)},{global:{plugins:[Quasar,router]},attachTo:window.document.body});await flushPromises();}
describe("TC-019 server-controlled editor page",()=>{
 it("keeps converted/read-only records out of the editor even through a direct URL",async()=>{sales.getQuotation.mockResolvedValue({...document,status:"CONVERTED",allowedActions:["print"]});await mountEditPage();expect(wrapper.find("form").exists()).toBe(false);expect(wrapper.text()).toContain("目前狀態或權限不允許此操作");});
 it("shows a load failure and retries the actual detail request",async()=>{sales.getQuotation.mockRejectedValueOnce(new Error("載入暫時失敗")).mockResolvedValue({...document,allowedActions:["edit"]});await mountEditPage();expect(wrapper.text()).toContain("載入暫時失敗");await wrapper.findAll("button").find(b=>b.text()==="重試").trigger("click");await flushPromises();expect(wrapper.find("form").exists()).toBe(true);expect(sales.getQuotation).toHaveBeenCalledTimes(2);});
 it("reloads the server version after saving instead of treating the client draft as truth",async()=>{sales.getQuotation.mockResolvedValueOnce({...document,allowedActions:["edit"]}).mockResolvedValue({...document,version:3,allowedActions:["edit"]});sales.updateQuotation.mockResolvedValue({quotation:{...document,version:3}});await mountEditPage();await submit();expect(sales.updateQuotation).toHaveBeenCalledWith(8,expect.objectContaining({version:2}));expect(wrapper.text()).toContain("最新版本 3");expect(sales.getQuotation).toHaveBeenCalledTimes(2);});
});

describe("TC-019 reused route and line-limit regression",()=>{
 it("does not discard a dirty editor on a reused route query change",async()=>{const {router}=await mountForm({document,onSave:vi.fn()});await input("備註").setValue("unsaved");vi.spyOn(window,"confirm").mockReturnValue(false);await router.push("/edit?convert=1");expect(router.currentRoute.value.query).toEqual({});expect(input("備註").element.value).toBe("unsaved");});
 it("still focuses a duplicate at the one-hundred-line limit",async()=>{const doc={...document,lines:[document.lines[0],...Array.from({length:99},(_,i)=>({...document.lines[0],id:20+i,skuId:30+i,skuUomId:50+i}))]};await mountForm({document:doc,onSave:vi.fn()});select("搜尋 SKU").vm.$emit("update:modelValue",sku);await flushPromises();const add=wrapper.findAll("button").find(b=>b.text()==="新增明細");expect(add.element.disabled).toBe(false);await add.trigger("click");await flushPromises();expect(wrapper.findAll('[data-testid="quotation-line"]')).toHaveLength(100);expect(window.document.activeElement).toBe(input("數量 1").element);});
});

describe("TC-019 persisted conversion difference pagination",()=>{
 it("pages all persisted differences locally without a zero server count",async()=>{const difference={added:[],removed:[],priceChanged:[],quantityChanged:Array.from({length:25},(_,i)=>({skuId:i+1,skuUomId:i+10,beforeQuantity:"1.000000",afterQuantity:"2.000000"}))};wrapper=mount(DifferencePanel,{props:{difference},global:{plugins:[Quasar]}});await flushPromises();expect(wrapper.text()).toContain("1–20 of 25");await wrapper.find('button[aria-label="Next page"]').trigger("click");await flushPromises();expect(wrapper.text()).toContain("21–25 of 25");expect(wrapper.findAll("tbody tr")).toHaveLength(5);});
});
