import { DOMWrapper, flushPromises, mount } from "@vue/test-utils";
import { createPinia, setActivePinia } from "pinia";
import { Quasar } from "quasar";
import { h } from "vue";
import { RouterView, createMemoryHistory, createRouter } from "vue-router";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
vi.mock("@/services/sales.js",()=>({default:{listQuotations:vi.fn(),getQuotation:vi.fn(),issueQuotation:vi.fn(),cancelQuotation:vi.fn()}}));
import sales from "@/services/sales.js";
import List, { page as listPage } from "@/pages/sales/SalesQuotationsPage.vue";
import Detail, { page as detailPage } from "@/pages/sales/SalesQuotationDetailPage.vue";
import { useSessionStore } from "@/stores/session.js";
const doc={id:8,number:"QT-202610-000008",status:"ISSUED",version:2,customerId:2,customerCode:"C2",customerName:"合成客戶",currencyCode:"HKD",quotationDate:"2026-10-06",validUntil:"2026-10-30",paymentTermName:"30天",externalReference:"PO",notes:"合成備註",totalAmount:"6.6666",lineCount:1,lines:[{id:11,lineNo:1,skuId:3,skuUomId:5,skuCode:"SKU3",skuName:"合成貨品",uomCode:"EA",quantity:"2.000000",unitSellingPrice:"3.3333",lineAmount:"6.6666",lineNote:""}],allowedActions:["print","convert","cancel"],conversion:null};
let wrapper;
async function open(path,permissions=["sales.view"]){const router=createRouter({history:createMemoryHistory(),routes:[{...listPage,component:List},{...detailPage,component:Detail}]});await router.push(path);await router.isReady();useSessionStore().user={id:1,permissions,roles:[]};wrapper=mount({render:()=>h(RouterView)},{global:{plugins:[Quasar,router]},attachTo:document.body});await flushPromises();return router;}
beforeEach(()=>{setActivePinia(createPinia());vi.clearAllMocks();sales.listQuotations.mockResolvedValue({rows:[doc],rowsNumber:1});sales.getQuotation.mockResolvedValue(doc);});
afterEach(()=>{wrapper?.unmount();wrapper=null;vi.restoreAllMocks();document.body.innerHTML="";});
describe("TC-019 Quotation inquiry",()=>{
 it("keeps read routes view-only and lists safe server totals with pagination",async()=>{expect(listPage.requires.permissions).toEqual(["sales.view"]);expect(detailPage.requires.permissions).toEqual(["sales.view"]);await open("/sales/quotations");expect(wrapper.text()).toContain("QT-202610-000008");expect(wrapper.text()).toContain("6.6666");expect(sales.listQuotations).toHaveBeenCalledWith(expect.objectContaining({page:1,rowsPerPage:20}));expect(wrapper.text()).not.toContain("新增報價");});
 it("persists explicit query filters and refreshes server pagination",async()=>{const router=await open("/sales/quotations");await wrapper.find('input[aria-label="報價編號／客戶"]').setValue("C2");await wrapper.findAll("button").find(b=>b.text()==="搜尋").trigger("click");await flushPromises();expect(router.currentRoute.value.query.q).toBe("C2");expect(sales.listQuotations).toHaveBeenLastCalledWith(expect.objectContaining({filter:"C2",page:1}));});
 it("uses server actions rather than inferring actions from Issued status",async()=>{sales.getQuotation.mockResolvedValue({...doc,allowedActions:["print"]});await open("/sales/quotations/8",["sales.view","sales.mgmt"]);expect(wrapper.text()).toContain("列印");expect(wrapper.text()).not.toContain("轉為銷售訂單");expect(wrapper.text()).not.toContain("取消報價");});
 it("shows the unique target and persisted differences for Converted",async()=>{sales.getQuotation.mockResolvedValue({...doc,status:"CONVERTED",allowedActions:["print"],conversion:{salesOrderId:9,salesOrderNumber:"SO-202610-000009",differenceSummary:{added:[],removed:[],quantityChanged:[],priceChanged:[]}}});await open("/sales/quotations/8");expect(wrapper.find('a[href="/sales/orders/9"]').text()).toContain("SO-202610-000009");expect(wrapper.text()).toContain("明細沒有差異");});
 it("issues once per intent and reloads actual allowedActions",async()=>{sales.getQuotation.mockResolvedValueOnce({...doc,status:"DRAFT",allowedActions:["issue"]}).mockResolvedValue(doc);sales.issueQuotation.mockResolvedValue({quotation:doc});await open("/sales/quotations/8",["sales.view","sales.mgmt"]);await wrapper.findAll("button").find(b=>b.text()==="發出報價").trigger("click");await flushPromises();await new DOMWrapper(document.body).findAll("button").find(b=>b.text()==="確認發出").trigger("click");await flushPromises();expect(sales.issueQuotation).toHaveBeenCalledWith(8,expect.objectContaining({version:2,eventId:expect.any(String)}));expect(sales.getQuotation).toHaveBeenCalledTimes(2);expect(wrapper.text()).not.toContain("發出報價");});
 it("rejects a short cancellation reason without a request",async()=>{await open("/sales/quotations/8",["sales.view","sales.mgmt"]);await wrapper.findAll("button").find(b=>b.text()==="取消報價").trigger("click");await flushPromises();const body=document.body;const reason=body.querySelector('textarea[aria-label="取消原因 *"]');reason.value="no";reason.dispatchEvent(new Event("input",{bubbles:true}));body.querySelector('form').dispatchEvent(new Event("submit",{bubbles:true,cancelable:true}));await flushPromises();expect(sales.cancelQuotation).not.toHaveBeenCalled();expect(body.textContent).toContain("最少五個字元");});
 it("retains load errors and provides retry without stale document data",async()=>{sales.getQuotation.mockRejectedValueOnce(new Error("載入失敗")).mockResolvedValue(doc);await open("/sales/quotations/8");expect(wrapper.text()).toContain("載入失敗");await wrapper.findAll("button").find(b=>b.text()==="重試").trigger("click");await flushPromises();expect(wrapper.text()).toContain(doc.number);});
 it("freezes an uncertain cancellation and keeps its event across route guard and retry",async()=>{sales.cancelQuotation.mockRejectedValueOnce({code:"NETWORK_ERROR"}).mockResolvedValue({quotation:doc});const router=await open("/sales/quotations/8",["sales.view","sales.mgmt"]);await wrapper.findAll("button").find(b=>b.text()==="取消報價").trigger("click");await flushPromises();const body=new DOMWrapper(document.body);await body.find('textarea').setValue("合成取消原因");await body.find('form').trigger("submit");await flushPromises();expect(body.text()).toContain("結果尚未確認");expect(body.find('textarea').attributes("disabled")).toBeDefined();const first=sales.cancelQuotation.mock.calls[0];const confirm=vi.spyOn(window,"confirm").mockReturnValue(false);await router.push("/sales/quotations/9");await flushPromises();expect(router.currentRoute.value.params.id).toBe("8");expect(confirm).toHaveBeenCalled();await body.find('form').trigger("submit");await flushPromises();expect(sales.cancelQuotation.mock.calls[1]).toEqual(first);expect(sales.getQuotation).toHaveBeenCalledTimes(2);});
 it("offers explicit reload after a stale cancellation and closes the old intent",async()=>{sales.cancelQuotation.mockRejectedValue({code:"VERSION_CONFLICT"});await open("/sales/quotations/8",["sales.view","sales.mgmt"]);await wrapper.findAll("button").find(b=>b.text()==="取消報價").trigger("click");await flushPromises();const body=new DOMWrapper(document.body);await body.find('textarea').setValue("合成取消原因");await body.find('form').trigger("submit");await flushPromises();expect(body.text()).toContain("版本已更改");await body.findAll('button').find(b=>b.text()==="重新讀取報價").trigger("click");await flushPromises();expect(sales.getQuotation).toHaveBeenCalledTimes(2);});

});
