import {flushPromises,mount} from "@vue/test-utils";
import {createPinia,setActivePinia} from "pinia";
import {Quasar} from "quasar";
import {h} from "vue";
import {RouterView,createMemoryHistory,createRouter} from "vue-router";
import {afterEach,beforeEach,expect,it,vi} from "vitest";
vi.mock("@/services/sales.js",()=>({default:{getOrder:vi.fn(),confirmOrder:vi.fn(),getOperation:vi.fn(),lookupCustomers:vi.fn(),withdrawOrder:vi.fn(),cancelOrder:vi.fn(),closeRemainingOrder:vi.fn(),runBackorderAllocation:vi.fn()}}));
import sales from "@/services/sales.js";
import Detail,{page} from "@/pages/sales/SalesOrderDetailPage.vue";
import {useSessionStore} from "@/stores/session.js";
const draft={id:8,number:"SO-8",status:"DRAFT",sourceType:"MANUAL",version:3,customerId:2,customerCode:"C2",customerName:"客戶",fulfillmentWarehouseId:6,warehouseCode:"W6",warehouseName:"倉庫",currencyCode:"HKD",orderDate:"2026-10-07",totalAmount:"0.0000",lineCount:1,hasBackorder:false,lines:[{id:11,lineNo:1,skuId:3,skuCode:"S3",skuName:"貨品",uomCode:"EA",quantity:"2.000000",unitSellingPrice:"0.0000",orderedBaseQuantity:"2",reservedBaseQuantity:"0",backorderedBaseQuantity:"0",fulfilledBaseQuantity:"0",cancelledBaseQuantity:"0",lineAmount:"0.0000"}],allowedActions:["edit","confirm"],history:[],currentMaster:{customer:{customerCode:"C2",customerName:"目前客戶",status:"active"},skus:[]}};
const order={...draft,status:"CONFIRMED",allowedActions:["withdraw","cancel"],lines:[{...draft.lines[0],reservedBaseQuantity:"1",backorderedBaseQuantity:"1"}]};
let wrapper;
async function open(permissions=["sales.view","sales.mgmt"]){const router=createRouter({history:createMemoryHistory(),routes:[{...page,component:Detail}]});await router.push("/sales/orders/8");await router.isReady();useSessionStore().user={id:7,roles:[],permissions};wrapper=mount({render:()=>h(RouterView)},{global:{plugins:[Quasar,router]},attachTo:document.body});await flushPromises();return router;}
async function click(label){const button=[...document.querySelectorAll("button")].find(el=>el.textContent===label);expect(button).toBeTruthy();button.click();await flushPromises();}
beforeEach(()=>{setActivePinia(createPinia());vi.clearAllMocks();sessionStorage.clear();sales.getOrder.mockResolvedValue(order);sales.lookupCustomers.mockResolvedValue({items:[{customerId:2,credit:{configured:true,status:"normal",creditLimit:"1000.0000",currencyCode:"HKD"}}]});sales.confirmOrder.mockResolvedValue({outcome:"CONFIRMED",warnings:[],salesOrder:{...order,status:"CONFIRMED"}});sales.getOperation.mockResolvedValue({status:"IN_PROGRESS"});sales.withdrawOrder.mockImplementation(async()=>{sales.getOrder.mockResolvedValue({...draft,version:4,allowedActions:["edit","confirm","cancel"]});return {operation:{id:8,version:4,status:"DRAFT"}};});sales.cancelOrder.mockResolvedValue({operation:{id:8,version:4,status:"CANCELLED"}});});
afterEach(()=>{wrapper?.unmount();wrapper=null;vi.restoreAllMocks();document.body.innerHTML="";});

it("TC-029 lifecycle dialog validates Unicode reason and success reloads all server facts",async()=>{
 await open();await click("撤回確認");const input=document.querySelector('textarea');expect(input).toBeTruthy();const submit=()=>[...document.querySelectorAll("button")].find(b=>b.textContent==="提交訂單操作");expect(submit().disabled).toBe(true);input.value="abcd";input.dispatchEvent(new Event("input",{bubbles:true}));await flushPromises();expect(submit().disabled).toBe(true);input.value="客戶要求重新確認";input.dispatchEvent(new Event("input",{bubbles:true}));await flushPromises();await click("提交訂單操作");expect(sales.withdrawOrder).toHaveBeenCalledTimes(1);expect(sales.withdrawOrder).toHaveBeenCalledWith(8,expect.objectContaining({reason:"客戶要求重新確認",version:3}),expect.objectContaining({signal:expect.any(AbortSignal)}));expect(wrapper.text()).toContain("訂單操作已完成");expect(wrapper.text()).toContain("Reserved 0");expect(wrapper.text()).toContain("確認訂單");expect(sessionStorage.length).toBe(0);
});
it("TC-030 server actions plus live session permission control all lifecycle buttons",async()=>{
 await open(["sales.view"]);expect(wrapper.text()).not.toContain("撤回確認");expect(wrapper.text()).not.toContain("取消訂單");wrapper.unmount();sales.getOrder.mockResolvedValue({...order,status:"PARTIALLY_FULFILLED",allowedActions:["closeRemaining"]});await open();expect(wrapper.text()).toContain("關閉剩餘數量");expect(wrapper.text()).not.toContain("撤回確認");expect(wrapper.text()).not.toContain("取消訂單");
});
it("TC-029 network uncertainty preserves exact original event/version/reason across refresh then retries only after404",async()=>{
 sales.withdrawOrder.mockRejectedValueOnce(new Error("offline"));await open();await click("撤回確認");const input=document.querySelector('textarea');input.value="客戶要求重新確認";input.dispatchEvent(new Event("input",{bubbles:true}));await flushPromises();await click("提交訂單操作");const saved=JSON.parse(sessionStorage.getItem("sales.lifecycle:7:8"));expect(saved.action).toBe("withdraw");expect(wrapper.text()).not.toContain("取消訂單");wrapper.unmount();sales.getOperation.mockRejectedValue({status:404});await open();await click("重查並重試原訂單操作");expect(sales.withdrawOrder.mock.calls[1][1]).toEqual({eventId:saved.eventId,version:3,reason:saved.reason});expect(sessionStorage.length).toBe(0);
});
it("TC-028 release409 shows safe error and original operation without optimistic status",async()=>{
 sales.withdrawOrder.mockRejectedValue({status:409,code:"RESERVATION_RELEASE_FAILED",message:"保留未能釋放"});sales.getOperation.mockRejectedValue({status:404});await open();await click("撤回確認");const input=document.querySelector('textarea');input.value="客戶要求重新確認";input.dispatchEvent(new Event("input",{bubbles:true}));await flushPromises();await click("提交訂單操作");expect(wrapper.text()).toContain("保留未能釋放");expect(wrapper.text()).toContain("Reserved 1");expect(wrapper.text()).not.toContain("訂單操作已完成");expect(sessionStorage.getItem("sales.lifecycle:7:8")).not.toBeNull();
});
it("TC-030 stale version reloads actual latest state before permitting another action",async()=>{
 sales.cancelOrder.mockRejectedValue({status:409,code:"VERSION_CONFLICT"});await open();await click("取消訂單");const input=document.querySelector('textarea');input.value="客戶要求取消訂單";input.dispatchEvent(new Event("input",{bubbles:true}));await flushPromises();await click("提交訂單操作");expect(wrapper.text()).toContain("操作未完成：VERSION_CONFLICT");expect(sessionStorage.length).toBe(0);expect(wrapper.text()).toContain("撤回確認");
});
it("TC-027 accepted wake reloads server facts without optimistic quantity changes and Viewer cannot wake",async()=>{
 sales.getOrder.mockResolvedValue({...order,hasBackorder:true,backorderLineCount:1});sales.runBackorderAllocation.mockResolvedValue({accepted:true});await open();await click("喚醒 Backorder 補配");await click("提交 FIFO 喚醒");expect(sales.runBackorderAllocation).toHaveBeenCalledTimes(1);expect(wrapper.text()).toContain("不保證即時配到");expect(wrapper.text()).toContain("Reserved 1");expect(wrapper.text()).toContain("Backorder 1");expect(sales.getOrder).toHaveBeenCalledTimes(2);sales.getOrder.mockResolvedValue({...order,version:4,hasBackorder:false,lines:[{...order.lines[0],reservedBaseQuantity:"2",backorderedBaseQuantity:"0"}]});await click("重新讀取訂單");expect(wrapper.text()).toContain("Reserved 2");expect(wrapper.text()).not.toContain("喚醒 Backorder 補配");wrapper.unmount();sales.getOrder.mockResolvedValue({...order,hasBackorder:true,backorderLineCount:1});await open(["sales.view"]);expect(wrapper.text()).not.toContain("喚醒 Backorder 補配");expect(wrapper.text()).toContain("FIFO");
});
