import { flushPromises, mount } from "@vue/test-utils";
import { createPinia, setActivePinia } from "pinia";
import { Quasar } from "quasar";
import { h } from "vue";
import { RouterView, createMemoryHistory, createRouter } from "vue-router";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
vi.mock("@/services/sales.js",()=>({default:{listOrders:vi.fn(),getOrder:vi.fn()}}));
import sales from "@/services/sales.js";
import List, {page as listPage} from "@/pages/sales/SalesOrdersPage.vue";
import Detail, {page as detailPage} from "@/pages/sales/SalesOrderDetailPage.vue";
import {useSessionStore} from "@/stores/session.js";
import menu from "@config/menu.js";
const order={id:8,number:"SO-202610-000008",status:"DRAFT",sourceType:"QUOTATION",sourceQuotationId:19,channelCode:"",externalOrderId:"",version:2,customerId:2,customerCode:"C2",customerName:"歷史客戶",fulfillmentWarehouseId:6,warehouseCode:"W6",warehouseName:"倉庫",currencyCode:"HKD",orderDate:"2026-10-06",requestedDeliveryDate:null,paymentTermName:"30 天",customerPoReference:"PO",notes:"<script>unsafe()</script>",totalAmount:"6.6666",createdAt:Date.now(),updatedAt:Date.now(),lineCount:1,hasBackorder:false,backorderLineCount:0,isArchived:false,lines:[{id:11,lineNo:1,skuId:3,skuUomId:5,skuCode:"SKU3",skuName:"歷史貨品",itemName:"品項",uomCode:"EA",quantity:"2.000000",orderedBaseQuantity:"2",reservedBaseQuantity:"0",backorderedBaseQuantity:"0",fulfilledBaseQuantity:"0",cancelledBaseQuantity:"0",unitSellingPrice:"3.3333",lineAmount:"6.6666",lineNote:""}],allowedActions:["edit"],history:[{id:4,sequence:1,fromStatus:null,toStatus:"DRAFT",action:"created",reason:"",actorLabel:"合成用戶",occurredAt:Date.now(),version:1}],historyTruncated:false,currentMaster:{customer:{customerCode:"C2",customerName:"目前客戶",status:"blocked"},skus:[{skuId:3,skuCode:"SKU3",skuName:"目前貨品",itemName:"品項",skuStatus:"inactive",itemStatus:"active"}]}};
let wrapper;
async function open(path,permissions=["sales.view"]){const router=createRouter({history:createMemoryHistory(),routes:[{...listPage,component:List},{...detailPage,component:Detail}]});await router.push(path);await router.isReady();useSessionStore().user={id:1,permissions,roles:[]};wrapper=mount({render:()=>h(RouterView)},{global:{plugins:[Quasar,router]},attachTo:document.body});await flushPromises();return router;}
beforeEach(()=>{setActivePinia(createPinia());vi.clearAllMocks();sales.listOrders.mockResolvedValue({rows:[order],rowsNumber:1});sales.getOrder.mockResolvedValue(order);});
afterEach(()=>{wrapper?.unmount();wrapper=null;vi.restoreAllMocks();document.body.innerHTML="";});
describe("TC-019 Active SO inquiry",()=>{
 it("keeps menus and direct read routes view-only, hides management actions from Viewer",async()=>{expect(listPage.requires.permissions).toEqual(["sales.view"]);expect(detailPage.requires.permissions).toEqual(["sales.view"]);expect(menu.groups.some(group=>group.name===listPage.menu.group)).toBe(true);await open("/sales/orders");expect(wrapper.text()).toContain(order.number);expect(wrapper.text()).toContain("6.6666");expect(wrapper.text()).not.toContain("新增銷售訂單");expect(sales.listOrders).toHaveBeenCalledWith(expect.objectContaining({page:1,rowsPerPage:20,sortBy:"orderDate",descending:true}));});
 it("persists exact number, external source and status filters in the URL",async()=>{const router=await open("/sales/orders?number=SO-202610-000008&channelCode=WEB&externalOrderId=case%25&status=DRAFT&hasBackorder=false");expect(sales.listOrders).toHaveBeenCalledWith(expect.objectContaining({number:order.number,channelCode:"WEB",externalOrderId:"case%",status:"DRAFT",hasBackorder:"false"}));await wrapper.find('input[aria-label="訂單編號（精確）"]').setValue("SO-202610-000009");await wrapper.findAll("button").find(b=>b.text()==="搜尋").trigger("click");await flushPromises();expect(router.currentRoute.value.query.number).toBe("SO-202610-000009");});
 it("retains unsent filter input when loading synchronizes only pagination",async()=>{let resolve;sales.listOrders.mockImplementationOnce(()=>new Promise(done=>{resolve=done;}));const router=await open("/sales/orders");const input=wrapper.find('input[aria-label="訂單編號（精確）"]');await input.setValue("SO-190001-999999");resolve({rows:[order],rowsNumber:1});await flushPromises();expect(router.currentRoute.value.query.page).toBe("1");expect(input.element.value).toBe("SO-190001-999999");await wrapper.findAll("button").find(b=>b.text()==="搜尋").trigger("click");await flushPromises();expect(router.currentRoute.value.query.number).toBe("SO-190001-999999");});
 it("accepts off-page positive IDs and refuses unsafe ID input",async()=>{const router=await open("/sales/orders");const customer=wrapper.find('input[aria-label="客戶 ID"]'),warehouse=wrapper.find('input[aria-label="倉庫 ID"]');for(const value of ["0","-1","1.5","9007199254740992"]){await customer.setValue(value);await customer.trigger("keydown",{key:"Enter",keyCode:13});await flushPromises();await wrapper.findAll("button").find(b=>b.text()==="搜尋").trigger("click");await flushPromises();expect(router.currentRoute.value.query.customerId).toBeUndefined();}await customer.setValue("123");await customer.trigger("keydown",{key:"Enter",keyCode:13});await warehouse.setValue("456");await warehouse.trigger("keydown",{key:"Enter",keyCode:13});await flushPromises();await wrapper.findAll("button").find(b=>b.text()==="搜尋").trigger("click");await flushPromises();expect(router.currentRoute.value.query.customerId).toBe("123");expect(router.currentRoute.value.query.warehouseId).toBe("456");expect(sales.listOrders).toHaveBeenLastCalledWith(expect.objectContaining({customerId:"123",warehouseId:"456"}));});
 it("ignores an old filter response when a new search has already completed",async()=>{let resolve;sales.listOrders.mockImplementationOnce(()=>new Promise(done=>{resolve=done;}));const router=await open("/sales/orders?page=2");sales.listOrders.mockResolvedValue({rows:[],rowsNumber:0});await router.push({query:{number:"SO-190001-999999"}});await flushPromises();expect(router.currentRoute.value.query.page).toBe("1");resolve({rows:[order],rowsNumber:1});await flushPromises();expect(router.currentRoute.value.query.page).toBe("1");expect(router.currentRoute.value.query.number).toBe("SO-190001-999999");expect(wrapper.text()).toContain("沒有符合條件的 Active 銷售訂單");});
 it("uses server actions and shows snapshots, current references and the source link safely",async()=>{sales.getOrder.mockResolvedValue({...order,allowedActions:[]});await open("/sales/orders/8",["sales.view","sales.mgmt"]);expect(wrapper.text()).not.toContain("編輯 Draft");expect(wrapper.text()).toContain("Active");expect(wrapper.text()).toContain("歷史客戶");expect(wrapper.text()).toContain("目前客戶");expect(wrapper.text()).toContain("歷史貨品");expect(wrapper.text()).toContain("目前貨品");expect(wrapper.find('a[href="/sales/quotations/19"]').exists()).toBe(true);expect(wrapper.find("script").exists()).toBe(false);expect(wrapper.text()).toContain(order.notes);expect(wrapper.text()).toContain("合成用戶");});
 it("shows backorder and all exact base quantities without claiming Inventory effects",async()=>{sales.getOrder.mockResolvedValue({...order,hasBackorder:true,backorderLineCount:1,lines:[{...order.lines[0],orderedBaseQuantity:"9007199254740992",backorderedBaseQuantity:"9007199254740992"}]});await open("/sales/orders/8");expect(wrapper.text()).toContain("有 Backorder");expect(wrapper.text()).toContain("9007199254740992");expect(wrapper.text()).not.toContain("確認訂單");});
 it("pages all detail lines and explicitly warns on truncated history",async()=>{sales.getOrder.mockResolvedValue({...order,historyTruncated:true,lineCount:25,lines:Array.from({length:25},(_,i)=>({...order.lines[0],id:i+1,lineNo:i+1}))});await open("/sales/orders/8");expect(wrapper.text()).toContain("1–20 of 25");await wrapper.find('button[aria-label="Next page"]').trigger("click");await flushPromises();expect(wrapper.text()).toContain("21–25 of 25");expect(wrapper.text()).toContain("最近 100 項");});
 it("retries detail errors and shows an empty Active list without automatic Archive search",async()=>{sales.getOrder.mockRejectedValueOnce(new Error("載入失敗")).mockResolvedValue(order);await open("/sales/orders/8");expect(wrapper.text()).toContain("載入失敗");await wrapper.findAll("button").find(b=>b.text()==="重試").trigger("click");await flushPromises();expect(wrapper.text()).toContain(order.number);wrapper.unmount();sales.listOrders.mockResolvedValue({rows:[],rowsNumber:0});await open("/sales/orders?q=missing");expect(wrapper.text()).toContain("沒有符合條件的 Active 銷售訂單");expect(sales.getOrder).toHaveBeenCalledTimes(2);});
});
