import assert from "node:assert/strict";
import test from "node:test";
import { createHash } from "node:crypto";
import { validateSalesOrderQuery, salesOrderWhere } from "../../../src/modules/sales/SalesInquiryService.js";
import { salesOrderListRequest, SALES_ORDER_LIST_RESPONSE, SALES_ORDER_READ_RESPONSE } from "../../../src/handlers/sales/salesSchemas.js";
import { ListSalesOrdersHandler } from "../../../src/handlers/sales-orders/listSalesOrdersHandler.js";
import { GetSalesOrderHandler } from "../../../src/handlers/sales-orders/getSalesOrderHandler.js";
test("TC-019/TC-018 SO queries reject unknown filters, unsafe offsets, sort fragments and invalid dates",()=>{
 for(const input of [{extra:"x"},{sortBy:"constructor"},{sortBy:"number DESC;"},{page:Number.MAX_SAFE_INTEGER,pageSize:100},{page:1.5},{status:[]},{sourceType:"OTHER"},{customerId:0},{warehouseId:0},{hasBackorder:"false"},{descending:"false"},{q:"x".repeat(191)},{orderDateFrom:"2026-10-10",orderDateTo:"2026-10-01"},{updatedFrom:2,updatedTo:1},{updatedTo:-1}])assert.throws(()=>validateSalesOrderQuery(input),{code:"SALES_INPUT_INVALID"});
 assert.throws(()=>validateSalesOrderQuery({orderDateFrom:"2026-02-30"}),{code:"SALES_DATE_INVALID"});
});
test("TC-019/TC-018 SO HTTP query coercion is isolated and preserves repeated enums",()=>{const query={page:"2",pageSize:"10",warehouseId:"4",hasBackorder:"false",descending:"false",status:["DRAFT","CONFIRMED"],sourceType:"MANUAL",updatedFrom:"1"},req={auth:{claims:{sub:"1",roles:["viewer"],permissions:["sales.view"]}},input:{query}};const result=salesOrderListRequest(req);assert.equal(result.input.page,2);assert.equal(result.input.warehouseId,4);assert.equal(result.input.hasBackorder,false);assert.equal(query.page,"2");assert.deepEqual(validateSalesOrderQuery(result.input).sourceType,["MANUAL"]);for(const invalid of [{pageSize:"101"},{hasBackorder:"maybe"},{extra:"x"}])assert.throws(()=>salesOrderListRequest({...req,input:{query:invalid}}),{code:"SALES_INPUT_INVALID"});});
test("TC-019/TC-018 external IDs use exact hash keys and Active routing without wildcard search",()=>{const input=validateSalesOrderQuery({externalOrderId:"_order%雪",channelCode:"WEB"}),{where,values}=salesOrderWhere(input);assert.match(where,/external_order_id_hash=\?/);assert.match(where,/is_order_archived=0/);assert.match(where,/channel_code=\?/);assert.doesNotMatch(where,/LIKE|archive_/);assert.ok(values.some(value=>Buffer.isBuffer(value)&&value.equals(createHash("sha256").update(input.externalOrderId).digest())));assert.ok(values.includes("_order%雪"));assert.ok(values.includes("WEB"));});
test("TC-019/TC-018 exact number and escaped Customer search remain parameterized",()=>{const {where,values}=salesOrderWhere(validateSalesOrderQuery({number:"SO-202610-000001",q:"C_%!",status:["DRAFT"],warehouseId:8,hasBackorder:true}));assert.match(where,/sales_order_number=\?/);assert.match(where,/customer_name_snapshot LIKE \? ESCAPE '!'/);assert.doesNotMatch(where,/C_%!|JOIN sales_order_lines/);assert.ok(values.includes("C!_!%!!%"));assert.ok(values.includes("%C!_!%!!%"));assert.ok(values.includes("SO-202610-000001"));});
test("TC-019/TC-018 SO read handlers require view and expose bounded exact safe contracts",()=>{for(const Handler of [ListSalesOrdersHandler,GetSalesOrderHandler]){assert.equal(Handler.api.method,"GET");assert.deepEqual(Handler.api.authorizationPolicies[0].options.permissions,["sales.view"]);assert.ok(Handler.api.path.startsWith("/api/v1/sales-orders"));}assert.equal(SALES_ORDER_LIST_RESPONSE.properties.items.maxItems,100);assert.equal(SALES_ORDER_LIST_RESPONSE.properties.items.items.additionalProperties,false);assert.equal(SALES_ORDER_READ_RESPONSE.additionalProperties,false);assert.equal(SALES_ORDER_READ_RESPONSE.properties.history.maxItems,100);assert.equal(SALES_ORDER_READ_RESPONSE.properties.lines.maxItems,100);assert.deepEqual(SALES_ORDER_READ_RESPONSE.properties.allowedActions.items.enum,["edit"]);assert.doesNotMatch(JSON.stringify(SALES_ORDER_READ_RESPONSE),/bank|address|password|payload_hash/);});
