import path from "node:path";
import {lstat,unlink} from "node:fs/promises";
import {BaseService} from "../../../framework/services/BaseService.js";
const name="sales.fileRetention",day=86400000,terminal="('COMPLETED','PARTIAL_SUCCESS','FAILED','CANCELLED')";
const privateEntry=(stat,directory)=>!stat.isSymbolicLink()&&(directory?stat.isDirectory():stat.isFile())&&(stat.mode&0o777)===(directory?0o700:0o600)&&(!process.getuid||stat.uid===process.getuid());
export class SalesFileRetentionJob extends BaseService {
 static service=Object.freeze({name:"job.salesFileRetention",lifecycle:"singleton",dependencies:["scheduler","mysqldatabase","time","logging"],eager:true});
 static jobs=Object.freeze([{name,method:"run",scope:"cluster",intervalMs:day,timeoutMs:30000}]);
 constructor({config,services,options={}}={}){super({config,services,options});this.scheduler=services.require("scheduler");this.database=services.require("mysqldatabase");this.logger=services.require("logging").logger;this.root=path.resolve(options.root??"storage/sales-imports");this.fileDays=config?.sales?.importFileRetentionDays??90;this.payloadDays=config?.sales?.intakePayloadRetentionDays??90;}
 async initialize(){this.scheduler.register(this);}
 #active(signal){const scheduler=this.scheduler,job=scheduler.jobs?.get(name);if(!scheduler.started||scheduler.stopped||scheduler.schedulerConfig?.enabled!==true||job?.serviceName!=="job.salesFileRetention"||job.method!=="run"||job.scope!=="cluster"||job.enabled!==true||scheduler.running?.get(name)?.controller.signal!==signal||signal?.aborted!==false)throw Error("Sales retention worker unavailable");return scheduler.owner;}
 async #lease(tx,signal,owner){if(this.#active(signal)!==owner)throw Error("Sales retention worker unavailable");const [[lease]]=await tx.query("SELECT owner,expires_at FROM fr_job_leases WHERE job_name='sales.fileRetention' FOR UPDATE"),[[clock]]=await tx.query("SELECT UNIX_TIMESTAMP() AS now,CAST(UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000 AS UNSIGNED) AS now_ms");if(this.#active(signal)!==owner||lease?.owner!==owner||![Number(lease?.expires_at),Number(clock?.now),Number(clock?.now_ms)].every(Number.isSafeInteger)||Number(lease.expires_at)<=Number(clock.now))throw Error("Sales retention lease unavailable");return Number(clock.now_ms);}
 async #transaction(signal,work){const owner=this.#active(signal);return this.database.withTransaction(async tx=>{const now=await this.#lease(tx,signal,owner),result=await work(tx,now);await this.#lease(tx,signal,owner);return result;},{signal});}
 async #remove(batch,file){if(!/^SI-\d{6}-\d{6}$/u.test(batch)||file!==`${batch}/source.csv`&&file!==`${batch}/result.csv`)throw Error("Sales retention path invalid");
  try{if(!privateEntry(await lstat(this.root),true))throw Error("Sales retention directory invalid");const directory=path.join(this.root,batch);if(!privateEntry(await lstat(directory),true))throw Error("Sales retention directory invalid");const target=path.join(this.root,file);if(!privateEntry(await lstat(target),false))throw Error("Sales retention file invalid");await unlink(target);}catch(error){if(error.code!=="ENOENT")throw error;}
 }
 async run(signal){
  const counts={filesPurged:0,payloadsPurged:0,failed:0};
  // ponytail: each daily run clears at most50 batches/500 payloads; increase only if measured expiry backlog needs it.
  const jobs=await this.#transaction(signal,async(tx,now)=>(await tx.query(`SELECT id FROM sales_import_jobs WHERE status IN ${terminal} AND completed_at<=? AND files_purged_at IS NULL ORDER BY id LIMIT 50`,[now-this.fileDays*day]))[0]);
  for(const candidate of jobs){signal.throwIfAborted();try{const purged=await this.#transaction(signal,async(tx,now)=>{const [[job]]=await tx.query(`SELECT id,batch_number,source_file_path,result_file_path,status,completed_at FROM sales_import_jobs WHERE id=? AND status IN ${terminal} AND completed_at<=? AND files_purged_at IS NULL FOR UPDATE`,[candidate.id,now-this.fileDays*day]);if(!job)return;for(const file of [job.source_file_path,job.result_file_path]){signal.throwIfAborted();if(file)await this.#remove(job.batch_number,file);}signal.throwIfAborted();await tx.execute("UPDATE sales_import_jobs SET source_file_path='',result_file_path='',files_purged_at=?,version=version+1,updated_at=? WHERE id=?",[now,now,job.id]);return true;});if(purged)counts.filesPurged++;}catch{signal.throwIfAborted();counts.failed++;}}
  counts.payloadsPurged=await this.#transaction(signal,async(tx,now)=>{const [rows]=await tx.query(`SELECT i.id FROM sales_intake_orders i LEFT JOIN sales_import_jobs j ON j.id=i.import_job_id WHERE i.safe_payload IS NOT NULL AND i.payload_purged_at IS NULL AND ((i.status IN ('INVALID','DUPLICATE','SUCCEEDED','FAILED') AND i.completed_at<=?) OR (j.status IN ${terminal} AND j.completed_at<=?)) ORDER BY i.id LIMIT 500 FOR UPDATE`,[now-this.payloadDays*day,now-this.payloadDays*day]);for(const row of rows){signal.throwIfAborted();await tx.execute("UPDATE sales_intake_orders SET safe_payload=NULL,payload_purged_at=? WHERE id=?",[now,row.id]);}return rows.length;});
  await this.logger.info("sales.file_retention_completed","Sales file retention batch completed",counts);signal.throwIfAborted();if(counts.failed)throw Error("Sales file retention incomplete");return counts;
 }
}
