import assert from "node:assert/strict";
import test from "node:test";
import process from "node:process";
import path from "node:path";
import {Buffer} from "node:buffer";
import {randomUUID,createHash} from "node:crypto";
import {Readable} from "node:stream";
import {spawn} from "node:child_process";
import {once} from "node:events";
import {createServer,request as httpRequest} from "node:http";
import {mkdtemp,rm} from "node:fs/promises";
import {cpus,totalmem,tmpdir} from "node:os";
import {performance} from "node:perf_hooks";
import {setTimeout as delay} from "node:timers/promises";
import {stringify} from "csv-stringify";
import {setup,stock} from "../sales/phase2/fixtures.js";
import {reconcileCommitments} from "../sales/phase2/commitmentReconciliation.js";
import {createApplication} from "../../src/framework/application/createApplication.js";
import {defaultConfigurationSource} from "../../src/framework/configuration/applicationConfiguration.js";
import {SALES_CSV_COLUMNS} from "../../src/modules/sales/salesCsv.js";
import {SalesOrderService} from "../../src/modules/sales/SalesOrderService.js";
import {SalesOrderConfirmationService} from "../../src/modules/sales/SalesOrderConfirmationService.js";
const it=process.env.DB_INTEGRATION_TESTS==='1'?test:test.skip;
it('TC-042 actual10000-order50000-line streaming HTTP CSV with50 foreground users and fixed scheduled workers', {timeout:1800000},async t=>{
 const f=await setup(t);await stock(f,0);const source=defaultConfigurationSource(),app=await createApplication({configurationSource:{...source,application:{...source.application,port:0},sales:{...source.sales,importChannelCodes:['SYNTHETIC']},security:{...source.security,reverseProxy:{...source.security.reverseProxy,trustProxy:'loopback'}},scheduler:{...source.scheduler,jobs:{...source.scheduler.jobs,'sales.importWorker':{enabled:true},'sales.confirmationRecovery':{enabled:true},'sales.backorderAllocate':{enabled:true}}}}});t.after(()=>app.shutdown('sales_import_capacity_complete'));
 const database=app.services.require('mysqldatabase'),time=app.services.require('time'),logger=app.services.require('logging').logger,orders=new SalesOrderService({database,time,logger}),confirmation=new SalesOrderConfirmationService({database,time,logger}),skus=[],actors=[],runId=randomUUID();
 const [[uom]]=await f.db.query('SELECT uom_id FROM item_sku_uoms WHERE id=?',[f.skuUomId]);
 for(let index=0;index<100;index++){const code='p3cap-'+runId+'-'+index,skuId=index===0?f.skuId:await f.insert('item_skus',{item_id:f.itemId,sku_code:code,sku_name:code,status:'active',sellable:1,inventory_tracked:1,created_at:f.now,updated_at:f.now}),skuUomId=index===0?f.skuUomId:await f.insert('item_sku_uoms',{sku_id:skuId,uom_id:Number(uom.uom_id),to_base_factor:1,is_base:1,is_default_sale:1,created_at:f.now,updated_at:f.now});const [[sku]]=await f.db.query('SELECT sku_code FROM item_skus WHERE id=?',[skuId]);skus.push({skuId,skuUomId,code:sku.sku_code});}
 const [[bin]]=await f.db.query('SELECT id FROM inventory_bins WHERE warehouse_id=?',[f.warehouseId]);for(const sku of skus)await f.db.execute("INSERT INTO inventory_stock_balances (warehouse_id,bin_id,sku_id,stock_status,on_hand_quantity,created_at,updated_at) VALUES (?,?,?,'AVAILABLE',100000,?,?)",[f.warehouseId,Number(bin.id),sku.skuId,f.now,f.now]);
 await f.db.execute("INSERT INTO role_permissions (role_id,permission_id) SELECT ?,id FROM permissions WHERE name='sales.import'",[f.roleId]);
 for(let index=0;index<50;index++){const label='p3cap-'+runId+'-'+index,customerId=await f.insert('customers',{customer_code:label,customer_code_key:label,legal_name:label,legal_name_key:label,default_currency_code:f.currency,status:'active',version:1,created_at:f.now,updated_at:f.now}),userId=await f.insert('users',{username:label,password_hash:'synthetic-only',display_name:'Synthetic capacity',created_at:f.now,updated_at:f.now});await f.db.execute('INSERT INTO user_roles (user_id,role_id) VALUES (?,?)',[userId,f.roleId]);const claims={...f.claims,actorId:userId,claimedPermissions:['sales.view','sales.mgmt','sales.import']},token=await app.services.require('jwt').issue({roles:claims.claimedRoles,permissions:claims.claimedPermissions},{subject:String(userId),version:await app.services.require('tokenRevocation').currentVersion(String(userId)),authTime:Math.floor(f.now/1000)});actors.push({index,userId,customerId,claims,token,tokenIssuedAt:Date.now()});f.beforeParents.push(async()=>{await f.db.execute('DELETE FROM sales_orders WHERE customer_id=?',[customerId]);await f.db.execute('DELETE FROM sales_audit_logs WHERE actor_user_id=?',[userId]);await f.db.execute('DELETE FROM sales_operation_requests WHERE actor_user_id=?',[userId]);await f.db.execute('DELETE FROM fr_token_versions WHERE subject=?',[String(userId)]);await f.db.execute('DELETE FROM user_roles WHERE user_id=?',[userId]);});}
 f.beforeParents.push(async()=>{await app.shutdown('sales_import_capacity_cleanup');for(const actor of actors)await f.db.execute('DELETE FROM sales_orders WHERE customer_id=?',[actor.customerId]);const [ownedJobs]=await f.db.query('SELECT id,batch_number FROM sales_import_jobs WHERE created_by=?',[actors[0].userId]);for(const job of ownedJobs){await f.db.execute('DELETE FROM sales_external_order_keys WHERE id IN (SELECT external_order_key_id FROM sales_intake_orders WHERE import_job_id=?)',[job.id]);await f.db.execute('DELETE FROM sales_import_jobs WHERE id=?',[job.id]);if(/^SI-\d{6}-\d{6}$/u.test(job.batch_number))await rm(path.join('storage/sales-imports',job.batch_number),{recursive:true,force:true});}});
 for(const name of ['sales.importWorker','sales.confirmationRecovery','sales.backorderAllocate']){const [[original]]=await f.db.query('SELECT * FROM fr_job_leases WHERE job_name=?',[name]);f.beforeParents.push(async()=>{if(original)await f.db.execute('UPDATE fr_job_leases SET owner=?,acquired_at=?,expires_at=? WHERE job_name=?',[original.owner,original.acquired_at,original.expires_at,name]);else await f.db.execute('DELETE FROM fr_job_leases WHERE job_name=?',[name]);});}
 let finishForeground=false,foregroundTasks=[];const foregroundFailures=[],samples=[];f.beforeParents.push(async()=>{finishForeground=true;await Promise.all(foregroundTasks);await app.shutdown('sales_import_capacity_stop_before_restore');});
 f.customerIds=[f.customerId,...actors.map(actor=>actor.customerId)];
 const create=async(actor,lineCount=1,quantity='1.000000',selected=skus.slice(0,lineCount))=>{const result=await orders.create({claims:actor.claims,input:{eventId:randomUUID(),customerId:actor.customerId,currencyCode:f.currency,fulfillmentWarehouseId:f.warehouseId,orderDate:time.fileDate(),lines:selected.map(sku=>({skuId:sku.skuId,skuUomId:sku.skuUomId,quantity,unitSellingPrice:'1.0000'}))}});return {actor,id:result.salesOrder.id,eventId:randomUUID(),version:result.salesOrder.version,lineCount};};
 // Actual recovery/backorder work shares the pool with the Import worker; no faster test-only cadence.
 const recovery=await create(actors[0]),recoveryIntent=await confirmation.startConfirmation({claims:recovery.actor.claims,id:recovery.id,input:{eventId:recovery.eventId,version:recovery.version}});await f.db.execute('UPDATE sales_operation_requests SET lease_until=0 WHERE event_id=?',[recoveryIntent.eventId]);
 await f.db.execute('UPDATE inventory_stock_balances SET on_hand_quantity=0 WHERE warehouse_id=? AND sku_id=?',[f.warehouseId,skus[99].skuId]);const backorder=await create(actors[1],1,'1.000000',[skus[99]]),backorderIntent=await confirmation.startConfirmation({claims:backorder.actor.claims,id:backorder.id,input:{eventId:backorder.eventId,version:backorder.version}});await confirmation.completeConfirmation({eventId:backorderIntent.eventId,claims:backorder.actor.claims,leaseOwner:backorderIntent.leaseOwner});await f.db.execute('UPDATE inventory_stock_balances SET on_hand_quantity=100000 WHERE warehouse_id=? AND sku_id=?',[f.warehouseId,skus[99].skuId]);
 const {url}=await app.start(),target=new URL(url),proxy=createServer((req,res)=>{const match=/^\/client\/(\d{1,2})(\/api\/.*)$/u.exec(req.url??'');if(!match||Number(match[1])>=50){res.writeHead(404).end();return;}const upstream=httpRequest({hostname:target.hostname,port:target.port,path:match[2],method:req.method,headers:{authorization:req.headers.authorization,'content-type':'application/json','idempotency-key':req.headers['idempotency-key']??'','x-forwarded-for':`192.0.2.${Number(match[1])+1}`}},response=>{res.writeHead(response.statusCode,response.headers);response.pipe(res);});upstream.on('error',()=>res.writeHead(502).end());req.pipe(upstream);});await new Promise(resolve=>{proxy.listen(0,'127.0.0.1',resolve);});t.after(()=>new Promise(resolve=>{proxy.close(resolve);}));const proxyUrl=`http://127.0.0.1:${proxy.address().port}`;
 const [[warehouse]]=await f.db.query('SELECT warehouse_code FROM inventory_warehouses WHERE id=?',[f.warehouseId]),[[unit]]=await f.db.query('SELECT code FROM item_uoms WHERE id=?',[uom.uom_id]);let generatedRows=0,bytes=0;const digest=createHash('sha256');
 async function* body(){const boundary='sales-'+runId;yield `--${boundary}\r\nContent-Disposition: form-data; name="eventId"\r\n\r\n${uploadEvent}\r\n--${boundary}\r\nContent-Disposition: form-data; name="file"; filename="synthetic-capacity.csv"\r\nContent-Type: text/csv\r\n\r\n`;function* rows(){yield SALES_CSV_COLUMNS.map(c=>c.name);for(let order=0;order<10000;order++)for(let line=0;line<5;line++){const row={templateVersion:'1.0',sourceOrderKey:'P3CAP-'+runId+'-'+order,channelCode:'SYNTHETIC',externalOrderId:'P3CAP-'+runId+'-'+order,customerId:String(actors[order%50].customerId),warehouseCode:warehouse.warehouse_code,orderDate:time.fileDate(),requestedDeliveryDate:'',currencyCode:f.currency,paymentTermCode:'',customerPoReference:'',orderNotes:'',skuCode:skus[line].code,salesUomCode:unit.code,quantity:'1.000000',unitSellingPrice:'1.0000',lineNote:''};generatedRows++;yield SALES_CSV_COLUMNS.map(c=>row[c.name]);}}for await(const chunk of Readable.from(rows()).pipe(stringify({record_delimiter:'\r\n'}))){bytes+=Buffer.byteLength(chunk);digest.update(chunk);yield chunk;}yield `\r\n--${boundary}--\r\n`;}
 const scheduler=app.services.require('scheduler'),baseline=process.memoryUsage(),peak={...baseline};let peakPoolQueue=0;const monitor=setInterval(()=>{const current=process.memoryUsage();for(const field of Object.keys(peak))peak[field]=Math.max(peak[field],current[field]);peakPoolQueue=Math.max(peakPoolQueue,app.services.require('mysqldatabase').pool.pool._connectionQueue.length);},5);monitor.unref();t.after(()=>clearInterval(monitor));
 assert.equal(app.configuration.database.connectionLimit,10);assert.equal(app.configuration.database.queueLimit,200);assert.equal(app.configuration.requestLimiter.maxRequestsPerIpPerWindow,20);assert.equal(scheduler.jobs.get('sales.importWorker').intervalMs,2000);assert.equal(scheduler.jobs.get('sales.importWorker').timeoutMs,30000);assert.equal(app.configuration.sales.importWorkerBatchSize,50);
 const started=performance.now();let stage='upload';
 async function bearer(actor){if(Date.now()-actor.tokenIssuedAt>480000){actor.token=await app.services.require('jwt').issue({roles:actor.claims.claimedRoles,permissions:actor.claims.claimedPermissions},{subject:String(actor.userId),version:await app.services.require('tokenRevocation').currentVersion(String(actor.userId)),authTime:Math.floor(f.now/1000)});actor.tokenIssuedAt=Date.now();}return actor.token;}
 foregroundTasks=actors.map(async actor=>{let round=0;for(;;){if(finishForeground)break;const request=await create(actor,actor.index%10===0?100:1),begin=performance.now(),sampleStage=stage,root=`${proxyUrl}/client/${actor.index}`,headers={Authorization:`Bearer ${await bearer(actor)}`,'Content-Type':'application/json','Idempotency-Key':request.eventId},response=await fetch(`${root}/api/v1/sales-orders/${request.id}/confirm`,{method:'POST',headers,body:JSON.stringify({eventId:request.eventId,version:request.version})});let result=await response.json(),polls=0;if(response.status===202){while(result.data?.status!=='SUCCEEDED'&&polls++<20){await delay(2000);const lookup=await fetch(`${root}/api/v1/sales-operations/by-event/${request.eventId}`,{headers:{...headers,Authorization:`Bearer ${await bearer(actor)}`}});assert.equal(lookup.status,200);result=await lookup.json();}}const sample={actor:actor.index,round:round++,lineCount:request.lineCount,stage:sampleStage,startedMs:begin-started,ms:performance.now()-begin,status:response.status,complete:response.status===200&&result.data?.salesOrder?.status==='CONFIRMED'||response.status===202&&result.data?.status==='SUCCEEDED'};samples.push(sample);assert.ok(sample.complete,'Every foreground dependency outcome is counted');if(!finishForeground)await delay(10000);}}).map(task=>task.catch(error=>{foregroundFailures.push(error);finishForeground=true;}));
 const uploadEvent=randomUUID(),response=await fetch(new URL('/api/v1/sales-imports/upload',url),{method:'POST',headers:{Authorization:`Bearer ${await bearer(actors[0])}`,'Idempotency-Key':uploadEvent,'Content-Type':`multipart/form-data; boundary=sales-${runId}`},body:Readable.from(body()),duplex:'half'}),admission=await response.json();assert.equal(response.status,201);const jobId=admission.data.importJob.id;assert.equal(generatedRows,50000);assert.ok(bytes<=52428800);const [[uploaded]]=await f.db.query('SELECT file_sha256,file_size_bytes FROM sales_import_jobs WHERE id=?',[jobId]);assert.equal(Buffer.from(uploaded.file_sha256).toString('hex'),digest.digest('hex'));assert.equal(Number(uploaded.file_size_bytes),bytes);
 stage='precheck';const facts=async()=>(await f.db.query('SELECT * FROM sales_import_jobs WHERE id=?',[jobId]))[0][0];let current=await facts(),nextReport=performance.now()+60000;
 async function waitUntil(predicate){while(!predicate(current)){assert.ok(performance.now()-started<1800000,'Import exceeded30minute developer target');assert.equal(foregroundFailures.length,0,'No foreground dependency failure is excluded');const stats=scheduler.stats.get('sales.importWorker');assert.equal(stats.failures,0,'Actual Import worker must not hide failed ticks');await delay(2000);current=await facts();if(performance.now()>=nextReport){t.diagnostic(JSON.stringify({stage:current.status,valid:Number(current.valid_count),succeeded:Number(current.success_count),elapsedMs:Math.round(performance.now()-started)}));nextReport=performance.now()+60000;}}}
 await waitUntil(job=>job.status==='READY');const readyMs=performance.now()-started;assert.equal(Number(current.source_order_count),10000);assert.equal(Number(current.total_row_count),50000);assert.equal(Number(current.valid_count),10000);stage='processing';const confirmEvent=randomUUID(),confirm=await fetch(new URL(`/api/v1/sales-imports/${jobId}/confirm`,url),{method:'POST',headers:{Authorization:`Bearer ${await bearer(actors[0])}`,'Content-Type':'application/json','Idempotency-Key':confirmEvent},body:JSON.stringify({eventId:confirmEvent,version:Number(current.version)})});assert.equal(confirm.status,202);await confirm.arrayBuffer();await waitUntil(job=>job.status==='PROCESSING'&&Number(job.success_count)>=50);
 await waitUntil(job=>['COMPLETED','PARTIAL_SUCCESS','FAILED'].includes(job.status));const durationMs=performance.now()-started;finishForeground=true;await Promise.all(foregroundTasks);assert.equal(foregroundFailures.length,0,'All foreground failures remain gate failures');clearInterval(monitor);const sorted=samples.map(sample=>sample.ms).sort((a,b)=>a-b),p95Ms=sorted[Math.ceil(sorted.length*.95)-1],[[counts]]=await f.db.query('SELECT COUNT(*) AS orders,SUM(line_count) AS line_count,SUM(status=\'SUCCEEDED\') AS succeeded,COUNT(DISTINCT processing_event_id) AS events FROM sales_intake_orders WHERE import_job_id=?',[jobId]),[[business]]=await f.db.query('SELECT COUNT(DISTINCT o.id) AS orders,COUNT(l.id) AS line_count FROM sales_orders o JOIN sales_order_lines l ON l.sales_order_id=o.id WHERE o.source_intake_order_id IN (SELECT id FROM sales_intake_orders WHERE import_job_id=?)',[jobId]),[[mysql]]=await f.db.query('SELECT VERSION() AS version,@@innodb_buffer_pool_size AS buffer_pool_bytes');
 assert.equal(current.status,'COMPLETED');assert.deepEqual(Object.fromEntries(Object.entries(counts).map(([k,v])=>[k,Number(v)])),{orders:10000,line_count:50000,succeeded:10000,events:10000});assert.deepEqual(business,{orders:10000,line_count:50000});assert.equal(Number(current.success_count),10000);assert.equal(Number(current.failed_count),0);assert.ok(durationMs<=1800000);assert.ok(p95Ms<=3000,`Foreground P95 ${p95Ms}ms exceeds3000ms`);assert.equal(new Set(samples.map(sample=>sample.actor)).size,50);for(const phase of ['precheck','processing']){const phaseSamples=samples.filter(sample=>sample.stage===phase).map(sample=>sample.ms).sort((a,b)=>a-b);assert.ok(phaseSamples.length>=50);assert.ok(phaseSamples[Math.ceil(phaseSamples.length*.95)-1]<=3000,phase+' foreground P95 exceeds3000ms');}assert.ok(peakPoolQueue>0);const schedulerStats=['sales.importWorker','sales.confirmationRecovery','sales.backorderAllocate'].map(name=>({name,...scheduler.stats.get(name)}));assert.ok(schedulerStats.every(stats=>stats.runs>0&&stats.failures===0&&stats.timeouts===0));
 const [[effects]]=await f.db.query('SELECT (SELECT status FROM sales_operation_requests WHERE event_id=?) AS recovered,(SELECT reserved_outstanding_base_quantity FROM sales_order_lines WHERE sales_order_id=?) AS allocated',[recovery.eventId,backorder.id]);assert.deepEqual(effects,{recovered:'SUCCEEDED',allocated:1});const reconciliation=await reconcileCommitments(f);assert.deepEqual(reconciliation.mismatches,{conservation:0,mappings:0,queue:0,flags:0,reservations:0,controls:0});
 const download=await fetch(new URL(`/api/v1/sales-imports/${jobId}/result`,url),{headers:{Authorization:`Bearer ${await bearer(actors[0])}`}});assert.equal(download.status,200);let resultBytes=0;for await(const chunk of download.body)resultBytes+=chunk.byteLength;assert.ok(resultBytes>0);
 t.diagnostic(JSON.stringify({orders:10000,lines:50000,customers:50,importSkus:5,foregroundSkus:100,bytes,resultBytes,readyMs,durationMs,foreground:{users:50,samples:samples.length,distribution:{one:samples.filter(s=>s.lineCount===1).length,hundred:samples.filter(s=>s.lineCount===100).length},thinkTimeMs:10000,p95Ms,latencySamples:samples,excludedFailures:0,warmups:0,syntheticSeedConfirmations:1},memory:{baseline,peak,end:process.memoryUsage(),note:'Whole combined load sampled; unchanged isolated50MiB upload/parse memory gates separately enforce Phase0 thresholds'},peakPoolQueue,hardware:{cpu:cpus()[0].model,cpuCount:cpus().length,memoryBytes:totalmem()},node:process.version,mysql:mysql.version,bufferPoolBytes:Number(mysql.buffer_pool_bytes),pool:10,queueLimit:200,workerBatch:50,workerIntervalMs:2000,workerTimeoutMs:30000,cache:'master fixture prepared; no foreground confirmation warmups',scheduler:schedulerStats.map(s=>({name:s.name,runs:s.runs,failures:s.failures,timeouts:s.timeouts})),reconciliation}));
});

it('TC-042 isolated noncontiguous50MiB CSV grouping retains original Phase0 memory bounds',{timeout:180000},async t=>{
 const root=await mkdtemp(path.join(tmpdir(),'sales-capacity-spool-'));const code=`
 import assert from 'node:assert/strict';import process from 'node:process';import {readdir,rm} from 'node:fs/promises';import {stringify} from 'csv-stringify/sync';import {parseSalesCsv,SALES_CSV_COLUMNS} from './server/src/modules/sales/salesCsv.js';import {performance} from 'node:perf_hooks';
 const root=process.env.SALES_CAPACITY_SPOOL_ROOT,measurements=[];
 try{for(const [size,orders] of [[5*1024*1024,1000],[50*1024*1024,10000]]){
  let bytes=0,consumed=0;const names=SALES_CSV_COLUMNS.map(column=>column.name),base={templateVersion:'1.0',channelCode:'SYNTHETIC',customerId:'1',warehouseCode:'WH',orderDate:'2026-10-09',requestedDeliveryDate:'',currencyCode:'HKD',paymentTermCode:'',customerPoReference:'',orderNotes:'',skuCode:'SKU',salesUomCode:'EA',quantity:'1',unitSellingPrice:'1',lineNote:'x'.repeat(200)};
  async function* source(){const header=names.join(',')+'\\n';bytes+=Buffer.byteLength(header);yield header;for(let pass=0;pass<5;pass++)for(let order=0;order<orders;order++){const key='A'+String(order).padStart(4,'0'),row={...base,sourceOrderKey:key,externalOrderId:key};let record=stringify([names.map(name=>row[name])]);row.orderNotes='x'.repeat(1048-Buffer.byteLength(record));record=stringify([names.map(name=>row[name])]);assert.equal(Buffer.byteLength(record),1048);bytes+=Buffer.byteLength(record);yield record;}const padding=size-bytes;assert.ok(padding>=0);bytes+=padding;yield '\\n'.repeat(padding);}
  global.gc();const baseline=process.memoryUsage(),peak={...baseline},sample=()=>{global.gc();const usage=process.memoryUsage();for(const metric of Object.keys(peak))peak[metric]=Math.max(peak[metric],usage[metric]);},timer=setInterval(sample,100),started=performance.now();let counts;
  try{counts=await parseSalesCsv(source(),{spoolRoot:root,onFileValidated:sample,onOrder:group=>{consumed++;assert.equal(group.errors.length,0);assert.equal(group.rowCount,5);assert.equal(group.payload.lines.length,1);assert.equal(group.payload.lines[0].quantity,'5.000000');const order=Number(group.sourceOrderKey.slice(1));assert.deepEqual(group.payload.lines[0].rowNumbers,Array.from({length:5},(_,pass)=>order+2+pass*orders));if(consumed%1000===0)sample();}});sample();}finally{clearInterval(timer);}
  assert.equal(bytes,size);assert.deepEqual(counts,{rowCount:orders*5,orderCount:orders});assert.equal(consumed,orders);assert.deepEqual(await readdir(root),[]);if(size===50*1024*1024)for(const [metric,limitMiB] of [['heapUsed',16],['external',32],['rss',64]])assert.ok(peak[metric]-baseline[metric]<=limitMiB*1024*1024,metric+' exceeds original Phase0 limit');measurements.push({bytes,orders,rows:orders*5,noncontiguousPasses:5,baseline,peak,elapsedMs:performance.now()-started,retainedMemoryGcSampleMs:100});
 }}finally{await rm(root,{recursive:true,force:true});}console.log(JSON.stringify({measurements,node:process.version,limitsMiB:{heapUsed:16,external:32,rss:64}}));`;
 const child=spawn(process.execPath,['--expose-gc','--input-type=module','-e',code],{cwd:process.cwd(),env:{...process.env,SALES_CAPACITY_SPOOL_ROOT:root},stdio:['ignore','pipe','pipe']});const exited=once(child,'exit');t.after(async()=>{if(child.exitCode===null){child.kill();await exited.catch(()=>{});}await rm(root,{recursive:true,force:true});});let output='',errors='';child.stdout.on('data',chunk=>{output+=chunk;});child.stderr.on('data',chunk=>{errors+=chunk;});const [exitCode]=await exited;assert.equal(exitCode,0,errors);const evidence=JSON.parse(output);assert.equal(evidence.measurements.length,2);t.diagnostic(JSON.stringify(evidence));
});
