import assert from "node:assert/strict";
import test from "node:test";
import {migrationFixture} from "../sales/phase1/fixtures.js";
import {CustomerLookupService} from "../../src/modules/customer/CustomerLookupService.js";
import {ItemLookupService} from "../../src/modules/item/ItemLookupService.js";
const integrationTest=process.env.DB_INTEGRATION_TESTS==="1"?test:test.skip;
integrationTest("TC-035 owner precheck batches resolve actual DB collation and preserve missing/inactive without business writes",async t=>{
 const f=await migrationFixture(t,[]),[[sku]]=await f.db.query("SELECT sku_code FROM item_skus WHERE id=?",[f.skuId]),[[uom]]=await f.db.query("SELECT code FROM item_uoms WHERE id=(SELECT uom_id FROM item_sku_uoms WHERE id=?)",[f.skuUomId]);
 let queries=0;const tx={query(...args){queries++;return f.db.query(...args);}},customers=new CustomerLookupService({database:f.db}),items=new ItemLookupService({database:f.db,time:{nowMs:()=>f.now},logger:{error:async()=>{}}});
 const snapshots=await customers.getSalesPrecheckSnapshotsInTransaction(tx,[f.customerId,Number.MAX_SAFE_INTEGER]);assert.equal(queries,1);assert.equal(snapshots.get(f.customerId).status,"active");assert.equal(snapshots.get(Number.MAX_SAFE_INTEGER),null);
 const codes=[{skuCode:sku.sku_code.toUpperCase(),salesUomCode:uom.code.toUpperCase()},{skuCode:sku.sku_code,salesUomCode:"MISSING"},{skuCode:"MISSING",salesUomCode:uom.code}];
 queries=0;const resolved=await items.resolveSaleCodesInTransaction(tx,codes);assert.equal(queries,1);assert.equal(resolved[0].sku.skuId,f.skuId);assert.equal(resolved[0].salesUom.skuUomId,f.skuUomId);assert.equal(resolved[1].salesUom,null);assert.equal(resolved[2].sku,null);
 await f.db.execute("UPDATE item_skus SET status='discontinued' WHERE id=?",[f.skuId]);await f.db.execute("UPDATE customers SET status='blocked' WHERE id=?",[f.customerId]);
 assert.equal((await items.resolveSaleCodesInTransaction(tx,[codes[0]]))[0].sku.usable,false);assert.equal((await customers.getSalesPrecheckSnapshotsInTransaction(tx,[f.customerId])).get(f.customerId).status,"blocked");
 const [[effects]]=await f.db.query("SELECT (SELECT COUNT(*) FROM sales_orders WHERE customer_id=?) AS orders,(SELECT COUNT(*) FROM inventory_reservations WHERE sku_id=?) AS reservations",[f.customerId,f.skuId]);assert.equal(effects.orders,0);assert.equal(effects.reservations,0);
});

integrationTest("TC-035 real owner precheck batches isolate invalid sources and duplicate routing without SO or reservation effects",async t=>{
 const {randomUUID}=await import("node:crypto"),{precheckSalesOrders,salesSourceHash}=await import("../../src/modules/sales/salesImportPrecheck.js"),f=await migrationFixture(t,[]);
 const [[sku]]=await f.db.query("SELECT sku_code FROM item_skus WHERE id=?",[f.skuId]),[[uom]]=await f.db.query("SELECT code FROM item_uoms WHERE id=(SELECT uom_id FROM item_sku_uoms WHERE id=?)",[f.skuUomId]),[[warehouse]]=await f.db.query("SELECT warehouse_code FROM inventory_warehouses WHERE id=?",[f.warehouseId]);
 const group=()=>({sourceOrderKey:randomUUID(),externalOrderId:randomUUID(),channelCode:"SYNTHETIC",firstRowNo:2,lastRowNo:2,rowCount:1,errors:[],processingEventId:randomUUID(),payload:{customerId:f.customerId,channelCode:"SYNTHETIC",currencyCode:f.currency,orderDate:"2026-10-08",requestedDeliveryDate:null,warehouseCode:warehouse.warehouse_code.toUpperCase(),paymentTermCode:"",customerPoReference:"",notes:"",lines:[{skuCode:sku.sku_code.toUpperCase(),salesUomCode:uom.code.toUpperCase(),quantity:"1.000000",unitSellingPrice:"0.0000",lineNote:"",rowNumbers:[2]}]}});
 const valid=group(),missing=group(),duplicate=group(),alias=group();alias.payload.lines.push({...alias.payload.lines[0],skuCode:sku.sku_code.toLowerCase(),unitSellingPrice:"1.0000",rowNumbers:[3]});alias.lastRowNo=3;missing.payload.lines[0].skuCode="MISSING";
 const keyId=await f.insert("sales_external_order_keys",{channel_code:"SYNTHETIC",external_order_id:duplicate.externalOrderId,external_order_id_hash:salesSourceHash(duplicate.externalOrderId),source_type:"CSV",payload_hash:"0".repeat(64),status:"SUCCEEDED",sales_order_id:Number.MAX_SAFE_INTEGER,sales_order_number:"SO26000001",is_order_archived:1,claimed_at:f.now,updated_at:f.now});
 let queries=0;const tx={query(...args){queries++;return f.db.query(...args);}},results=await precheckSalesOrders({tx,groups:[valid,missing,duplicate,alias],customers:new CustomerLookupService({database:f.db}),items:new ItemLookupService({database:f.db,time:{nowMs:()=>f.now},logger:{error:async()=>{}}}),config:{importChannelCodes:["SYNTHETIC"]},nowMs:f.now});
 assert.deepEqual(results.map(r=>r.status),["VALID","INVALID","DUPLICATE","INVALID"]);assert.equal(results[0].payload.document.fulfillmentWarehouseId,f.warehouseId);assert.equal(results[2].duplicate.externalOrderKeyId,keyId);assert.equal(results[2].duplicate.isArchived,true);assert.ok(results[2].warnings.some(w=>w.code==="EXTERNAL_ORDER_PAYLOAD_CONFLICT"));assert.equal(results[3].errors[0].code,"SALES_LINE_MERGE_CONFLICT");assert.equal(queries,6);await f.db.execute("UPDATE customers SET status='blocked' WHERE id=?",[f.customerId]);const [replay]=await precheckSalesOrders({tx,groups:[duplicate],customers:new CustomerLookupService({database:f.db}),items:new ItemLookupService({database:f.db,time:{nowMs:()=>f.now},logger:{error:async()=>{}}}),config:{importChannelCodes:["SYNTHETIC"]},nowMs:f.now});assert.equal(replay.status,"DUPLICATE");assert.equal(replay.duplicate.externalOrderKeyId,keyId);
 const [[effects]]=await f.db.query("SELECT (SELECT COUNT(*) FROM sales_orders WHERE customer_id=?) AS orders,(SELECT COUNT(*) FROM inventory_reservations WHERE sku_id=?) AS reservations,(SELECT COUNT(*) FROM sales_external_order_keys WHERE external_order_id_hash=?) AS source_keys",[f.customerId,f.skuId,salesSourceHash(valid.externalOrderId)]);assert.equal(effects.orders,0);assert.equal(effects.reservations,0);assert.equal(effects.source_keys,0);
});

async function workerFixture(t,{batchSize=2,channels=["SYNTHETIC"]}={}){
 const {randomUUID,createHash}=await import("node:crypto"),path=(await import("node:path")).default,{mkdtemp,writeFile,rm}=await import("node:fs/promises"),{stringify}=await import("csv-stringify/sync"),{SALES_CSV_COLUMNS}=await import("../../src/modules/sales/salesCsv.js"),{SalesImportService}=await import("../../src/modules/sales/SalesImportService.js"),{prepareDiskTempDirectory}=await import("../../src/framework/upload/normalizeUploadConfig.js"),{createApplication}=await import("../../src/framework/application/createApplication.js"),{defaultConfigurationSource}=await import("../../src/framework/configuration/applicationConfiguration.js"),{SchedulerService}=await import("../../src/services/scheduler/SchedulerService.js"),{SalesJobRuntimeService}=await import("../../src/services/salesJobs/SalesJobRuntimeService.js"),{SalesImportJob}=await import("../../src/services/salesJobs/jobs/SalesImportJob.js");
 const f=await migrationFixture(t,[]),source=defaultConfigurationSource(),config={...source,application:{...source.application,port:0},sales:{...source.sales,importChannelCodes:channels,importWorkerBatchSize:batchSize},scheduler:{...source.scheduler,jobs:{...source.scheduler.jobs,"sales.importWorker":{enabled:false}}}},app=await createApplication({configurationSource:config});t.after(()=>app.shutdown("sales_import_precheck_complete"));
 const base=prepareDiskTempDirectory(`storage/test-sales-precheck-${randomUUID()}`),root=prepareDiskTempDirectory(path.join(base,"jobs")),tempRoot=prepareDiskTempDirectory(path.join(base,"temp"));t.after(()=>rm(base,{recursive:true,force:true}));
 const database=app.services.require("mysqldatabase"),time=app.services.require("time"),logger=app.services.require("logging").logger,label="precheck-"+randomUUID().slice(0,8),roleId=await f.insert("roles",{name:label,created_at:f.now}),userId=await f.insert("users",{username:label,password_hash:"synthetic",display_name:"Synthetic",created_at:f.now,updated_at:f.now});
 await f.db.execute("INSERT INTO user_roles (user_id,role_id) VALUES (?,?)",[userId,roleId]);for(const permission of ["sales.view","sales.import"])await f.db.execute("INSERT INTO role_permissions (role_id,permission_id) SELECT ?,id FROM permissions WHERE name=?",[roleId,permission]);
 const claims={actorId:userId,claimedRoles:[label],claimedPermissions:["sales.view","sales.import"]},service=new SalesImportService({database,time,root,tempRoot}),name="sales.importWorker",[[original]]=await f.db.query("SELECT * FROM fr_job_leases WHERE job_name=?",[name]);
 f.beforeParents.push(async()=>{await f.db.execute("DELETE FROM sales_audit_logs WHERE actor_user_id=?",[userId]);await f.db.execute("DELETE FROM sales_import_jobs WHERE created_by=?",[userId]);await f.db.execute("DELETE FROM sales_operation_requests WHERE actor_user_id=?",[userId]);await f.db.execute("DELETE FROM role_permissions WHERE role_id=?",[roleId]);await f.db.execute("DELETE FROM user_roles WHERE user_id=?",[userId]);if(original)await f.db.execute("UPDATE fr_job_leases SET owner=?,acquired_at=?,expires_at=? WHERE job_name=?",[original.owner,original.acquired_at,original.expires_at,name]);else await f.db.execute("DELETE FROM fr_job_leases WHERE job_name=?",[name]);});
 const [[sku]]=await f.db.query("SELECT sku_code FROM item_skus WHERE id=?",[f.skuId]),[[uom]]=await f.db.query("SELECT code FROM item_uoms WHERE id=(SELECT uom_id FROM item_sku_uoms WHERE id=?)",[f.skuUomId]),[[warehouse]]=await f.db.query("SELECT warehouse_code FROM inventory_warehouses WHERE id=?",[f.warehouseId]);
 const row={templateVersion:"1.0",sourceOrderKey:"A",channelCode:"SYNTHETIC",externalOrderId:"A-"+randomUUID(),customerId:String(f.customerId),warehouseCode:warehouse.warehouse_code,orderDate:"2026-10-08",requestedDeliveryDate:"",currencyCode:f.currency,paymentTermCode:"",customerPoReference:"",orderNotes:"",skuCode:sku.sku_code,salesUomCode:uom.code,quantity:"1",unitSellingPrice:"0",lineNote:""};
 async function upload(rows=[row],bytes,actorClaims=claims){const content=bytes??stringify([SALES_CSV_COLUMNS.map(c=>c.name),...rows.map(r=>SALES_CSV_COLUMNS.map(c=>r[c.name]))]),directory=await mkdtemp(path.join(tempRoot,"upload-")),storedName=randomUUID()+".csv";await writeFile(path.join(directory,".upload-owner"),"erp-disk-upload-v1\n",{mode:0o600});await writeFile(path.join(directory,storedName),content,{mode:0o600});return (await service.createFromUpload({claims:actorClaims,eventId:randomUUID(),file:{field:"file",path:path.join(directory,storedName),storedName,originalName:"synthetic.csv",mimeType:"text/csv",size:Buffer.byteLength(content),contentHash:createHash("sha256").update(content).digest("hex")}})).importJob;}
 async function registeredWorker(){const sources={mysqldatabase:database,time,logging:{logger}},services={require:key=>sources[key]},runtimeConfig={...app.configuration,scheduler:{...app.configuration.scheduler,enabled:true,startupJitterRatio:0,jobs:{}}},scheduler=new SchedulerService({config:runtimeConfig,services}),runtime=new SalesJobRuntimeService({config:runtimeConfig,services});sources.scheduler=scheduler;sources.salesJobs=runtime;const job=new SalesImportJob({config:runtimeConfig,services});await job.initialize();runtime.importer.root=root;runtime.importer.tempRoot=tempRoot;await scheduler.start();f.beforeParents.push(()=>scheduler.stop());return {scheduler,runtime,job,async run(){await scheduler.execute(scheduler.jobs.get(name));}};}
 const facts=async id=>({job:(await f.db.query("SELECT * FROM sales_import_jobs WHERE id=?",[id]))[0][0],children:(await f.db.query("SELECT * FROM sales_intake_orders WHERE import_job_id=? ORDER BY id",[id]))[0],errors:(await f.db.query("SELECT e.* FROM sales_intake_errors e JOIN sales_intake_orders i ON i.id=e.intake_order_id WHERE i.import_job_id=? ORDER BY e.id",[id]))[0]});
 return {...f,app,database,time,logger,root,tempRoot,userId,roleId,claims,row,service,upload,registeredWorker,facts};
}
integrationTest("TC-035 real registered worker persists bounded partial precheck, resumes original children and has zero business effects",async t=>{
 const f=await workerFixture(t),job=await f.upload([f.row,{...f.row,sourceOrderKey:"B",externalOrderId:"B",skuCode:"MISSING"},{...f.row,sourceOrderKey:"C",externalOrderId:"C",quantity:"bad"},{...f.row,sourceOrderKey:"D",externalOrderId:"D"}]),worker=await f.registeredWorker();
 await worker.run();assert.equal(worker.scheduler.stats.get("sales.importWorker").failures,0);const first=await f.facts(job.id);assert.equal(first.job.status,"VALIDATING");assert.equal(Number(first.job.total_row_count),4);assert.equal(first.children.length,4);assert.notEqual(first.children[0].processing_event_id,worker.scheduler.owner);assert.equal(first.job.lease_owner,null);
 await worker.scheduler.stop();const second=await f.registeredWorker();await second.run();assert.equal(second.scheduler.stats.get("sales.importWorker").failures,0);const result=await f.facts(job.id);assert.equal(result.job.status,"READY");assert.deepEqual([Number(result.job.valid_count),Number(result.job.invalid_count),Number(result.job.warning_count)],[2,2,2]);assert.deepEqual(result.children.map(r=>[r.id,r.processing_event_id]),first.children.map(r=>[r.id,r.processing_event_id]));assert.equal(result.errors.length,2);
 const [[effects]]=await f.db.query("SELECT (SELECT COUNT(*) FROM sales_orders WHERE created_by=?) AS orders,(SELECT COUNT(*) FROM inventory_reservations WHERE sku_id=?) AS reservations,(SELECT COUNT(*) FROM sales_external_order_keys WHERE external_order_id_hash IN (SELECT external_order_id_hash FROM sales_intake_orders WHERE import_job_id=?)) AS source_keys",[f.userId,f.skuId,job.id]);assert.deepEqual(effects,{orders:0,reservations:0,source_keys:0});
});
integrationTest("TC-035 registered worker refuses revoked actor and malformed whole file admits no child",async t=>{
 const f=await workerFixture(t),job=await f.upload(),worker=await f.registeredWorker();await f.db.execute("DELETE rp FROM role_permissions rp JOIN permissions p ON p.id=rp.permission_id WHERE rp.role_id=? AND p.name='sales.import'",[f.roleId]);await worker.run();assert.equal(worker.scheduler.stats.get("sales.importWorker").failures,0);assert.equal((await f.facts(job.id)).children.length,0);assert.equal((await f.facts(job.id)).job.status,"UPLOADED");
 await f.db.execute("INSERT INTO role_permissions (role_id,permission_id) SELECT ?,id FROM permissions WHERE name='sales.import'",[f.roleId]);await worker.run();assert.equal((await f.facts(job.id)).job.status,"READY");
 const malformed=await f.upload([],"invalid,header\n");await worker.run();const failed=await f.facts(malformed.id);assert.equal(failed.job.status,"FAILED");assert.equal(failed.children.length,0);assert.equal(failed.job.lease_owner,null);
});
integrationTest("TC-035 a revoked oldest uploader cannot starve the next authorized job",async t=>{
 const f=await workerFixture(t),{randomUUID}=await import("node:crypto"),label="old-"+randomUUID().slice(0,8),oldId=await f.insert("users",{username:label,password_hash:"synthetic",display_name:"Synthetic",created_at:f.now,updated_at:f.now});await f.db.execute("INSERT INTO user_roles (user_id,role_id) VALUES (?,?)",[oldId,f.roleId]);
 f.beforeParents.push(async()=>{await f.db.execute("DELETE FROM sales_import_jobs WHERE created_by=?",[oldId]);await f.db.execute("DELETE FROM sales_operation_requests WHERE actor_user_id=?",[oldId]);await f.db.execute("DELETE FROM user_roles WHERE user_id=?",[oldId]);});
 const oldest=await f.upload(undefined,undefined,{...f.claims,actorId:oldId}),newer=await f.upload([{...f.row,sourceOrderKey:"Newer",externalOrderId:"Newer"}]);await f.db.execute("UPDATE users SET status='disabled' WHERE id=?",[oldId]);const worker=await f.registeredWorker();await worker.run();
 assert.equal((await f.facts(oldest.id)).children.length,0);assert.equal((await f.facts(newer.id)).job.status,"READY");assert.equal(worker.scheduler.stats.get("sales.importWorker").failures,0);
});
integrationTest("TC-035 lost ingestion COMMIT acknowledgement resumes exact persisted source events once",async t=>{
 const f=await workerFixture(t),job=await f.upload([f.row,{...f.row,sourceOrderKey:"B",externalOrderId:"B"},{...f.row,sourceOrderKey:"C",externalOrderId:"C",quantity:"bad"},{...f.row,sourceOrderKey:"D",externalOrderId:"D"}]),worker=await f.registeredWorker();let lose=true;
 worker.runtime.importer.database={query:f.database.query.bind(f.database),async withTransaction(work,options){let inserted=false;const result=await f.database.withTransaction(tx=>work({query:tx.query.bind(tx),execute:async(sql,params)=>{const r=await tx.execute(sql,params);if(sql.startsWith("INSERT INTO sales_intake_orders"))inserted=true;return r;}}),options);if(inserted&&lose){lose=false;throw Object.assign(Error("synthetic lost acknowledgement"),{code:"DATABASE_TRANSACTION_INDETERMINATE"});}return result;}};
 await worker.run();assert.equal(worker.scheduler.stats.get("sales.importWorker").failures,1);const first=await f.facts(job.id);assert.equal(first.children.length,2);assert.equal(first.job.status,"VALIDATING");await worker.scheduler.stop();const next=await f.registeredWorker();await next.run();await next.run();const result=await f.facts(job.id);assert.equal(result.job.status,"READY");assert.equal(result.children.length,4);for(const child of first.children)assert.equal(result.children.find(r=>r.id===child.id).processing_event_id,child.processing_event_id);assert.equal(result.errors.length,1);
});
integrationTest("TC-035 actual Scheduler stop aborts child persistence and expired business claim resumes on a new registered worker",async t=>{
 const f=await workerFixture(t),job=await f.upload([f.row,{...f.row,sourceOrderKey:"B",externalOrderId:"B"}]),worker=await f.registeredWorker(),entered=Promise.withResolvers();let held=false;
 worker.runtime.importer.database={query:f.database.query.bind(f.database),withTransaction:(work,options)=>f.database.withTransaction(tx=>work({query:tx.query.bind(tx),execute:async(sql,params)=>{const result=await tx.execute(sql,params);if(!held&&sql.startsWith("INSERT INTO sales_intake_orders")){held=true;entered.resolve();await new Promise((resolve,reject)=>{options.signal.addEventListener("abort",()=>reject(options.signal.reason),{once:true});});}return result;}}),options)};
 const execution=worker.run();await Promise.race([entered.promise,execution.then(()=>assert.fail("worker did not reach persistence"))]);assert.deepEqual(await worker.scheduler.stop({timeoutMs:1000}),{stopped:true,drained:true});await execution;
 const stopped=await f.facts(job.id);assert.equal(stopped.children.length,0);assert.equal(stopped.job.status,"VALIDATING");assert.match(stopped.job.lease_owner,/^[a-f0-9-]{36}$/u);assert.equal(worker.runtime.importPrincipal(),null);
 await f.db.execute("UPDATE sales_import_jobs SET lease_until=CAST(UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000 AS UNSIGNED)-1 WHERE id=?",[job.id]);const next=await f.registeredWorker();await next.run();const result=await f.facts(job.id);assert.equal(result.job.status,"READY");assert.equal(result.children.length,2);assert.equal(result.job.lease_owner,null);
});
integrationTest("TC-035 provider failure and changed runtime signal preserve recoverable original children without invalidating peers",async t=>{
 const f=await workerFixture(t),job=await f.upload([f.row,{...f.row,sourceOrderKey:"B",externalOrderId:"B"}]),worker=await f.registeredWorker(),{ItemLookupService}=await import("../../src/modules/item/ItemLookupService.js");
 worker.runtime.importer.workerOptions.itemProvider={resolveSaleCodesInTransaction(){throw Error("synthetic provider outage");}};await worker.run();const first=await f.facts(job.id);assert.equal(first.children.length,2);assert.ok(first.children.every(r=>r.status==="RECEIVED"));assert.equal(first.errors.length,0);assert.equal(first.job.status,"VALIDATING");
 const items=new ItemLookupService({database:f.database,time:f.time,logger:f.logger}),authorize=worker.runtime.importer.precheck.authorize;let swapped=false;worker.runtime.importer.precheck.items={async resolveSaleCodesInTransaction(...args){const result=await items.resolveSaleCodesInTransaction(...args);swapped=true;return result;}};
 worker.runtime.importer.precheck.authorize=()=>{const principal=authorize();return swapped&&principal?{...principal,signal:new AbortController().signal}:principal;};await worker.run();const fenced=await f.facts(job.id);assert.ok(fenced.children.every(r=>r.status==="RECEIVED"));assert.equal(fenced.errors.length,0);assert.deepEqual(fenced.children.map(r=>r.processing_event_id),first.children.map(r=>r.processing_event_id));await worker.scheduler.stop();
 await f.db.execute("UPDATE sales_import_jobs SET lease_until=CAST(UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000 AS UNSIGNED)-1 WHERE id=?",[job.id]);const next=await f.registeredWorker();await next.run();const final=await f.facts(job.id);assert.equal(final.job.status,"READY");assert.ok(final.children.every(r=>r.status==="VALID"));assert.deepEqual(final.children.map(r=>r.processing_event_id),first.children.map(r=>r.processing_event_id));
});
integrationTest("TC-035 real registered worker completes bounded50MiB/100000-row ingestion inside its unchanged30-second deadline",async t=>{
 for(const orders of [1000,10000])await t.test(`${orders}-orders`,async t=>{
  const f=await workerFixture(t,{batchSize:50}),{open,mkdtemp,writeFile}=await import("node:fs/promises"),path=(await import("node:path")).default,{randomUUID,createHash}=await import("node:crypto"),{SALES_CSV_COLUMNS}=await import("../../src/modules/sales/salesCsv.js"),{stringify}=await import("csv-stringify/sync"),directory=await mkdtemp(path.join(f.tempRoot,"upload-")),storedName=randomUUID()+".csv",filePath=path.join(directory,storedName),handle=await open(filePath,"w",0o600),digest=createHash("sha256");let bytes=0;
  const write=async text=>{digest.update(text);bytes+=Buffer.byteLength(text);await handle.write(text);};await write(SALES_CSV_COLUMNS.map(c=>c.name).join(",")+"\n");const lines=100000/orders;
  for(let source=0;source<orders;source++){let chunk="";for(let index=0;index<lines;index++){const value={...f.row,sourceOrderKey:"Group"+source,externalOrderId:"External"+source,skuCode:index===0?f.row.skuCode:"MISSING"+index,lineNote:""};let record=stringify([SALES_CSV_COLUMNS.map(c=>value[c.name])]);value.lineNote="x".repeat(524-Buffer.byteLength(record));record=stringify([SALES_CSV_COLUMNS.map(c=>value[c.name])]);assert.equal(Buffer.byteLength(record),524);chunk+=record;}await write(chunk);}
  await write("\n".repeat(52428800-bytes));await handle.close();await writeFile(path.join(directory,".upload-owner"),"erp-disk-upload-v1\n",{mode:0o600});
  const job=(await f.service.createFromUpload({claims:f.claims,eventId:randomUUID(),file:{field:"file",path:filePath,storedName,originalName:"capacity.csv",mimeType:"text/csv",size:bytes,contentHash:digest.digest("hex")}})).importJob,worker=await f.registeredWorker(),started=performance.now();await worker.run();const elapsedMs=Math.round(performance.now()-started),stat=worker.scheduler.stats.get("sales.importWorker");assert.equal(stat.timeouts,0);assert.equal(stat.failures,0);assert.ok(elapsedMs<30000);
  const [[counts]]=await f.db.query("SELECT total_row_count,source_order_count,(SELECT COUNT(*) FROM sales_intake_orders WHERE import_job_id=j.id) AS children FROM sales_import_jobs j WHERE id=?",[job.id]);assert.equal(Number(counts.total_row_count),100000);assert.equal(Number(counts.source_order_count),orders);assert.equal(Number(counts.children),orders);t.diagnostic(JSON.stringify({bytes,rows:100000,orders,elapsedMs,deadlineMs:30000}));await worker.scheduler.stop();
 });
});
integrationTest("TC-036 actual Import read APIs paginate safe summaries and enforce child-parent ownership for view-only users",async t=>{
 const f=await workerFixture(t),first=await f.upload([f.row,{...f.row,sourceOrderKey:"Invalid",externalOrderId:"Invalid",quantity:"bad"}]),worker=await f.registeredWorker();await worker.run();const second=await f.upload([{...f.row,sourceOrderKey:"Second",externalOrderId:"Second"}]);await worker.run();await worker.scheduler.stop();
 const firstFacts=await f.facts(first.id),invalid=firstFacts.children.find(row=>row.status==="INVALID");assert.ok(invalid);
 await f.db.execute("DELETE rp FROM role_permissions rp JOIN permissions p ON p.id=rp.permission_id WHERE rp.role_id=? AND p.name='sales.import'",[f.roleId]);const {url}=await f.app.start(),token=await f.app.services.require("jwt").issue({roles:f.claims.claimedRoles,permissions:["sales.view"]},{subject:String(f.userId),version:await f.app.services.require("tokenRevocation").currentVersion(String(f.userId)),authTime:Math.floor(f.now/1000)});
 f.beforeParents.push(()=>f.db.execute("DELETE FROM fr_token_versions WHERE subject=?",[String(f.userId)]));
 const get=async(path,auth=true)=>{const response=await fetch(new URL(path,url),{headers:auth?{Authorization:`Bearer ${token}`}:{}});return {status:response.status,body:await response.json()};};
 const list=await get(`/api/v1/sales-imports?actorId=${f.userId}&pageSize=1&sortBy=batchNumber&descending=false`);assert.equal(list.status,200);assert.equal(list.body.data.total,2);assert.equal(list.body.data.items.length,1);assert.equal(list.body.data.items[0].id,first.id);assert.deepEqual(list.body.data.items[0].allowedActions,[]);
 const detail=await get(`/api/v1/sales-imports/${first.id}`);assert.equal(detail.status,200);assert.equal(detail.body.data.invalidCount,1);assert.doesNotMatch(JSON.stringify(detail.body),/source_file_path|safe_payload|processing_event_id|file_sha256|lease_owner|source\.csv/);
 const orders=await get(`/api/v1/sales-imports/${first.id}/orders?status=INVALID&pageSize=1`);assert.equal(orders.status,200);assert.equal(orders.body.data.total,1);assert.equal(orders.body.data.items[0].id,Number(invalid.id));assert.doesNotMatch(JSON.stringify(orders.body),/safe_payload|payload_hash|processing_event_id|value_summary/);
 const errors=await get(`/api/v1/sales-imports/${first.id}/orders/${invalid.id}/errors?pageSize=1`);assert.equal(errors.status,200);assert.equal(errors.body.data.total,1);assert.equal(errors.body.data.items[0].code,"SALES_QUANTITY_INVALID");assert.doesNotMatch(JSON.stringify(errors.body),/value_summary|safe_payload|SQL|stack/);
 const mismatch=await get(`/api/v1/sales-imports/${second.id}/orders/${invalid.id}/errors`),absent=await get(`/api/v1/sales-imports/${Number.MAX_SAFE_INTEGER}/orders/${invalid.id}/errors`);assert.equal(mismatch.status,404);assert.equal(absent.status,404);assert.equal(mismatch.body.error.code,absent.body.error.code);assert.equal(mismatch.body.error.message,absent.body.error.message);
 for(const query of ["sortBy=constructor","pageSize=101","unknown=1","page=9007199254740991&pageSize=100","createdFrom=2&createdTo=1"]){const bad=await get(`/api/v1/sales-imports?${query}`);assert.equal(bad.status,400);assert.equal(bad.body.error.code,"SALES_INPUT_INVALID");}
 assert.equal((await get(`/api/v1/sales-imports/${first.id}`,false)).status,401);
 await f.db.execute("UPDATE sales_import_jobs SET source_file_path='' WHERE id=?",[second.id]);assert.equal((await get(`/api/v1/sales-imports/${second.id}`)).status,404);await f.db.execute("UPDATE sales_import_jobs SET files_purged_at=? WHERE id=?",[f.now,second.id]);assert.equal((await get(`/api/v1/sales-imports/${second.id}`)).status,200);
 await f.db.execute("DELETE FROM role_permissions WHERE role_id=?",[f.roleId]);const revoked=await get(`/api/v1/sales-imports/${first.id}`);assert.equal(revoked.status,403);assert.equal(revoked.body.error.code,"PERMISSION_STALE");
});
integrationTest("TC-037 native Import controls enforce CAS, event replay/races, rollback and fresh HTTP cache authorization",async t=>{
 const f=await workerFixture(t),{randomUUID}=await import("node:crypto"),job=await f.upload([f.row,{...f.row,sourceOrderKey:"Bad",externalOrderId:"Bad",quantity:"bad"}]),worker=await f.registeredWorker();await worker.run();await worker.scheduler.stop();const ready=await f.facts(job.id),version=Number(ready.job.version),eventId=randomUUID(),input={eventId,version};
 const result=await f.service.confirm({claims:f.claims,id:job.id,input});assert.equal(result.importJob.status,"QUEUED");const queued=await f.facts(job.id);assert.equal(Number(queued.job.confirmed_by),f.userId);assert.deepEqual(queued.children.map(r=>r.status).sort(),["INVALID","QUEUED"]);assert.deepEqual(queued.children.map(r=>r.processing_event_id),ready.children.map(r=>r.processing_event_id));
 assert.deepEqual(await f.service.confirm({claims:f.claims,id:job.id,input}),result);await assert.rejects(()=>f.service.confirm({claims:f.claims,id:job.id,input:{...input,version:version+1}}),{code:"SALES_EVENT_CONFLICT"});
 const [[audits]]=await f.db.query("SELECT COUNT(*) AS n FROM sales_audit_logs WHERE event_id=? AND action='sales_import.confirmed'",[eventId]);assert.equal(Number(audits.n),1);
 const next=await f.upload([{...f.row,sourceOrderKey:"Race",externalOrderId:randomUUID()}]),again=await f.registeredWorker();again.runtime.importer.runProcessingBatch=async()=>({processed:0});await again.run();await again.scheduler.stop();const before=await f.facts(next.id),race=await Promise.allSettled([f.service.confirm({claims:f.claims,id:next.id,input:{eventId:randomUUID(),version:Number(before.job.version)}}),f.service.cancel({claims:f.claims,id:next.id,input:{eventId:randomUUID(),version:Number(before.job.version)}})]);assert.equal(race.filter(r=>r.status==="fulfilled").length,1);assert.ok(["VERSION_CONFLICT","CONCURRENT_OPERATION"].includes(race.find(r=>r.status==="rejected").reason.code));
 const {SalesImportService}=await import("../../src/modules/sales/SalesImportService.js"),failure=new SalesImportService({database:f.database,time:f.time,root:f.root,tempRoot:f.tempRoot,audit:{record(){throw Error("required audit unavailable");}}}),failedEvent=randomUUID();await assert.rejects(()=>failure.cancel({claims:f.claims,id:job.id,input:{eventId:failedEvent,version:result.importJob.version}}),error=>error.cause?.message==="required audit unavailable");assert.equal((await f.facts(job.id)).job.status,"QUEUED");assert.equal((await f.db.query("SELECT COUNT(*) AS n FROM sales_operation_requests WHERE event_id=?",[failedEvent]))[0][0].n,0);
 const {url}=await f.app.start(),token=await f.app.services.require("jwt").issue({roles:f.claims.claimedRoles,permissions:f.claims.claimedPermissions},{subject:String(f.userId),version:await f.app.services.require("tokenRevocation").currentVersion(String(f.userId)),authTime:Math.floor(f.now/1000)});f.beforeParents.push(()=>f.db.execute("DELETE FROM fr_token_versions WHERE subject=?",[String(f.userId)]));
 const cancelEvent=randomUUID(),post=()=>fetch(new URL(`/api/v1/sales-imports/${job.id}/cancel`,url),{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json","Idempotency-Key":cancelEvent},body:JSON.stringify({eventId:cancelEvent,version:result.importJob.version})});
 const cancelled=await post();assert.equal(cancelled.status,200);assert.equal((await cancelled.json()).data.importJob.status,"CANCELLED");const replay=await post();assert.equal(replay.status,200);await replay.arrayBuffer();await f.db.execute("DELETE rp FROM role_permissions rp JOIN permissions p ON p.id=rp.permission_id WHERE rp.role_id=? AND p.name='sales.import'",[f.roleId]);const revoked=await post();assert.equal(revoked.status,403);assert.equal((await revoked.json()).error.code,"PERMISSION_STALE");
 f.beforeParents.push(()=>f.db.execute("DELETE FROM sales_audit_logs WHERE actor_user_id=?",[f.userId]));
});
integrationTest("TC-037 native result stream neutralizes source/error cells and denies missing, symlink, traversal and purged artifacts",async t=>{
 const f=await workerFixture(t),{createSalesImportResultStream}=await import("../../src/modules/sales/salesImportResult.js"),{pipeline}=await import("node:stream/promises"),{createWriteStream}=await import("node:fs"),{symlink,unlink,chmod}=await import("node:fs/promises"),path=(await import("node:path")).default,{parse}=await import("csv-parse/sync"),job=await f.upload([{...f.row,sourceOrderKey:"  =1,\"quoted\"",externalOrderId:"@cmd",quantity:"bad"}]),worker=await f.registeredWorker();await worker.run();await worker.scheduler.stop();const facts=await f.facts(job.id),relative=`${job.batchNumber}/result.csv`,file=path.join(f.root,relative);
 await f.db.execute("UPDATE sales_intake_errors SET safe_message='  +cmd' WHERE intake_order_id=?",[facts.children[0].id]);await pipeline(createSalesImportResultStream({database:f.database,id:job.id}),createWriteStream(file,{flags:"wx",mode:0o600}));await f.db.execute("UPDATE sales_import_jobs SET status='FAILED',completed_at=?,result_file_path=? WHERE id=?",[f.time.nowMs(),relative,job.id]);
 const consume=async()=>{const result=await f.service.resolveResultDownload({claims:f.claims,id:job.id});let text="";for await(const chunk of result.stream)text+=chunk;return text;};const rows=parse(await consume(),{bom:true});assert.equal(rows[1][0],"'  =1,\"quoted\"");assert.equal(rows[1][2],"'@cmd");assert.equal(rows[1][7],"'  +cmd");
 await f.db.execute("UPDATE sales_import_jobs SET result_file_path='../foreign.csv' WHERE id=?",[job.id]);await assert.rejects(()=>consume(),{code:"SALES_IMPORT_RESULT_EXPIRED"});await f.db.execute("UPDATE sales_import_jobs SET result_file_path=? WHERE id=?",[relative,job.id]);await chmod(file,0o644);await assert.rejects(()=>consume(),{code:"SALES_IMPORT_RESULT_EXPIRED"});await chmod(file,0o600);await unlink(file);await symlink(path.join(f.root,job.batchNumber,"source.csv"),file);await assert.rejects(()=>consume(),{code:"SALES_IMPORT_RESULT_EXPIRED"});await unlink(file);await assert.rejects(()=>consume(),{code:"SALES_IMPORT_RESULT_EXPIRED"});
 await f.db.execute("UPDATE sales_import_jobs SET files_purged_at=? WHERE id=?",[f.time.nowMs(),job.id]);await assert.rejects(()=>consume(),{code:"SALES_IMPORT_RESULT_EXPIRED"});await assert.rejects(()=>f.service.resolveResultDownload({claims:f.claims,id:Number.MAX_SAFE_INTEGER}),{code:"SALES_IMPORT_NOT_FOUND"});
});
integrationTest("TC-037 actual HTTP result downloads safe CSV for view-only actor and reports purge410",async t=>{
 const f=await workerFixture(t),job=await f.upload([{...f.row,sourceOrderKey:"=cmd",externalOrderId:"@cmd",quantity:"bad"}]),worker=await f.registeredWorker();await worker.run();await worker.scheduler.stop();
 const {DownloadSalesImportResultHandler}=await import("../../src/handlers/sales-imports/downloadSalesImportResultHandler.js"),{createSalesImportResultStream}=await import("../../src/modules/sales/salesImportResult.js"),{createApplication}=await import("../../src/framework/application/createApplication.js"),{defaultConfigurationSource}=await import("../../src/framework/configuration/applicationConfiguration.js"),{pipeline}=await import("node:stream/promises"),{createWriteStream}=await import("node:fs"),path=(await import("node:path")).default,{parse}=await import("csv-parse/sync"),relative=`${job.batchNumber}/result.csv`;
 await pipeline(createSalesImportResultStream({database:f.database,id:job.id}),createWriteStream(path.join(f.root,relative),{flags:"wx",mode:0o600}));await f.db.execute("UPDATE sales_import_jobs SET status='FAILED',completed_at=?,result_file_path=? WHERE id=?",[f.time.nowMs(),relative,job.id]);await f.db.execute("DELETE rp FROM role_permissions rp JOIN permissions p ON p.id=rp.permission_id WHERE rp.role_id=? AND p.name='sales.import'",[f.roleId]);
 const handler=new DownloadSalesImportResultHandler(f.app.services);handler.imports.root=f.root;const source=defaultConfigurationSource(),app=await createApplication({configurationSource:{...source,application:{...source.application,port:0},scheduler:{...source.scheduler,jobs:{...source.scheduler.jobs,"sales.importWorker":{enabled:false}}}},handlers:{downloadSalesImportResult:handler}});t.after(()=>app.shutdown("sales_import_result_http_complete"));const {url}=await app.start(),token=await app.services.require("jwt").issue({roles:f.claims.claimedRoles,permissions:["sales.view"]},{subject:String(f.userId),version:await app.services.require("tokenRevocation").currentVersion(String(f.userId)),authTime:Math.floor(f.now/1000)});f.beforeParents.push(()=>f.db.execute("DELETE FROM fr_token_versions WHERE subject=?",[String(f.userId)]));
 const get=()=>fetch(new URL(`/api/v1/sales-imports/${job.id}/result`,url),{headers:{Authorization:`Bearer ${token}`}}),response=await get();assert.equal(response.status,200);assert.equal(response.headers.get("content-type"),"text/csv; charset=utf-8");assert.match(response.headers.get("content-disposition"),/attachment/u);assert.equal(response.headers.get("cache-control"),"private, no-store");const csv=await response.text(),rows=parse(csv,{bom:true});assert.equal(rows[1][0],"'=cmd");assert.equal(rows[1][2],"'@cmd");assert.doesNotMatch(csv,/safe_payload|value_summary|processing_event_id/);await f.db.execute("UPDATE sales_import_jobs SET files_purged_at=? WHERE id=?",[f.time.nowMs(),job.id]);const expired=await get();assert.equal(expired.status,410);assert.equal((await expired.json()).error.code,"SALES_IMPORT_RESULT_EXPIRED");
});
integrationTest("TC-037 native lost control COMMIT acknowledgement replays original domain event once and mandatory precheck audit rolls back",async t=>{
 const f=await workerFixture(t),{randomUUID}=await import("node:crypto"),{SalesImportService}=await import("../../src/modules/sales/SalesImportService.js"),job=await f.upload(),worker=await f.registeredWorker(),eventId=randomUUID();
 let failAudit=true;worker.runtime.importer.workerOptions.audit={async record(tx,data){if(failAudit&&data.action==="sales_import.prechecked")throw Error("required precheck audit unavailable");return f.service.audit.record(tx,data);}};await worker.run();assert.equal(worker.scheduler.stats.get("sales.importWorker").failures,1);const partial=await f.facts(job.id);assert.equal(partial.job.status,"VALIDATING");assert.equal(partial.children[0].status,"RECEIVED");failAudit=false;await worker.run();await worker.scheduler.stop();const ready=await f.facts(job.id);assert.equal(ready.job.status,"READY");assert.equal(ready.children[0].processing_event_id,partial.children[0].processing_event_id);
 let lose=true;const service=new SalesImportService({database:{async withTransaction(work,options){const result=await f.database.withTransaction(work,options);if(lose&&result?.importJob?.status==="QUEUED"){lose=false;throw Object.assign(Error("lost acknowledgement"),{code:"DATABASE_TRANSACTION_INDETERMINATE"});}return result;}},time:f.time,root:f.root,tempRoot:f.tempRoot}),input={eventId,version:Number(ready.job.version)};await assert.rejects(()=>service.confirm({claims:f.claims,id:job.id,input}),{code:"TRANSACTION_OUTCOME_UNKNOWN"});const replay=await service.confirm({claims:f.claims,id:job.id,input});assert.equal(replay.importJob.status,"QUEUED");assert.equal(Number((await f.facts(job.id)).job.version),Number(ready.job.version)+1);
 const [audits]=await f.db.query("SELECT action,COUNT(*) AS n FROM sales_audit_logs WHERE target_type='IMPORT_JOB' AND target_id=? GROUP BY action",[job.id]);assert.deepEqual(Object.fromEntries(audits.map(r=>[r.action,Number(r.n)])),{"sales_import.uploaded":1,"sales_import.prechecked":1,"sales_import.confirmed":1});
});

async function intakeFixture(t,rows,channels){
 const f=await workerFixture(t,{batchSize:50,channels}),{stock}=await import("../sales/phase2/fixtures.js"),{randomUUID}=await import("node:crypto"),{SalesIntakeService}=await import("../../src/modules/sales/SalesIntakeService.js");
 await stock(f,4);await f.db.execute("UPDATE currencies SET status='ACTIVE' WHERE code=?",[f.currency]);const job=await f.upload(rows?.(f)??[{...f.row,quantity:"10"}]),worker=await f.registeredWorker();await worker.run();const ready=await f.facts(job.id);assert.equal(ready.job.status,"READY");await f.service.confirm({claims:f.claims,id:job.id,input:{eventId:randomUUID(),version:Number(ready.job.version)}});
 const claim=randomUUID();await f.db.execute("UPDATE sales_import_jobs SET status='PROCESSING',lease_owner=?,lease_until=CAST(UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000 AS UNSIGNED)+60000 WHERE id=?",[claim,job.id]);
 f.beforeParents.push(async()=>{await worker.scheduler.stop();await f.db.execute("DELETE FROM sales_orders WHERE source_intake_order_id IN (SELECT id FROM sales_intake_orders WHERE import_job_id=?)",[job.id]);await f.db.execute("DELETE FROM sales_external_order_keys WHERE id IN (SELECT external_order_key_id FROM sales_intake_orders WHERE import_job_id=?)",[job.id]);});
 const service=options=>new SalesIntakeService({database:f.database,time:f.time,logger:f.logger,config:f.app.configuration.sales,authorizeSalesImport:()=>worker.runtime.importPrincipal(),...options});
 async function effect(id,options){let outcome,failure;worker.runtime.importer.runProcessingBatch=async()=>({processed:0});worker.runtime.importer.runPrecheckBatch=async({signal})=>{try{const intake=service(options);outcome=Array.isArray(id)?await Promise.all(id.map(intakeOrderId=>intake.process({intakeOrderId,jobClaimToken:claim,signal}))):await intake.process({intakeOrderId:id,jobClaimToken:claim,signal});return {processed:Array.isArray(id)?id.length:1};}catch(error){failure=error;throw error;}};await worker.run();if(failure)throw failure;return outcome;}
 return {...f,job,worker,claim,effect,service};
}
integrationTest("TC-038 actual registered Intake converts CSV with import-only actor atomically, replays and resolves lost COMMIT acknowledgement",async t=>{
 const f=await intakeFixture(t),child=(await f.facts(f.job.id)).children[0],result=await f.effect(Number(child.id));assert.equal(result.status,"SUCCEEDED",(await f.facts(f.job.id)).children[0].result_code);assert.ok(result.warnings.includes("PARTIAL_BACKORDER"));
 const [[order]]=await f.db.query("SELECT status,source_type,source_intake_order_id,external_order_key_id,confirmation_event_id,confirmed_by,version FROM sales_orders WHERE id=?",[result.salesOrderId]),[[line]]=await f.db.query("SELECT reserved_outstanding_base_quantity,backordered_base_quantity FROM sales_order_lines WHERE sales_order_id=?",[result.salesOrderId]);assert.equal(order.status,"CONFIRMED");assert.equal(order.source_type,"CSV");assert.equal(Number(order.source_intake_order_id),Number(child.id));assert.equal(order.confirmation_event_id,child.processing_event_id);assert.equal(Number(order.confirmed_by),f.userId);assert.equal(Number(order.version),2);assert.deepEqual([Number(line.reserved_outstanding_base_quantity),Number(line.backordered_base_quantity)],[4,6]);
 const [[key]]=await f.db.query("SELECT status,sales_order_id FROM sales_external_order_keys WHERE id=?",[order.external_order_key_id]),[[operation]]=await f.db.query("SELECT status,result_type FROM sales_operation_requests WHERE event_id=?",[child.processing_event_id]);assert.equal(key.status,"SUCCEEDED");assert.equal(Number(key.sales_order_id),result.salesOrderId);assert.deepEqual(operation,{status:"SUCCEEDED",result_type:"INTAKE_RESULT"});assert.equal((await f.facts(f.job.id)).children[0].status,"SUCCEEDED");assert.deepEqual(await f.effect(Number(child.id)),result);
 const [[counts]]=await f.db.query("SELECT (SELECT COUNT(*) FROM sales_orders WHERE source_intake_order_id=?) AS orders,(SELECT COUNT(*) FROM inventory_reservations WHERE warehouse_id=?) AS reservations",[child.id,f.warehouseId]);assert.deepEqual(counts,{orders:1,reservations:1});
});
integrationTest("TC-038 lost Intake COMMIT acknowledgement reads original event and cannot create another order",async t=>{
 const other=await intakeFixture(t),next=(await other.facts(other.job.id)).children[0];let lose=true;const database={query:other.database.query.bind(other.database),async withTransaction(work,options){const value=await other.database.withTransaction(work,options);if(lose&&value?.status==="SUCCEEDED"){lose=false;throw Object.assign(Error("synthetic lost acknowledgement"),{code:"DATABASE_TRANSACTION_INDETERMINATE"});}return value;}};await assert.rejects(()=>other.effect(Number(next.id),{database}),{code:"TRANSACTION_OUTCOME_UNKNOWN"});const replay=await other.effect(Number(next.id));assert.equal(replay.status,"SUCCEEDED");assert.equal((await other.db.query("SELECT COUNT(*) AS n FROM sales_orders WHERE source_intake_order_id=?",[next.id]))[0][0].n,1);
});
integrationTest("TC-038 business failure leaves no partial Sales/Inventory/key/op and technical failure retries the original event",async t=>{
 const f=await intakeFixture(t),child=(await f.facts(f.job.id)).children[0];await f.db.execute("UPDATE customers SET status='blocked' WHERE id=?",[f.customerId]);const result=await f.effect(Number(child.id));assert.equal(result.status,"FAILED");assert.equal((await f.facts(f.job.id)).children[0].status,"FAILED");
 const [[effects]]=await f.db.query("SELECT (SELECT COUNT(*) FROM sales_orders WHERE source_intake_order_id=?) AS orders,(SELECT COUNT(*) FROM inventory_reservations WHERE warehouse_id=?) AS reservations,(SELECT COUNT(*) FROM sales_external_order_keys WHERE external_order_id_hash=?) AS source_keys,(SELECT COUNT(*) FROM sales_operation_requests WHERE event_id=?) AS operations",[child.id,f.warehouseId,child.external_order_id_hash,child.processing_event_id]);assert.deepEqual(effects,{orders:0,reservations:0,source_keys:0,operations:0});assert.equal((await f.facts(f.job.id)).errors.length,1);
});
integrationTest("TC-038 required audit failure rolls back Intake and same-event technical retry succeeds",async t=>{
 const other=await intakeFixture(t),next=(await other.facts(other.job.id)).children[0],{SalesOrderService}=await import("../../src/modules/sales/SalesOrderService.js"),orders=new SalesOrderService({database:other.database,time:other.time,logger:other.logger,audit:{record(){throw Error("synthetic required audit unavailable");}}});await assert.rejects(()=>other.effect(Number(next.id),{orderService:orders}),error=>error.cause?.message==="synthetic required audit unavailable");assert.equal((await other.facts(other.job.id)).children[0].status,"QUEUED");assert.equal((await other.db.query("SELECT COUNT(*) AS n FROM sales_orders WHERE source_intake_order_id=?",[next.id]))[0][0].n,0);const successful=await other.effect(Number(next.id));assert.equal(successful.status,"SUCCEEDED");assert.equal((await other.facts(other.job.id)).children[0].processing_event_id,next.processing_event_id);
});
integrationTest("TC-038 real concurrent duplicate storm creates one SO and preserves source/channel separation and conflict warnings",async t=>{
 const f=await intakeFixture(t,f=>Array.from({length:40},(_,index)=>({...f.row,sourceOrderKey:`Source-${index}`,channelCode:index===39?"SYNTHETIC_ALT":"SYNTHETIC",quantity:index===38?"11":"10"})),["SYNTHETIC","SYNTHETIC_ALT"]),children=(await f.facts(f.job.id)).children,results=await f.effect(children.map(row=>Number(row.id)));assert.equal(results.filter(row=>row.status==="SUCCEEDED").length,2);assert.equal(results.filter(row=>row.status==="DUPLICATE").length,38);const main=children.map((child,index)=>({...child,result:results[index]})).filter(child=>child.channel_code==="SYNTHETIC"),owner=main.find(child=>child.result.status==="SUCCEEDED");assert.ok(main.every(child=>child.result.salesOrderId===owner.result.salesOrderId));assert.notEqual(results[children.findIndex(child=>child.channel_code==="SYNTHETIC_ALT")].salesOrderId,owner.result.salesOrderId);for(const child of main.filter(child=>child.result.status==="DUPLICATE"))assert.deepEqual(child.result.warnings,child.payload_hash===owner.payload_hash?[]:["EXTERNAL_ORDER_PAYLOAD_CONFLICT"]);assert.deepEqual(await f.effect(children.map(row=>Number(row.id))),results);
 const [[counts]]=await f.db.query("SELECT (SELECT COUNT(*) FROM sales_orders WHERE source_intake_order_id IN (SELECT id FROM sales_intake_orders WHERE import_job_id=?)) AS orders,(SELECT COUNT(*) FROM sales_external_order_keys WHERE external_order_id_hash=?) AS source_keys",[f.job.id,children[0].external_order_id_hash]);assert.deepEqual(counts,{orders:2,source_keys:2});assert.equal(f.worker.scheduler.stats.get("sales.importWorker").timeouts,0);
});
integrationTest("TC-038 queued and cached Intake require fresh original import authority; source hash collision alerts and leaves no effects",async t=>{
 const f=await intakeFixture(t,f=>[f.row,{...f.row,sourceOrderKey:"Next",externalOrderId:"Next-"+f.row.externalOrderId}]),children=(await f.facts(f.job.id)).children,first=await f.effect(Number(children[0].id));assert.equal(first.status,"SUCCEEDED");await f.db.execute("DELETE rp FROM role_permissions rp JOIN permissions p ON p.id=rp.permission_id WHERE rp.role_id=? AND p.name='sales.import'",[f.roleId]);for(const child of children)await assert.rejects(()=>f.effect(Number(child.id)),{code:"FORBIDDEN"});assert.equal((await f.facts(f.job.id)).children[1].status,"QUEUED");await f.db.execute("INSERT INTO role_permissions (role_id,permission_id) SELECT ?,id FROM permissions WHERE name='sales.import'",[f.roleId]);
 const hash=children[1].external_order_id_hash;await f.db.execute("UPDATE sales_intake_orders SET external_order_id_hash=? WHERE id=?",[Buffer.alloc(32),children[1].id]);const alerts=[];await assert.rejects(()=>f.effect(Number(children[1].id),{logger:{error:async(...args)=>alerts.push(args)}}),{code:"SALES_SOURCE_HASH_COLLISION"});assert.equal(alerts.length,1);assert.deepEqual(alerts[0][2],{intakeOrderId:Number(children[1].id),severity:"critical"});assert.equal((await f.facts(f.job.id)).children[1].status,"QUEUED");assert.equal((await f.db.query("SELECT COUNT(*) AS n FROM sales_orders WHERE source_intake_order_id=?",[children[1].id]))[0][0].n,0);await f.db.execute("UPDATE sales_intake_orders SET external_order_id_hash=? WHERE id=?",[hash,children[1].id]);const keyId=await f.insert("sales_external_order_keys",{channel_code:children[1].channel_code,external_order_id:"Synthetic collision",external_order_id_hash:hash,source_type:"CSV",payload_hash:children[1].payload_hash,status:"SUCCEEDED",sales_order_number:"SO-202610-000001",is_order_archived:1,claimed_at:f.time.nowMs(),updated_at:f.time.nowMs()});alerts.length=0;await assert.rejects(()=>f.effect(Number(children[1].id),{logger:{error:async(...args)=>alerts.push(args)}}),{code:"SALES_SOURCE_HASH_COLLISION"});assert.equal(alerts.length,1);assert.equal((await f.facts(f.job.id)).children[1].status,"QUEUED");await f.db.execute("DELETE FROM sales_external_order_keys WHERE id=?",[keyId]);assert.equal((await f.effect(Number(children[1].id))).status,"SUCCEEDED");
});
integrationTest("TC-038 changed live running signal after Draft aborts all effects and a fresh run retains the original event",async t=>{
 const f=await intakeFixture(t),child=(await f.facts(f.job.id)).children[0],{SalesOrderService}=await import("../../src/modules/sales/SalesOrderService.js"),orders=new SalesOrderService({database:f.database,time:f.time,logger:f.logger}),create=orders.createIntakeDraftInTransaction.bind(orders);orders.createIntakeDraftInTransaction=async(...args)=>{const result=await create(...args);f.worker.scheduler.running.get("sales.importWorker").controller.abort(Error("synthetic stopped run"));return result;};await assert.rejects(()=>f.effect(Number(child.id),{orderService:orders}));
 const [[effects]]=await f.db.query("SELECT (SELECT COUNT(*) FROM sales_orders WHERE source_intake_order_id=?) AS orders,(SELECT COUNT(*) FROM inventory_reservations WHERE warehouse_id=?) AS reservations,(SELECT COUNT(*) FROM sales_external_order_keys WHERE external_order_id_hash=?) AS source_keys",[child.id,f.warehouseId,child.external_order_id_hash]);assert.deepEqual(effects,{orders:0,reservations:0,source_keys:0});assert.equal((await f.facts(f.job.id)).children[0].status,"QUEUED");assert.equal((await f.effect(Number(child.id))).status,"SUCCEEDED");assert.equal((await f.facts(f.job.id)).children[0].processing_event_id,child.processing_event_id);
});
integrationTest("TC-038 Inventory contract mismatch after real reservations rolls back the full Intake aggregate",async t=>{
 const f=await intakeFixture(t),child=(await f.facts(f.job.id)).children[0],{InventoryReservationService}=await import("../../src/modules/inventory/InventoryReservationService.js"),{SalesOrderConfirmationService}=await import("../../src/modules/sales/SalesOrderConfirmationService.js"),authorizeSalesIntake=()=>f.worker.runtime.importPrincipal(),inventory=new InventoryReservationService({database:f.database,time:f.time,logger:f.logger,authorizeSalesIntake}),confirmationService=new SalesOrderConfirmationService({database:f.database,time:f.time,logger:f.logger,config:f.app.configuration.sales,authorizeSalesIntake,inventory:{async reserveAvailableForSalesIntakeInTransaction(...args){return {...await inventory.reserveAvailableForSalesIntakeInTransaction(...args),lineCount:99};}}});await assert.rejects(()=>f.effect(Number(child.id),{confirmationService}),{code:"INVENTORY_CONTRACT_MISMATCH"});assert.equal((await f.facts(f.job.id)).children[0].status,"QUEUED");const [[effects]]=await f.db.query("SELECT (SELECT COUNT(*) FROM sales_orders WHERE source_intake_order_id=?) AS orders,(SELECT COUNT(*) FROM inventory_reservations WHERE warehouse_id=?) AS reservations,(SELECT COUNT(*) FROM inventory_operation_requests WHERE source_event_id=?) AS operations",[child.id,f.warehouseId,child.processing_event_id]);assert.deepEqual(effects,{orders:0,reservations:0,operations:0});assert.equal((await f.effect(Number(child.id))).status,"SUCCEEDED");
});
integrationTest("TC-038 original Job claim expiring after real confirmation rolls back every effect before commit",async t=>{
 const f=await intakeFixture(t),child=(await f.facts(f.job.id)).children[0],{SalesOrderConfirmationService}=await import("../../src/modules/sales/SalesOrderConfirmationService.js"),confirmationService=new SalesOrderConfirmationService({database:f.database,time:f.time,logger:f.logger,config:f.app.configuration.sales,authorizeSalesIntake:()=>f.worker.runtime.importPrincipal()}),confirm=confirmationService.confirmIntakeDraftInTransaction.bind(confirmationService);confirmationService.confirmIntakeDraftInTransaction=async(tx,request)=>{const result=await confirm(tx,request);await tx.execute("UPDATE sales_import_jobs SET lease_until=CAST(UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000 AS UNSIGNED)-1 WHERE id=?",[f.job.id]);return result;};await assert.rejects(()=>f.effect(Number(child.id),{confirmationService}),{code:"CONCURRENT_OPERATION"});const [[effects]]=await f.db.query("SELECT (SELECT COUNT(*) FROM sales_orders WHERE source_intake_order_id=?) AS orders,(SELECT COUNT(*) FROM inventory_reservations WHERE warehouse_id=?) AS reservations,(SELECT COUNT(*) FROM sales_external_order_keys WHERE external_order_id_hash=?) AS source_keys",[child.id,f.warehouseId,child.external_order_id_hash]);assert.deepEqual(effects,{orders:0,reservations:0,source_keys:0});assert.equal((await f.facts(f.job.id)).children[0].status,"QUEUED");assert.equal((await f.effect(Number(child.id))).status,"SUCCEEDED");
});
integrationTest("TC-038 server-verified synthetic Channel converts atomically and duplicate identity survives terminal replay",async t=>{
 const f=await intakeFixture(t,f=>[f.row,{...f.row,sourceOrderKey:"Channel duplicate"}]),children=(await f.facts(f.job.id)).children,ids=children.map(child=>Number(child.id)),identity={code:"SYNTHETIC",serviceId:"synthetic-adapter"};
 f.beforeParents.push(async()=>{await f.worker.scheduler.stop();for(const id of ids){await f.db.execute("DELETE FROM sales_orders WHERE source_intake_order_id=?",[id]);await f.db.execute("DELETE FROM sales_external_order_keys WHERE id=(SELECT external_order_key_id FROM sales_intake_orders WHERE id=?)",[id]);await f.db.execute("DELETE FROM sales_intake_orders WHERE id=?",[id]);}});
 for(const child of children){const payload=typeof child.safe_payload==="string"?JSON.parse(child.safe_payload):child.safe_payload;await f.db.execute("UPDATE sales_intake_orders SET source_type='CHANNEL',import_job_id=NULL,transport_idempotency_key_hash=source_order_key_hash,safe_payload=? WHERE id=?",[JSON.stringify({...payload,channelIdentity:identity}),child.id]);}
 const options={channelVerifier:async value=>value?.code===identity.code&&value.serviceId===identity.serviceId?{...identity,active:true}:null},first=await f.effect(ids[0],options),duplicate=await f.effect(ids[1],options);assert.equal(first.status,"SUCCEEDED");assert.equal(duplicate.status,"DUPLICATE");assert.equal(duplicate.salesOrderId,first.salesOrderId);assert.deepEqual(await f.effect(ids[1],options),duplicate);await assert.rejects(()=>f.effect(ids[1],{channelVerifier:async()=>null}),{code:"SALES_DEPENDENCY_UNAVAILABLE"});const [[order]]=await f.db.query("SELECT source_type,created_by,confirmed_by FROM sales_orders WHERE id=?",[first.salesOrderId]);assert.deepEqual(order,{source_type:"CHANNEL",created_by:null,confirmed_by:null});
});

async function processingFixture(t,{batchSize=2,rows}={}){
 const f=await workerFixture(t,{batchSize}),{stock}=await import("../sales/phase2/fixtures.js"),{randomUUID}=await import("node:crypto");await stock(f,4);await f.db.execute("UPDATE currencies SET status='ACTIVE' WHERE code=?",[f.currency]);const job=await f.upload(rows?await rows(f):[f.row,{...f.row,sourceOrderKey:"Peer",externalOrderId:"Peer-"+f.row.externalOrderId}]),worker=await f.registeredWorker();
 for(let attempt=0;attempt<10&&(await f.facts(job.id)).job.status!=="READY";attempt++)await worker.run();const ready=await f.facts(job.id);assert.equal(ready.job.status,"READY");await worker.scheduler.stop();await f.service.confirm({claims:f.claims,id:job.id,input:{eventId:randomUUID(),version:Number(ready.job.version)}});
 f.beforeParents.push(async()=>{await f.db.execute("DELETE FROM sales_orders WHERE source_intake_order_id IN (SELECT id FROM sales_intake_orders WHERE import_job_id=?)",[job.id]);await f.db.execute("DELETE FROM sales_external_order_keys WHERE id IN (SELECT external_order_key_id FROM sales_intake_orders WHERE import_job_id=?)",[job.id]);});return {...f,job,ready};
}
integrationTest("TC-038 registered processing worker bounds batches, isolates failed peers and publishes truthful private terminal CSV once",async t=>{
 let blockedId;const f=await processingFixture(t,{rows:async f=>{blockedId=await f.insert("customers",{customer_code:"blocked-"+f.row.externalOrderId,customer_code_key:"blocked-"+f.row.externalOrderId,legal_name:"Synthetic blocked customer",legal_name_key:"blocked-"+f.row.externalOrderId,default_currency_code:f.currency,status:"active",version:1,created_at:f.now,updated_at:f.now});return [{...f.row,quantity:"3"},{...f.row,sourceOrderKey:"Blocked",externalOrderId:"Blocked-"+f.row.externalOrderId,customerId:String(blockedId)},{...f.row,sourceOrderKey:"Peer",externalOrderId:"Peer-"+f.row.externalOrderId,quantity:"3"},{...f.row,sourceOrderKey:"Invalid",externalOrderId:"Invalid-"+f.row.externalOrderId,quantity:"bad"}];}});await f.db.execute("UPDATE customers SET status='blocked' WHERE id=?",[blockedId]);const worker=await f.registeredWorker();await worker.run();const partial=await f.facts(f.job.id);assert.equal(partial.job.status,"PROCESSING");assert.equal(partial.children.filter(row=>["SUCCEEDED","FAILED"].includes(row.status)).length,2);assert.equal(partial.job.lease_owner,null);assert.equal(partial.job.result_file_path,"");await worker.run();await worker.scheduler.stop();const final=await f.facts(f.job.id);assert.equal(final.job.status,"PARTIAL_SUCCESS");assert.deepEqual([Number(final.job.success_count),Number(final.job.failed_count),Number(final.job.invalid_count),Number(final.job.duplicate_count),Number(final.job.source_order_count)],[2,1,1,0,4]);assert.equal(final.job.lease_owner,null);assert.deepEqual(final.children.map(row=>[row.id,row.processing_event_id]),f.ready.children.map(row=>[row.id,row.processing_event_id]));
 const {parse}=await import("csv-parse/sync"),download=await f.service.resolveResultDownload({claims:f.claims,id:f.job.id});let csv="";for await(const chunk of download.stream)csv+=chunk;const rows=parse(csv,{bom:true});assert.equal(rows.length,5);assert.deepEqual(rows.slice(1).map(row=>row[3]).sort(),["FAILED","INVALID","SUCCEEDED","SUCCEEDED"]);const [[audits]]=await f.db.query("SELECT COUNT(*) AS n FROM sales_audit_logs WHERE target_type='IMPORT_JOB' AND target_id=? AND action='sales_import.completed'",[f.job.id]);assert.equal(Number(audits.n),1);assert.equal(worker.scheduler.stats.get("sales.importWorker").failures,0);
});
integrationTest("TC-038 processing publication refuses0755 root and batch without marking a completed Job",async t=>{
 for(const level of ["root","batch"])await t.test(level,async t=>{
  const f=await processingFixture(t),{chmod,lstat,readdir}=await import("node:fs/promises"),path=(await import("node:path")).default,directory=level==="root"?f.root:path.join(f.root,f.job.batchNumber);f.beforeParents.push(()=>chmod(directory,0o700));await chmod(directory,0o755);const worker=await f.registeredWorker();await worker.run();await worker.scheduler.stop();const failed=await f.facts(f.job.id);assert.equal(worker.scheduler.stats.get("sales.importWorker").failures,1);assert.equal(failed.job.status,"PROCESSING");assert.equal(failed.job.result_file_path,"");assert.ok(failed.children.every(row=>row.status==="SUCCEEDED"));assert.equal((await f.db.query("SELECT COUNT(*) AS n FROM sales_audit_logs WHERE target_type='IMPORT_JOB' AND target_id=? AND action='sales_import.completed'",[f.job.id]))[0][0].n,0);
  await chmod(directory,0o700);const next=await f.registeredWorker();await next.run();await next.scheduler.stop();const final=await f.facts(f.job.id);assert.equal(final.job.status,"COMPLETED");assert.equal((await lstat(path.join(f.root,final.job.result_file_path))).mode&0o777,0o600);assert.deepEqual(final.children.map(row=>[row.id,row.processing_event_id,row.sales_order_id]),failed.children.map(row=>[row.id,row.processing_event_id,row.sales_order_id]));assert.ok(!(await readdir(path.join(f.root,f.job.batchNumber))).some(name=>name.endsWith(".tmp")));const download=await f.service.resolveResultDownload({claims:f.claims,id:f.job.id});let bytes=0;for await(const chunk of download.stream)bytes+=Buffer.byteLength(chunk);assert.ok(bytes>0);
 });
});
integrationTest("TC-038 technical processing deferral preserves original event and lets its peer succeed before retry",async t=>{
 const f=await processingFixture(t),worker=await f.registeredWorker(),{SalesIntakeService}=await import("../../src/modules/sales/SalesIntakeService.js"),first=f.ready.children[0],service=new SalesIntakeService({database:f.database,time:f.time,logger:f.logger,config:f.app.configuration.sales,authorizeSalesImport:()=>worker.runtime.importPrincipal()});worker.runtime.importer.workerOptions.intakeService={async process(request){if(request.intakeOrderId===Number(first.id))throw Object.assign(Error("synthetic dependency unavailable"),{code:"SALES_DEPENDENCY_UNAVAILABLE"});return service.process(request);}};
 await worker.run();await worker.scheduler.stop();const deferred=await f.facts(f.job.id);assert.equal(deferred.job.status,"PROCESSING");assert.equal(deferred.job.lease_owner,null);assert.deepEqual(deferred.children.map(row=>row.status),["PROCESSING","SUCCEEDED"]);assert.ok(Number(deferred.children[0].next_attempt_at)>Number(deferred.children[0].last_attempt_at));assert.equal(deferred.children[0].sales_order_id,null);assert.equal(deferred.errors.length,0);assert.equal(worker.scheduler.stats.get("sales.importWorker").failures,0);
 await f.db.execute("UPDATE sales_intake_orders SET next_attempt_at=CAST(UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000 AS UNSIGNED)-1 WHERE id=?",[first.id]);const next=await f.registeredWorker();await next.run();await next.scheduler.stop();const final=await f.facts(f.job.id);assert.equal(final.job.status,"COMPLETED");assert.ok(final.children.every(row=>row.status==="SUCCEEDED"));assert.deepEqual(final.children.map(row=>[row.id,row.processing_event_id]),f.ready.children.map(row=>[row.id,row.processing_event_id]));assert.equal(Number(final.children[0].attempt_count),2);assert.equal(Number(final.children[1].attempt_count),1);
});
integrationTest("TC-038 actual processing worker resolves lost Intake COMMIT acknowledgement from original facts",async t=>{
 const f=await processingFixture(t),worker=await f.registeredWorker(),{SalesIntakeService}=await import("../../src/modules/sales/SalesIntakeService.js");let lost=0;const database={query:f.database.query.bind(f.database),async withTransaction(work,options){const result=await f.database.withTransaction(work,options);if(result?.status==="SUCCEEDED"&&lost++===0)throw Object.assign(Error("synthetic lost acknowledgement"),{code:"DATABASE_TRANSACTION_INDETERMINATE"});return result;}};worker.runtime.importer.workerOptions.intakeService=new SalesIntakeService({database,time:f.time,logger:f.logger,config:f.app.configuration.sales,authorizeSalesImport:()=>worker.runtime.importPrincipal()});await worker.run();await worker.scheduler.stop();const final=await f.facts(f.job.id);assert.ok(lost>0);assert.equal(final.job.status,"COMPLETED");assert.equal(worker.scheduler.stats.get("sales.importWorker").failures,0);assert.deepEqual(final.children.map(row=>row.processing_event_id),f.ready.children.map(row=>row.processing_event_id));const [[counts]]=await f.db.query("SELECT (SELECT COUNT(*) FROM sales_orders WHERE source_intake_order_id IN (SELECT id FROM sales_intake_orders WHERE import_job_id=?)) AS orders,(SELECT COUNT(*) FROM sales_operation_requests WHERE command_type='PROCESS_INTAKE' AND event_id IN (SELECT processing_event_id FROM sales_intake_orders WHERE import_job_id=?)) AS operations",[f.job.id,f.job.id]);assert.deepEqual(counts,{orders:2,operations:2});
});
integrationTest("TC-038 completed audit failure after atomic result rename remains recoverable without repeating source effects",async t=>{
 const f=await processingFixture(t),worker=await f.registeredWorker(),{readFile,readdir}=await import("node:fs/promises"),path=(await import("node:path")).default;worker.runtime.importer.workerOptions.audit={record(tx,data){if(data.action==="sales_import.completed")throw Error("synthetic required completion audit unavailable");return f.service.audit.record(tx,data);}};await worker.run();await worker.scheduler.stop();const pending=await f.facts(f.job.id),file=path.join(f.root,f.job.batchNumber,"result.csv"),bytes=await readFile(file);assert.equal(worker.scheduler.stats.get("sales.importWorker").failures,1);assert.equal(pending.job.status,"PROCESSING");assert.equal(pending.job.result_file_path,"");assert.equal(pending.job.lease_owner,null);assert.ok(pending.children.every(row=>row.status==="SUCCEEDED"));await assert.rejects(()=>f.service.resolveResultDownload({claims:f.claims,id:f.job.id}),{code:"SALES_STATE_CONFLICT"});
 const next=await f.registeredWorker();await next.run();await next.scheduler.stop();const final=await f.facts(f.job.id);assert.equal(final.job.status,"COMPLETED");assert.deepEqual(final.children.map(row=>[row.id,row.processing_event_id,row.sales_order_id,row.updated_at]),pending.children.map(row=>[row.id,row.processing_event_id,row.sales_order_id,row.updated_at]));assert.deepEqual(await readFile(file),bytes);assert.ok(!(await readdir(path.dirname(file))).some(name=>name.endsWith(".tmp")));assert.equal((await f.db.query("SELECT COUNT(*) AS n FROM sales_audit_logs WHERE target_type='IMPORT_JOB' AND target_id=? AND action='sales_import.completed'",[f.job.id]))[0][0].n,1);
});
integrationTest("TC-038 actual SIGKILL and explicit owned lease expiry recover original sources and partial result temporary",async t=>{
 for(const mode of ["after-commit","result-write"])await t.test(mode,async t=>{
  const f=await processingFixture(t,{batchSize:3,rows:f=>[f.row,{...f.row,sourceOrderKey:"Second",externalOrderId:"Second-"+f.row.externalOrderId},{...f.row,sourceOrderKey:"Third",externalOrderId:"Third-"+f.row.externalOrderId}]}),{fork}=await import("node:child_process"),{once}=await import("node:events"),{readdir,lstat}=await import("node:fs/promises"),path=(await import("node:path")).default,child=fork(new URL("../sales/phase3/processingCrashChild.js",import.meta.url),[mode,f.root,f.tempRoot],{execArgv:[],silent:true});child.stdout.resume();child.stderr.resume();f.beforeParents.push(async()=>{if(child.exitCode===null&&child.signalCode===null){const exited=once(child,"exit");child.kill("SIGKILL");await exited;}});
  await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(Error("Owned crash child did not reach the requested window")),15000),finish=(error)=>{clearTimeout(timeout);child.off("message",message);child.off("exit",exit);child.off("error",finish);error?reject(error):resolve();},message=value=>value?.event===(mode==="after-commit"?"source-committed":"result-writing")&&finish(),exit=()=>finish(Error("Owned crash child exited before its window"));child.on("message",message);child.once("exit",exit);child.once("error",finish);});
  const exited=once(child,"exit");assert.equal(child.kill("SIGKILL"),true);const [code,killed]=await exited;assert.equal(code,null);assert.equal(killed,"SIGKILL");const stopped=await f.facts(f.job.id),directory=path.join(f.root,f.job.batchNumber);assert.equal(stopped.job.status,"PROCESSING");assert.match(stopped.job.lease_owner,/^[a-f0-9-]{36}$/u);assert.equal(stopped.children.filter(row=>row.status==="SUCCEEDED").length,mode==="after-commit"?1:3);if(mode==="result-write"){const temporary=(await readdir(directory)).filter(name=>/^result-[a-f0-9-]{36}\.tmp$/u.test(name));assert.equal(temporary.length,1);assert.equal((await lstat(path.join(directory,temporary[0]))).mode&0o777,0o600);}
  // Advance only this synthetic Job and fixed runtime lease, rather than changing the real60s lease policy.
  await f.db.execute("UPDATE fr_job_leases SET expires_at=UNIX_TIMESTAMP()-1 WHERE job_name='sales.importWorker'");await f.db.execute("UPDATE sales_import_jobs SET lease_until=CAST(UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000 AS UNSIGNED)-1 WHERE id=?",[f.job.id]);const next=await f.registeredWorker();await next.run();await next.scheduler.stop();const final=await f.facts(f.job.id);assert.equal(final.job.status,"COMPLETED");assert.equal(final.job.lease_owner,null);assert.equal(next.scheduler.stats.get("sales.importWorker").failures,0);assert.deepEqual(final.children.map(row=>[row.id,row.processing_event_id]),f.ready.children.map(row=>[row.id,row.processing_event_id]));for(const original of stopped.children.filter(row=>row.status==="SUCCEEDED")){const recovered=final.children.find(row=>row.id===original.id);assert.equal(recovered.sales_order_id,original.sales_order_id);assert.equal(Number(recovered.updated_at),Number(original.updated_at));}assert.equal(final.children.filter(row=>row.status==="SUCCEEDED").length,3);assert.ok(!(await readdir(directory)).some(name=>name.endsWith(".tmp")));const [[counts]]=await f.db.query("SELECT (SELECT COUNT(*) FROM sales_orders WHERE source_intake_order_id IN (SELECT id FROM sales_intake_orders WHERE import_job_id=?)) AS orders,(SELECT COUNT(*) FROM sales_operation_requests WHERE command_type='PROCESS_INTAKE' AND event_id IN (SELECT processing_event_id FROM sales_intake_orders WHERE import_job_id=?)) AS operations,(SELECT COUNT(*) FROM sales_audit_logs WHERE target_type='IMPORT_JOB' AND target_id=? AND action='sales_import.completed') AS audits",[f.job.id,f.job.id,f.job.id]);assert.deepEqual(counts,{orders:3,operations:3,audits:1});
 });
});
integrationTest("TC-038 processing summary accounts for duplicates discovered after confirmation from terminal child facts",async t=>{
 const f=await processingFixture(t,{batchSize:3,rows:f=>[{...f.row,unitSellingPrice:"1"},{...f.row,sourceOrderKey:"Duplicate",unitSellingPrice:"1"},{...f.row,sourceOrderKey:"Conflict",quantity:"2",unitSellingPrice:"1"}]}),worker=await f.registeredWorker();await worker.run();await worker.scheduler.stop();const final=await f.facts(f.job.id);assert.equal(final.job.status,"COMPLETED");assert.deepEqual([Number(final.job.valid_count),Number(final.job.success_count),Number(final.job.duplicate_count),Number(final.job.warning_count)],[1,1,2,1]);assert.deepEqual(final.children.map(row=>row.status),["SUCCEEDED","DUPLICATE","DUPLICATE"]);assert.equal(new Set(final.children.map(row=>row.sales_order_id)).size,1);assert.deepEqual(final.children.map(row=>row.processing_event_id),f.ready.children.map(row=>row.processing_event_id));assert.equal(worker.scheduler.stats.get("sales.importWorker").failures,0);
});
integrationTest("TC-038 processing revocation between source commits halts remaining effects and cached completed facts until fresh authority returns",async t=>{
 const f=await processingFixture(t),worker=await f.registeredWorker(),{SalesIntakeService}=await import("../../src/modules/sales/SalesIntakeService.js"),service=new SalesIntakeService({database:f.database,time:f.time,logger:f.logger,config:f.app.configuration.sales,authorizeSalesImport:()=>worker.runtime.importPrincipal()});let first=true;worker.runtime.importer.workerOptions.intakeService={async process(request){const result=await service.process(request);if(first){first=false;await f.db.execute("DELETE rp FROM role_permissions rp JOIN permissions p ON p.id=rp.permission_id WHERE rp.role_id=? AND p.name='sales.import'",[f.roleId]);}return result;}};await worker.run();await worker.scheduler.stop();const revoked=await f.facts(f.job.id);assert.equal(worker.scheduler.stats.get("sales.importWorker").failures,1);assert.deepEqual(revoked.children.map(row=>row.status),["SUCCEEDED","PROCESSING"]);assert.equal(revoked.job.status,"PROCESSING");assert.equal(revoked.job.lease_owner,null);assert.equal(revoked.children[1].sales_order_id,null);
 const next=await f.registeredWorker();await next.run();assert.deepEqual((await f.facts(f.job.id)).children.map(row=>[row.status,row.sales_order_id]),revoked.children.map(row=>[row.status,row.sales_order_id]));await f.db.execute("INSERT INTO role_permissions (role_id,permission_id) SELECT ?,id FROM permissions WHERE name='sales.import'",[f.roleId]);await next.run();await next.scheduler.stop();const final=await f.facts(f.job.id);assert.equal(final.job.status,"COMPLETED");assert.deepEqual(final.children.map(row=>row.processing_event_id),f.ready.children.map(row=>row.processing_event_id));assert.equal(final.children[0].sales_order_id,revoked.children[0].sales_order_id);assert.equal(Number(final.children[0].updated_at),Number(revoked.children[0].updated_at));
});
integrationTest("TC-038 actual Scheduler stop preserves the claimed remaining sources and fresh expired-claim recovery",async t=>{
 const f=await processingFixture(t),worker=await f.registeredWorker(),{SalesIntakeService}=await import("../../src/modules/sales/SalesIntakeService.js"),service=new SalesIntakeService({database:f.database,time:f.time,logger:f.logger,config:f.app.configuration.sales,authorizeSalesImport:()=>worker.runtime.importPrincipal()}),entered=Promise.withResolvers();let first=true;worker.runtime.importer.workerOptions.intakeService={async process(request){const result=await service.process(request);if(first){first=false;entered.resolve();await new Promise((resolve,reject)=>{request.signal.addEventListener("abort",()=>reject(request.signal.reason),{once:true});});}return result;}};const execution=worker.run();await Promise.race([entered.promise,execution.then(()=>assert.fail("worker did not reach the committed source"))]);assert.deepEqual(await worker.scheduler.stop({timeoutMs:1000}),{stopped:true,drained:true});await execution;const stopped=await f.facts(f.job.id);assert.equal(stopped.job.status,"PROCESSING");assert.match(stopped.job.lease_owner,/^[a-f0-9-]{36}$/u);assert.deepEqual(stopped.children.map(row=>row.status),["SUCCEEDED","PROCESSING"]);assert.equal(worker.runtime.importPrincipal(),null);
 await f.db.execute("UPDATE sales_import_jobs SET lease_until=CAST(UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000 AS UNSIGNED)-1 WHERE id=?",[f.job.id]);const next=await f.registeredWorker();await next.run();await next.scheduler.stop();const final=await f.facts(f.job.id);assert.equal(final.job.status,"COMPLETED");assert.deepEqual(final.children.map(row=>row.processing_event_id),f.ready.children.map(row=>row.processing_event_id));assert.equal(final.children[0].sales_order_id,stopped.children[0].sales_order_id);assert.equal(Number(final.children[0].updated_at),Number(stopped.children[0].updated_at));assert.equal(next.scheduler.stats.get("sales.importWorker").failures,0);
});
async function channelFixture(t){
 const f=await workerFixture(t,{batchSize:3}),{stock}=await import("../sales/phase2/fixtures.js"),{SalesIntakeService}=await import("../../src/modules/sales/SalesIntakeService.js"),{readFile}=await import("node:fs/promises");await stock(f,4);await f.db.execute("UPDATE currencies SET status='ACTIVE' WHERE code=?",[f.currency]);const fixture=JSON.parse(await readFile(new URL("../sales/phase3/channel-v1.fixture.json",import.meta.url),"utf8")),contextA=Object.freeze({transport:"synthetic-A"}),contextB=Object.freeze({transport:"synthetic-B"}),identities=[{code:"SYNTHETIC",serviceId:"synthetic-adapter"},{code:"SYNTHETIC_ALT",serviceId:"synthetic-adapter-B"}],active=new Set(identities.map(value=>value.code)),owned=new Set();
 const channelVerifier=async(value,{purpose}={})=>{const identity=purpose==="SUBMIT"?value===contextA?identities[0]:value===contextB?identities[1]:null:purpose==="PROCESS"?identities.find(identity=>identity.code===value?.code&&identity.serviceId===value?.serviceId):null;return identity&&active.has(identity.code)?{...identity,active:true}:null;},makeService=options=>new SalesIntakeService({database:f.database,time:f.time,logger:f.logger,config:f.app.configuration.sales,channelVerifier,...options}),input=(suffix="A")=>{const body=structuredClone(fixture);body.requestId="request-"+suffix;body.idempotencyKey=f.row.externalOrderId+"-key-"+suffix;body.order={...body.order,externalOrderId:f.row.externalOrderId+"-external-"+suffix,customerId:f.customerId,fulfillmentWarehouseCode:f.row.warehouseCode,currencyCode:f.currency,lines:[{skuCode:f.row.skuCode,salesUomCode:f.row.salesUomCode,quantity:"1",unitSellingPrice:"1",lineNote:""}]};owned.add(body.order.externalOrderId);return body;};
 f.beforeParents.push(async()=>{if(!owned.size)return;const [rows]=await f.db.query(`SELECT id,processing_event_id,external_order_key_id FROM sales_intake_orders WHERE source_type='CHANNEL' AND external_order_id IN (${[...owned].map(()=>"?").join(",")})`,[...owned]);for(const row of rows){await f.db.execute("DELETE FROM sales_orders WHERE source_intake_order_id=?",[row.id]);await f.db.execute("DELETE FROM sales_operation_requests WHERE event_id=?",[row.processing_event_id]);await f.db.execute("DELETE FROM sales_intake_orders WHERE id=?",[row.id]);if(row.external_order_key_id)await f.db.execute("DELETE FROM sales_external_order_keys WHERE id=?",[row.external_order_key_id]);}});
 return {...f,contextA,contextB,identities,active,channelVerifier,makeService,input};
}
integrationTest("TC-040 real canonical Channel admission uses trusted context, same-key immutable original event and actual shared worker",async t=>{
 const f=await channelFixture(t),service=f.makeService(),input=f.input();input.channelIdentity=f.identities[1];const first=await service.submit(input,{context:f.contextA});assert.equal(first.outcome,"ACCEPTED");assert.equal(first.statusUrl,null);const [[before]]=await f.db.query("SELECT * FROM sales_intake_orders WHERE id=?",[first.intakeOrderId]);assert.equal(before.channel_code,"SYNTHETIC");assert.equal(before.status,"QUEUED");assert.equal(before.import_job_id,null);assert.equal((await f.db.query("SELECT COUNT(*) AS n FROM sales_orders WHERE source_intake_order_id=?",[before.id]))[0][0].n,0);assert.deepEqual(await service.submit({...input,requestId:"another-request"},{context:f.contextA}),first);
 const conflict=structuredClone(input);conflict.order.lines[0].quantity="2";assert.deepEqual(await service.submit(conflict,{context:f.contextA}),{outcome:"VALIDATION_FAILED",intakeOrderId:first.intakeOrderId,errors:[{code:"IDEMPOTENCY_CONFLICT",field:"idempotencyKey"}]});const denied=await service.submit(input,{context:{...f.identities[0],authenticated:true}});assert.equal(denied.outcome,"TECHNICAL_RETRY");assert.equal((await f.db.query("SELECT COUNT(*) AS n FROM sales_intake_orders WHERE channel_code=? AND transport_idempotency_key_hash=?",["SYNTHETIC",before.transport_idempotency_key_hash]))[0][0].n,1);
 const worker=await f.registeredWorker();worker.runtime.importer.workerOptions.channelVerifier=f.channelVerifier;await worker.run();await worker.scheduler.stop();const duplicate=await service.submit(input,{context:f.contextA});assert.equal(duplicate.outcome,"DUPLICATE");assert.equal(duplicate.isArchived,false);const [[processed]]=await f.db.query("SELECT status,processing_event_id,sales_order_id FROM sales_intake_orders WHERE id=?",[before.id]);assert.equal(processed.status,"SUCCEEDED");assert.equal(processed.processing_event_id,before.processing_event_id);assert.equal(Number(processed.sales_order_id),duplicate.salesOrderId);const other=await service.submit(input,{context:f.contextB});assert.equal(other.outcome,"ACCEPTED");assert.notEqual(other.intakeOrderId,first.intakeOrderId);const next=await f.registeredWorker();next.runtime.importer.workerOptions.channelVerifier=f.channelVerifier;await next.run();await next.scheduler.stop();const separated=await service.submit(input,{context:f.contextB});assert.equal(separated.outcome,"DUPLICATE");assert.notEqual(separated.salesOrderId,duplicate.salesOrderId);assert.equal(next.scheduler.stats.get("sales.importWorker").failures,0);
});
integrationTest("TC-040 Channel business validation persists safe exception while dependency failure and lost acknowledgement retry original admission",async t=>{
 const f=await channelFixture(t),service=f.makeService(),invalid=f.input("invalid");invalid.order.customerId=Number.MAX_SAFE_INTEGER;const failed=await service.submit(invalid,{context:f.contextA});assert.equal(failed.outcome,"VALIDATION_FAILED");assert.ok(failed.intakeOrderId>0);assert.ok(failed.errors.some(error=>error.code==="CUSTOMER_NOT_SALEABLE"));assert.deepEqual(await service.submit(invalid,{context:f.contextA}),failed);const retryInput=f.input("retry"),unavailable=f.makeService({customerProvider:{getSalesPrecheckSnapshotsInTransaction(){throw Error("private dependency SQL stack");}}}),retry=await unavailable.submit(retryInput,{context:f.contextA});assert.deepEqual(retry,{outcome:"TECHNICAL_RETRY",requestId:retryInput.requestId,retryAfterSeconds:2});assert.equal((await f.db.query("SELECT COUNT(*) AS n FROM sales_intake_orders WHERE external_order_id=?",[retryInput.order.externalOrderId]))[0][0].n,0);
 let lost=true;const database={query:f.database.query.bind(f.database),async withTransaction(work,options){const result=await f.database.withTransaction(work,options);if(lost&&result?.outcome==="ACCEPTED"){lost=false;throw Object.assign(Error("synthetic lost admission acknowledgement"),{code:"DATABASE_TRANSACTION_INDETERMINATE"});}return result;}},unknown=f.makeService({database});assert.equal((await unknown.submit(retryInput,{context:f.contextA})).outcome,"TECHNICAL_RETRY");const accepted=await service.submit(retryInput,{context:f.contextA});assert.equal(accepted.outcome,"ACCEPTED");assert.equal((await f.db.query("SELECT COUNT(*) AS n FROM sales_intake_orders WHERE external_order_id=?",[retryInput.order.externalOrderId]))[0][0].n,1);assert.doesNotMatch(JSON.stringify([failed,retry,accepted]),/private|SQL|stack|payload_hash|safe_payload/);
 f.active.delete("SYNTHETIC");const worker=await f.registeredWorker();worker.runtime.importer.workerOptions.channelVerifier=f.channelVerifier;await worker.run();await worker.scheduler.stop();const [[pending]]=await f.db.query("SELECT status,sales_order_id FROM sales_intake_orders WHERE id=?",[accepted.intakeOrderId]);assert.equal(pending.status,"PROCESSING");assert.equal(pending.sales_order_id,null);assert.equal((await service.submit(retryInput,{context:f.contextA})).outcome,"TECHNICAL_RETRY");f.active.add("SYNTHETIC");await f.db.execute("UPDATE sales_intake_orders SET next_attempt_at=CAST(UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000 AS UNSIGNED)-1 WHERE id=?",[accepted.intakeOrderId]);const next=await f.registeredWorker();next.runtime.importer.workerOptions.channelVerifier=f.channelVerifier;await next.run();await next.scheduler.stop();assert.equal((await service.submit(retryInput,{context:f.contextA})).outcome,"DUPLICATE");
});
integrationTest("TC-040 raw canonical source above128KiB admits its small merged document with truthful normalized line count",async t=>{
 const f=await channelFixture(t),input=f.input("merged"),service=f.makeService();input.order.lines=Array.from({length:100},()=>({...input.order.lines[0],lineNote:"註".repeat(500)}));assert.ok(Buffer.byteLength(JSON.stringify(input))>131072);const accepted=await service.submit(input,{context:f.contextA});assert.equal(accepted.outcome,"ACCEPTED");const [[intake]]=await f.db.query("SELECT line_count,safe_payload FROM sales_intake_orders WHERE id=?",[accepted.intakeOrderId]);assert.equal(Number(intake.line_count),1);const payload=typeof intake.safe_payload==="string"?JSON.parse(intake.safe_payload):intake.safe_payload;assert.equal(payload.document.lines.length,1);assert.equal(payload.document.lines[0].quantity,"100.000000");const worker=await f.registeredWorker();worker.runtime.importer.workerOptions.channelVerifier=f.channelVerifier;await worker.run();await worker.scheduler.stop();const result=await service.submit(input,{context:f.contextA});assert.equal(result.outcome,"DUPLICATE");assert.equal(worker.scheduler.stats.get("sales.importWorker").failures,0);const [[count]]=await f.db.query("SELECT COUNT(*) AS n FROM sales_order_lines WHERE sales_order_id=?",[result.salesOrderId]);assert.equal(count.n,1);
});
integrationTest("TC-040 concurrent Channel admission converges and archived duplicate routing needs no mutable masters",async t=>{
 const f=await channelFixture(t),service=f.makeService(),input=f.input("concurrent"),results=await Promise.all(Array.from({length:12},()=>service.submit(input,{context:f.contextA}))),accepted=results.find(result=>result.outcome==="ACCEPTED");assert.ok(accepted);for(const result of results)assert.ok(["ACCEPTED","TECHNICAL_RETRY"].includes(result.outcome));for(let index=0;index<results.length;index++)assert.deepEqual(await service.submit(input,{context:f.contextA}),accepted);assert.equal((await f.db.query("SELECT COUNT(*) AS n FROM sales_intake_orders WHERE external_order_id=?",[input.order.externalOrderId]))[0][0].n,1);
 const archived=f.input("archived"),{salesSourceHash}=await import("../../src/modules/sales/salesImportPrecheck.js");await f.insert("sales_external_order_keys",{channel_code:"SYNTHETIC",external_order_id:archived.order.externalOrderId,external_order_id_hash:salesSourceHash(archived.order.externalOrderId),source_type:"CHANNEL",payload_hash:"0".repeat(64),status:"SUCCEEDED",sales_order_id:null,sales_order_number:"SO-202610-000001",is_order_archived:1,claimed_at:f.now,updated_at:f.now});archived.order.customerId=Number.MAX_SAFE_INTEGER;archived.order.lines[0].skuCode="SYNTHETIC_MISSING";const duplicate=await service.submit(archived,{context:f.contextA});assert.deepEqual(duplicate,{outcome:"DUPLICATE",salesOrderId:null,salesOrderNumber:"SO-202610-000001",isArchived:true});assert.deepEqual(await service.submit(archived,{context:f.contextA}),duplicate);
});
integrationTest("TC-040 full stored JSON bytecount over128KiB creates a bounded validation exception rather than endless technical retries",async t=>{
 const f=await channelFixture(t),input=f.input("stored-cap"),database={query:f.database.query.bind(f.database),withTransaction:(work,options)=>f.database.withTransaction(tx=>work({execute:tx.execute.bind(tx),async query(sql,...args){const result=await tx.query(sql,...args);if(sql==="SELECT LENGTH(CAST(CAST(? AS JSON) AS CHAR CHARSET utf8mb4)) AS bytes"){assert.ok(JSON.parse(args[0][0]).channelIdentity);return [[{bytes:131073}]];}return result;}}),options)},service=f.makeService({database}),result=await service.submit(input,{context:f.contextA});assert.equal(result.outcome,"VALIDATION_FAILED");assert.deepEqual(result.errors,[{code:"SALES_IMPORT_ORDER_INVALID",field:"payload"}]);assert.deepEqual(await f.makeService().submit(input,{context:f.contextA}),result);const [[row]]=await f.db.query("SELECT status,LENGTH(CAST(safe_payload AS CHAR CHARSET utf8mb4)) AS bytes,sales_order_id FROM sales_intake_orders WHERE id=?",[result.intakeOrderId]);assert.equal(row.status,"INVALID");assert.ok(Number(row.bytes)<131072);assert.equal(row.sales_order_id,null);
});
integrationTest("TC-041 actual handler registry and HTTP reject public Channel intake and status routes",async t=>{
 const f=await workerFixture(t),{createHandlerRegistry}=await import("../../src/framework/api/handlerRegistry.js"),{resolveApiDefinitions}=await import("../../src/framework/api/apiDefinitionResolver.js"),handlers=await createHandlerRegistry({services:f.app.services}),routes=resolveApiDefinitions(handlers,f.app.configuration.api.defaults);assert.ok(routes.length>0);assert.ok(routes.every(route=>!/^\/api\/v1\/sales-(?:channels|intake-orders)(?:\/|$)/u.test(route.path)));const {url}=await f.app.start(),token=await f.app.services.require("jwt").issue({roles:f.claims.claimedRoles,permissions:f.claims.claimedPermissions},{subject:String(f.userId),version:await f.app.services.require("tokenRevocation").currentVersion(String(f.userId)),authTime:Math.floor(f.now/1000)});f.beforeParents.push(()=>f.db.execute("DELETE FROM fr_token_versions WHERE subject=?",[String(f.userId)]));for(const path of ["/api/v1/sales-channels/intake","/api/v1/sales-intake-orders"]){for(const authenticated of [false,true]){const response=await fetch(new URL(path,url),{method:"POST",headers:{"Content-Type":"application/json",...(authenticated?{Authorization:`Bearer ${token}`}:{})},body:"{}"});assert.equal(response.status,401);assert.equal((await response.json()).error.code,"Unauthorized Access");}}
});
