import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import test from "node:test";
import { setup,stock } from "../sales/phase2/fixtures.js";
import { SalesOrderLifecycleService } from "../../src/modules/sales/SalesOrderLifecycleService.js";
import { InventoryReservationService } from "../../src/modules/inventory/InventoryReservationService.js";
const it=process.env.DB_INTEGRATION_TESTS==="1"?test:test.skip;
const reason="客戶要求調整訂單";
const command=f=>({claims:f.claims,id:f.request.id,input:{eventId:randomUUID(),version:3,reason}});
const lifecycle=(f,options)=>new SalesOrderLifecycleService({...f,services:f.app.services,...options});
async function confirm(f,atp=4){await stock(f,atp);const s=f.service(),intent=await s.startConfirmation(f.request);return s.completeConfirmation({eventId:intent.eventId,claims:f.claims,leaseOwner:intent.leaseOwner});}
async function facts(f){const [[order]]=await f.db.query("SELECT status,version,confirmation_event_id,has_backorder FROM sales_orders WHERE id=?",[f.request.id]);const [lines]=await f.db.query("SELECT reserved_outstanding_base_quantity,backordered_base_quantity,fulfilled_base_quantity,cancelled_base_quantity FROM sales_order_lines WHERE sales_order_id=?",[f.request.id]);const [mappings]=await f.db.query("SELECT r.* FROM sales_order_line_reservations r JOIN sales_order_lines l ON l.id=r.sales_order_line_id WHERE l.sales_order_id=?",[f.request.id]);const [reservations]=await f.db.query("SELECT id,version,status,original_quantity,outstanding_quantity,released_quantity FROM inventory_reservations WHERE warehouse_id=?",[f.warehouseId]);const [queue]=await f.db.query("SELECT status,outstanding_base_quantity FROM sales_backorder_entries WHERE sales_order_id=?",[f.request.id]);return {order,lines,mappings,reservations,queue};}
it("TC-029 withdraw releases partial/full/zero commitments, re-fetches current Draft masters and replays once",async t=>{
 for(const atp of [4,10,0])await t.test(`ATP ${atp}`,async child=>{const f=await setup(child);await confirm(f,atp);await f.db.execute("UPDATE customers SET legal_name='Current customer' WHERE id=?",[f.customerId]);await f.db.execute("UPDATE item_skus SET sku_name='Current SKU' WHERE id=?",[f.skuId]);const req=command(f),s=lifecycle(f),r=await s.withdrawConfirmation(req);assert.equal(r.salesOrder.status,"DRAFT");assert.equal(r.salesOrder.version,4);assert.equal(r.salesOrder.customerName,"Current customer");assert.equal(r.salesOrder.lines[0].skuName,"Current SKU");assert.deepEqual(r.salesOrder.lines.map(l=>[l.reservedBaseQuantity,l.backorderedBaseQuantity,l.fulfilledBaseQuantity,l.cancelledBaseQuantity]),[["0","0","0","0"]]);assert.deepEqual((await s.withdrawConfirmation(req)).operation,r.operation);const state=await facts(f);assert.equal(state.order.confirmation_event_id,null);assert.equal(state.mappings.length,0);assert.equal(state.queue.length,0);assert.equal(state.reservations.length,atp?1:0);assert.ok(state.reservations.every(r=>r.status==="RELEASED"&&r.outstanding_quantity===0));const [[history]]=await f.db.query("SELECT COUNT(*) AS n,MAX(reason) AS reason FROM sales_order_status_history WHERE sales_order_id=? AND action='withdrawn'",[f.request.id]);assert.equal(history.n,1);assert.equal(history.reason,reason);const [[audit]]=await f.db.query("SELECT details FROM sales_audit_logs WHERE event_id=?",[req.input.eventId]);assert.match(audit.details.commitmentHash,/^[a-f0-9]{64}$/u);});
});
it("TC-030 Draft cancel never calls Inventory/Fulfillment; Confirmed cancel moves reserve+backorder to cancelled",async t=>{
 const f=await setup(t),s=lifecycle(f,{inventory:{releaseSalesBatchInTransaction(){throw Error("Draft must not release");}},fulfillmentGuard:{assertAllowed(){throw Error("Draft must not guard");}}});const req=command(f);req.input.version=1;const result=await s.cancel(req);assert.equal(result.salesOrder.status,"CANCELLED");assert.equal(result.salesOrder.lines[0].cancelledBaseQuantity,"10");
});
it("TC-030 Confirmed cancel moves reserve+backorder to cancelled atomically",async t=>{
 const g=await setup(t);await confirm(g);const r=await lifecycle(g).cancel(command(g));assert.equal(r.salesOrder.status,"CANCELLED");assert.equal(r.salesOrder.lines[0].cancelledBaseQuantity,"10");assert.equal(r.salesOrder.hasBackorder,false);const state=await facts(g);assert.equal(state.queue[0].status,"CANCELLED");assert.equal(state.queue[0].outstanding_base_quantity,0);assert.equal(state.mappings[0].released_base_quantity,4);assert.equal(state.mappings[0].outstanding_base_quantity,0);assert.equal((await g.db.query("SELECT cancel_reason FROM sales_orders WHERE id=?",[g.request.id]))[0][0].cancel_reason,reason);
});
it("TC-029 missing/tampered Inventory release or required Audit fails with actual complete native rollback",async t=>{
 const f=await setup(t);await confirm(f);const before=await facts(f),inventory=new InventoryReservationService(f);
 for(const fault of ["missing","tampered","audit"]){const opts=fault==="audit"?{audit:{record:async()=>{throw Error("Audit fault");}}}:{inventory:{releaseSalesBatchInTransaction:async(...args)=>{const r=await inventory.releaseSalesBatchInTransaction(...args);if(fault==="missing")r.results=(async function*(){yield [];})();else{const original=r.results;r.results=(async function*(){for await(const page of original)yield page.map(m=>({...m,version:m.version+1}));})();}return r;}}};const req=command(f);await assert.rejects(()=>lifecycle(f,opts).cancel(req));assert.deepEqual(await facts(f),before);assert.equal((await f.db.query("SELECT COUNT(*) AS n FROM sales_operation_requests WHERE event_id=?",[req.input.eventId]))[0][0].n,0);}
});
it("TC-029 real provider OPEN/UNKNOWN and registered unavailable block release before any Inventory call",async t=>{
 const f=await setup(t);await confirm(f);const before=await facts(f);for(const provider of [null,{assertSalesLifecycleAllowedInTransaction:async()=>({status:"OPEN"})},{assertSalesLifecycleAllowedInTransaction:async()=>({status:"UNKNOWN"})}]){const s=lifecycle(f,{services:{names:()=>["fulfillmentOpenMatter"],resolve:async()=>provider},inventory:{releaseSalesBatchInTransaction(){throw Error("release called");}}});await assert.rejects(()=>s.cancel(command(f)),{code:provider?.assertSalesLifecycleAllowedInTransaction&&((await provider.assertSalesLifecycleAllowedInTransaction()).status)==="OPEN"?"OPEN_FULFILLMENT_EXISTS":"SALES_DEPENDENCY_UNAVAILABLE"});assert.deepEqual(await facts(f),before);}
});
it("TC-030 stale version, second event, invalid states and revoked replay leave committed facts intact",async t=>{
 const f=await setup(t);await confirm(f);const before=await facts(f),s=lifecycle(f);await assert.rejects(()=>s.cancel({...command(f),input:{...command(f).input,version:2}}),{code:"VERSION_CONFLICT"});await assert.rejects(()=>s.closeRemaining(command(f)),{code:"SALES_STATE_CONFLICT"});assert.deepEqual(await facts(f),before);const req=command(f);await s.cancel(req);await assert.rejects(()=>s.withdrawConfirmation({...command(f),input:{...command(f).input,version:4}}),{code:"SALES_STATE_CONFLICT"});await f.db.execute("DELETE FROM role_permissions WHERE role_id=?",[f.roleId]);await assert.rejects(()=>s.cancel(req),{code:"PERMISSION_STALE"});
});
it("TC-030 close remaining preserves synthetic existing fulfilled history and cancels only unfulfilled demand",async t=>{
 // Fulfillment module is not installed; synthesize its previously committed projection consistently with Inventory rows.
 const f=await setup(t);await confirm(f,0);await f.db.execute("UPDATE sales_order_lines SET fulfilled_base_quantity=2,backordered_base_quantity=8 WHERE sales_order_id=?",[f.request.id]);await f.db.execute("UPDATE sales_backorder_entries SET outstanding_base_quantity=8 WHERE sales_order_id=?",[f.request.id]);await f.db.execute("UPDATE sales_orders SET status='PARTIALLY_FULFILLED' WHERE id=?",[f.request.id]);const s=lifecycle(f);await assert.rejects(()=>s.cancel(command(f)),{code:"SALES_STATE_CONFLICT"});await assert.rejects(()=>s.withdrawConfirmation(command(f)),{code:"SALES_STATE_CONFLICT"});const r=await s.closeRemaining(command(f));assert.equal(r.salesOrder.status,"CLOSED");assert.equal(r.salesOrder.lines[0].fulfilledBaseQuantity,"2");assert.equal(r.salesOrder.lines[0].cancelledBaseQuantity,"8");assert.equal(r.salesOrder.lines[0].backorderedBaseQuantity,"0");assert.equal(r.salesOrder.lines[0].orderedBaseQuantity,"10");
});
it("TC-029 installed migration history blocks absence exception; original applied history is preserved",async t=>{
 const f=await setup(t);await confirm(f);const name=`migrations/9999_create_fulfillments_${randomUUID()}.js`;let exists=true;t.after(async()=>{if(exists)await f.db.execute("DELETE FROM fr_schema_migrations WHERE name=?",[name]);});await f.db.execute("INSERT INTO fr_schema_migrations (name,applied_at) VALUES (?,CURRENT_TIMESTAMP)",[name]);try{await assert.rejects(()=>lifecycle(f).cancel(command(f)),{code:"SALES_DEPENDENCY_UNAVAILABLE"});assert.equal((await facts(f)).order.status,"CONFIRMED");}finally{await f.db.execute("DELETE FROM fr_schema_migrations WHERE name=?",[name]);exists=false;}
});
it("TC-030 close remaining releases outstanding partially consumed native reservation and preserves fulfilled quantity",async t=>{
 const f=await setup(t);await confirm(f);await f.db.execute("UPDATE inventory_reservations SET consumed_quantity=2,outstanding_quantity=2,status='PARTIALLY_CONSUMED',version=2 WHERE warehouse_id=?",[f.warehouseId]);await f.db.execute("UPDATE inventory_stock_controls SET reserved_quantity=2 WHERE warehouse_id=?",[f.warehouseId]);await f.db.execute("UPDATE sales_order_line_reservations SET consumed_base_quantity=2,outstanding_base_quantity=2,status='PARTIALLY_CONSUMED',inventory_version=2 WHERE sales_order_line_id IN (SELECT id FROM sales_order_lines WHERE sales_order_id=?)",[f.request.id]);await f.db.execute("UPDATE sales_order_lines SET reserved_outstanding_base_quantity=2,fulfilled_base_quantity=2 WHERE sales_order_id=?",[f.request.id]);await f.db.execute("UPDATE sales_orders SET status='PARTIALLY_FULFILLED' WHERE id=?",[f.request.id]);const r=await lifecycle(f).closeRemaining(command(f));assert.equal(r.salesOrder.status,"CLOSED");assert.equal(r.salesOrder.lines[0].fulfilledBaseQuantity,"2");assert.equal(r.salesOrder.lines[0].cancelledBaseQuantity,"8");const [[mapping]]=await f.db.query("SELECT consumed_base_quantity,released_base_quantity,outstanding_base_quantity FROM sales_order_line_reservations WHERE sales_order_line_id=?",[r.salesOrder.lines[0].id]);assert.deepEqual(mapping,{consumed_base_quantity:2,released_base_quantity:2,outstanding_base_quantity:0});
});
it("TC-029 real HTTP lifecycle validates strict input, terminal schema, same event replay and freshly revoked access",async t=>{
 const f=await setup(t);await confirm(f);const {url}=await f.app.start(),token=await f.app.services.require("jwt").issue({roles:f.claims.claimedRoles,permissions:f.claims.claimedPermissions},{subject:String(f.userId),version:await f.app.services.require("tokenRevocation").currentVersion(String(f.userId)),authTime:Math.floor(f.now/1000)}),req=command(f);
 const post=body=>fetch(new URL(`/api/v1/sales-orders/${f.request.id}/confirmation/withdraw`,url),{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json","Idempotency-Key":req.input.eventId},body:JSON.stringify(body)});
 for(const change of [{version:"3"},{reason:"abcd"},{actorId:f.userId}])assert.equal((await post({...req.input,...change})).status,400);
 const response=await post(req.input);const result=await response.json();assert.equal(response.status,200,JSON.stringify(result));assert.equal(result.data.salesOrder.status,"DRAFT");assert.deepEqual((await (await post(req.input)).json()).data,result.data);
 await f.db.execute("DELETE FROM role_permissions WHERE role_id=?",[f.roleId]);assert.equal((await post(req.input)).status,403);
});

it("TC-029 inactive current Customer/SKU do not invent a new withdrawal restriction; Draft names refresh before release",async t=>{
 const f=await setup(t);await confirm(f);await f.db.execute("UPDATE customers SET status='inactive',legal_name='Inactive current customer' WHERE id=?",[f.customerId]);await f.db.execute("UPDATE item_skus SET status='inactive',sku_name='Inactive current SKU' WHERE id=?",[f.skuId]);const r=await lifecycle(f).withdrawConfirmation(command(f));assert.equal(r.salesOrder.status,"DRAFT");assert.equal(r.salesOrder.customerName,"Inactive current customer");assert.equal(r.salesOrder.lines[0].skuName,"Inactive current SKU");assert.equal(r.salesOrder.lines[0].quantity,"10.000000");assert.equal(r.salesOrder.lines[0].orderedBaseQuantity,"10");
});
