import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import test from "node:test";
import { setup,stock,waitForWorkerEntry } from "../sales/phase2/fixtures.js";
import { InventoryReservationService } from "../../src/modules/inventory/InventoryReservationService.js";
import { SalesBackorderService } from "../../src/modules/sales/SalesBackorderService.js";
import { SalesOrderService,readSalesOrderDetail } from "../../src/modules/sales/SalesOrderService.js";
import { SalesOrderLifecycleService } from "../../src/modules/sales/SalesOrderLifecycleService.js";
import { SchedulerService } from "../../src/services/scheduler/SchedulerService.js";
import { SalesJobRuntimeService } from "../../src/services/salesJobs/SalesJobRuntimeService.js";
import { SalesBackorderAllocationJob } from "../../src/services/salesJobs/jobs/SalesBackorderAllocationJob.js";

const it=process.env.DB_INTEGRATION_TESTS==="1"?test:test.skip,name="sales.backorderAllocate";
async function prepareLease(f){
 const [[original]]=await f.db.query("SELECT * FROM fr_job_leases WHERE job_name=?",[name]);
 f.beforeParents.push(async()=>{if(original)await f.db.execute("UPDATE fr_job_leases SET owner=?,acquired_at=?,expires_at=? WHERE job_name=?",[original.owner,original.acquired_at,original.expires_at,name]);else await f.db.execute("DELETE FROM fr_job_leases WHERE job_name=?",[name]);});
 const owner=`sales-test-${randomUUID()}`;
 await f.db.execute("INSERT INTO fr_job_leases (job_name,owner,acquired_at,expires_at) VALUES (?,?,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()+60) ON DUPLICATE KEY UPDATE owner=VALUES(owner),acquired_at=VALUES(acquired_at),expires_at=VALUES(expires_at)",[name,owner]);
 return owner;
}
it("TC-031 Inventory worker native partial membership replay and fresh lease remain inside the caller rollback",async t=>{
 const f=await setup(t);await stock(f,4);const owner=await prepareLease(f),signal=new AbortController().signal;let enabled=true;
 // Exercise Inventory authority in a caller-owned transaction; the real Scheduler registration is tested by the job integration below.
 const s=new InventoryReservationService({...f,authorizeSalesBackorder:()=>enabled?{leaseOwner:owner,signal}:null});
 const [[line]]=await f.db.query("SELECT id FROM sales_order_lines WHERE sales_order_id=?",[f.request.id]);
 const eventId=randomUUID(),command={actor:{userId:null,serviceName:name,claimedRoles:[],claimedPermissions:[name]},source:{documentId:String(f.request.id),eventId},correlationId:eventId,payload:{warehouseId:f.warehouseId,expectedOrderVersion:1,lines:[{sourceLineId:Number(line.id),skuId:f.skuId,orderedBaseQuantity:10,minimumRemainingDays:0}]}};
 const rollback=Error("intentional caller rollback");
 await assert.rejects(()=>f.database.withTransaction(async tx=>{
  const result=await s.reserveAvailableForSalesBackorderInTransaction(tx,command);assert.equal(result.lines[0].reservedBaseQuantity,4);assert.equal(result.lines[0].uncoveredBaseQuantity,6);
  const [operations]=await tx.query("SELECT command_type,actor_user_id,actor_label FROM inventory_operation_requests WHERE source_event_id=? ORDER BY id",[eventId]);assert.deepEqual(operations.map(o=>o.command_type),["SALES_BACKORDER_BATCH_RESERVE","SALES_BACKORDER_LINE_RESERVE"]);assert.ok(operations.every(o=>o.actor_user_id===null&&o.actor_label===name));
  await tx.execute("UPDATE item_skus SET status='inactive' WHERE id=?",[f.skuId]);assert.deepEqual(await s.reserveAvailableForSalesBackorderInTransaction(tx,command),result);
  enabled=false;await assert.rejects(()=>s.reserveAvailableForSalesBackorderInTransaction(tx,command),{code:"PERMISSION_STALE"});enabled=true;
  await tx.execute("UPDATE fr_job_leases SET expires_at=UNIX_TIMESTAMP() WHERE job_name=?",[name]);await assert.rejects(()=>s.reserveAvailableForSalesBackorderInTransaction(tx,command),{code:"PERMISSION_STALE"});throw rollback;
 }),error=>(error.cause??error)===rollback);
 const [[count]]=await f.db.query("SELECT COUNT(*) AS n FROM inventory_operation_requests WHERE source_event_id=?",[eventId]);assert.equal(count.n,0);assert.equal((await f.db.query("SELECT COUNT(*) AS n FROM inventory_reservations WHERE warehouse_id=?",[f.warehouseId]))[0][0].n,0);assert.equal((await f.db.query("SELECT status FROM item_skus WHERE id=?",[f.skuId]))[0][0].status,"active");
});

async function confirm(f,id=f.request.id){const s=f.service(),intent=await s.startConfirmation({claims:f.claims,id,input:{eventId:randomUUID(),version:1}});return s.completeConfirmation({eventId:intent.eventId,claims:f.claims,leaseOwner:intent.leaseOwner});}
async function anotherOrder(f){const r=await new SalesOrderService(f).create({claims:f.claims,input:{eventId:randomUUID(),customerId:f.customerId,currencyCode:f.currency,fulfillmentWarehouseId:f.warehouseId,orderDate:f.time.fileDate(),lines:[{skuId:f.skuId,skuUomId:f.skuUomId,quantity:"10.000000",unitSellingPrice:"1.0000"}]}});return r.salesOrder.id;}
async function topup(f,quantity){const [[bin]]=await f.db.query("SELECT id FROM inventory_bins WHERE warehouse_id=?",[f.warehouseId]);const [[balance]]=await f.db.query("SELECT id FROM inventory_stock_balances WHERE warehouse_id=? AND sku_id=?",[f.warehouseId,f.skuId]);if(balance)await f.db.execute("UPDATE inventory_stock_balances SET on_hand_quantity=on_hand_quantity+?,version=version+1 WHERE id=?",[quantity,Number(balance.id)]);else await f.db.execute("INSERT INTO inventory_stock_balances (warehouse_id,bin_id,sku_id,stock_status,on_hand_quantity,created_at,updated_at) VALUES (?,?,?,'AVAILABLE',?,?,?)",[f.warehouseId,Number(bin.id),f.skuId,quantity,f.now,f.now]);}
async function allocator(f,options={}){const owner=await prepareLease(f),controller=new AbortController(),authorizeSalesBackorder=()=>({leaseOwner:owner,signal:controller.signal});return {s:new SalesBackorderService({...f,authorizeSalesBackorder,...options}),owner,controller,authorizeSalesBackorder};}
it("TC-031 FIFO allocates oldest partial demand, blocks later due entry behind cooldown and wakes whole scope without priority mutation",async t=>{
 const f=await setup(t);await stock(f,0);await confirm(f);const second=await anotherOrder(f);await confirm(f,second);const a=await allocator(f),scope={warehouseId:f.warehouseId,skuId:f.skuId};const [before]=await f.db.query("SELECT id,priority_at FROM sales_backorder_entries WHERE warehouse_id=? ORDER BY priority_at,sales_order_id,line_no,id",[f.warehouseId]);await topup(f,7);
 const first=await a.s.runBatch({scope,maxEntries:10});assert.equal(first.allocatedEntries,1);assert.equal(first.allocatedBaseQuantity,"7");assert.equal(first.noStock,1);assert.equal(first.deferred,0);assert.equal((await readSalesOrderDetail(f.db,f.request.id)).lines[0].reservedBaseQuantity,"7");assert.equal((await readSalesOrderDetail(f.db,second)).lines[0].reservedBaseQuantity,"0");
 assert.equal((await a.s.runBatch({scope,maxEntries:10})).scanned,0);await topup(f,10);assert.deepEqual(await a.s.wake({claims:f.claims,input:{orderId:second}}),{accepted:true});const next=await a.s.runBatch({scope,maxEntries:10});assert.equal(next.allocatedEntries,2);assert.equal(next.allocatedBaseQuantity,"10");assert.equal(next.deferred,0);
 const orders=await Promise.all([f.request.id,second].map(id=>readSalesOrderDetail(f.db,id)));assert.deepEqual(orders.map(o=>[o.lines[0].reservedBaseQuantity,o.lines[0].backorderedBaseQuantity]),[["10","0"],["7","3"]]);assert.equal(orders[0].hasBackorder,false);assert.equal(orders[1].hasBackorder,true);assert.deepEqual((await f.db.query("SELECT id,priority_at FROM sales_backorder_entries WHERE warehouse_id=? ORDER BY priority_at,sales_order_id,line_no,id",[f.warehouseId]))[0],before);
 const [[control]]=await f.db.query("SELECT reserved_quantity FROM inventory_stock_controls WHERE warehouse_id=? AND sku_id=?",[f.warehouseId,f.skuId]);assert.equal(control.reserved_quantity,17);const [mappings]=await f.db.query("SELECT r.* FROM sales_order_line_reservations r JOIN sales_order_lines l ON l.id=r.sales_order_line_id WHERE l.sales_order_id IN (?,?)",[f.request.id,second]);assert.equal(mappings.length,3);assert.equal(mappings.reduce((sum,m)=>sum+m.outstanding_base_quantity,0),17);const [audit]=await f.db.query("SELECT actor_user_id,actor_label FROM sales_audit_logs WHERE target_id IN (?,?) AND action='sales_order.backorder_allocated'",[f.request.id,second]);assert.equal(audit.length,3);assert.ok(audit.every(row=>row.actor_user_id===null&&row.actor_label===name));
});
it("TC-031 zero ATP delays queue metadata only and stale zero-demand queue becomes terminal without Inventory",async t=>{
 const f=await setup(t);await stock(f,0);await confirm(f);const a=await allocator(f),before=await readSalesOrderDetail(f.db,f.request.id),scope={warehouseId:f.warehouseId,skuId:f.skuId};const result=await a.s.runBatch({scope,maxEntries:10});assert.equal(result.noStock,1);assert.equal(result.allocatedEntries,0);assert.deepEqual(await readSalesOrderDetail(f.db,f.request.id),before);const [[q]]=await f.db.query("SELECT * FROM sales_backorder_entries WHERE sales_order_id=?",[f.request.id]);assert.equal(q.attempt_count,1);assert.ok(q.next_attempt_at>q.last_attempt_at);assert.match(q.last_allocation_event_id,/^[a-f0-9-]{36}$/u);
 await f.db.execute("UPDATE sales_order_lines SET backordered_base_quantity=0,cancelled_base_quantity=10 WHERE sales_order_id=?",[f.request.id]);await f.db.execute("UPDATE sales_orders SET status='CANCELLED',has_backorder=0,backorder_line_count=0 WHERE id=?",[f.request.id]);await a.s.wake({claims:f.claims,input:scope});const inventory=a.s.inventory;a.s.inventory={reserveAvailableForSalesBackorderInTransaction(){throw Error("Stale must not call Inventory");}};const stale=await a.s.runBatch({scope,maxEntries:10});a.s.inventory=inventory;assert.equal(stale.stale,1);assert.equal(stale.deferred,0);assert.equal((await f.db.query("SELECT status,outstanding_base_quantity FROM sales_backorder_entries WHERE id=?",[q.id]))[0][0].status,"CANCELLED");assert.equal((await readSalesOrderDetail(f.db,f.request.id)).version,before.version);
});

async function commitmentFacts(f){const [lines]=await f.db.query("SELECT id,version,reserved_outstanding_base_quantity,backordered_base_quantity FROM sales_order_lines WHERE sales_order_id=?",[f.request.id]);const [queue]=await f.db.query("SELECT * FROM sales_backorder_entries WHERE sales_order_id=?",[f.request.id]);const [mappings]=await f.db.query("SELECT r.* FROM sales_order_line_reservations r JOIN sales_order_lines l ON l.id=r.sales_order_line_id WHERE l.sales_order_id=?",[f.request.id]);const [reservations]=await f.db.query("SELECT * FROM inventory_reservations WHERE warehouse_id=?",[f.warehouseId]);const [controls]=await f.db.query("SELECT * FROM inventory_stock_controls WHERE warehouse_id=?",[f.warehouseId]);const [audit]=await f.db.query("SELECT id,event_id FROM sales_audit_logs WHERE target_id=? AND target_type='ORDER' ORDER BY id",[f.request.id]);return {order:await readSalesOrderDetail(f.db,f.request.id),lines,queue,mappings,reservations,controls,audit};}
it("TC-031 native allocation faults and authority changes roll back every Sales/Inventory projection",async t=>{
 for(const fault of ["audit","missing","tampered","authority"])await t.test(fault,async child=>{
  const f=await setup(child);await stock(f,0);await confirm(f);await topup(f,4);const a=await allocator(f),before=await commitmentFacts(f),inventory=a.s.inventory;
  if(fault==="audit")a.s.audit={record(){throw Error("required Audit failed");}};
  else a.s.inventory={async reserveAvailableForSalesBackorderInTransaction(...args){const r=await inventory.reserveAvailableForSalesBackorderInTransaction(...args);if(fault==="missing")r.lines=[];if(fault==="tampered")r.lines[0].rootRequestHash="0".repeat(64);if(fault==="authority")a.s.authorize=()=>({leaseOwner:"changed-owner",signal:a.controller.signal});return r;}};
  const result=await a.s.runBatch({scope:{warehouseId:f.warehouseId,skuId:f.skuId},maxEntries:1});assert.equal(result.deferred,1);assert.equal(result.allocatedEntries,0);const after=await commitmentFacts(f);
  if(fault!=="authority"){assert.equal(after.queue[0].last_error_code,"SALES_DEPENDENCY_UNAVAILABLE");assert.equal(Number(after.queue[0].next_attempt_at)-Number(after.queue[0].last_attempt_at),30000);after.queue=before.queue;}
  assert.deepEqual(after,before);
 });
});
it("TC-031 native lost COMMIT acknowledgement reconciles the persisted original allocation event once",async t=>{
 const f=await setup(t);await stock(f,0);await confirm(f);await topup(f,4);const a=await allocator(f);let lose=true;
 const database={query:(...args)=>f.database.query(...args),async withTransaction(...args){const r=await f.database.withTransaction(...args);if(lose&&r?.quantity>0){lose=false;throw Object.assign(Error("lost COMMIT acknowledgement"),{code:"DATABASE_TRANSACTION_INDETERMINATE"});}return r;}};
 a.s.database=database;const result=await a.s.runBatch({scope:{warehouseId:f.warehouseId,skuId:f.skuId},maxEntries:10});assert.equal(result.reconciled,1);assert.equal(result.allocatedBaseQuantity,"4");assert.equal(result.deferred,0);const state=await commitmentFacts(f);assert.equal(state.mappings.length,1);assert.equal(state.reservations.length,1);assert.equal(state.order.lines[0].reservedBaseQuantity,"4");const eventId=state.queue[0].last_allocation_event_id;assert.equal(state.mappings[0].source_event_id,eventId);assert.equal((await f.db.query("SELECT COUNT(*) AS n FROM inventory_operation_requests WHERE source_event_id=?",[eventId]))[0][0].n,2);assert.equal((await f.db.query("SELECT COUNT(*) AS n FROM sales_order_status_history WHERE event_id=?",[eventId]))[0][0].n,1);assert.equal((await a.s.runBatch({maxEntries:10})).scanned,0);
});
it("TC-031 native proven rollback permits a new allocation event without preserving a fictitious effect",async t=>{
 const f=await setup(t);await stock(f,0);await confirm(f);await topup(f,4);const a=await allocator(f),before=await commitmentFacts(f),events=[],inventory=a.s.inventory;let rollback=true;
 a.s.inventory={async reserveAvailableForSalesBackorderInTransaction(tx,input){events.push(input.source.eventId);return inventory.reserveAvailableForSalesBackorderInTransaction(tx,input);}};
 a.s.database={query:(...args)=>f.database.query(...args),withTransaction:(work,options)=>f.database.withTransaction(async tx=>{const r=await work(tx);if(rollback&&r?.quantity>0){rollback=false;throw Error("native rollback before COMMIT");}return r;},options)};
 assert.equal((await a.s.runBatch({maxEntries:1})).deferred,1);const after=await commitmentFacts(f);assert.equal(after.queue[0].last_error_code,"SALES_DEPENDENCY_UNAVAILABLE");after.queue=before.queue;assert.deepEqual(after,before);assert.equal((await a.s.runBatch({maxEntries:1})).scanned,0);await a.s.wake({claims:f.claims,input:{orderId:f.request.id}});const next=await a.s.runBatch({maxEntries:1});assert.equal(next.allocatedBaseQuantity,"4");assert.equal(next.deferred,0);assert.equal(events.length,2);assert.notEqual(events[0],events[1]);assert.equal((await f.db.query("SELECT COUNT(*) AS n FROM inventory_operation_requests WHERE source_event_id=?",[events[0]]))[0][0].n,0);assert.equal((await commitmentFacts(f)).mappings[0].source_event_id,events[1]);
});
it("TC-031 true overlapping allocators fence one FIFO head and cannot over-reserve ATP",async t=>{
 const f=await setup(t);await stock(f,0);await confirm(f);await topup(f,4);const a=await allocator(f),barrier=Promise.withResolvers();let entered=0;
 const database={withTransaction:(...args)=>f.database.withTransaction(...args),async query(...args){const r=await f.database.query(...args);if(args[0].startsWith("SELECT q.id")&&entered<2){entered++;if(entered===2)barrier.resolve();await barrier.promise;}return r;}};
 const left=new SalesBackorderService({...f,database,authorizeSalesBackorder:a.authorizeSalesBackorder}),right=new SalesBackorderService({...f,database,authorizeSalesBackorder:a.authorizeSalesBackorder});const runs=[left.runBatch({maxEntries:1}),right.runBatch({maxEntries:1})];let results;
 try{results=await Promise.all(runs);}finally{barrier.resolve();await Promise.allSettled(runs);}
 assert.equal(entered,2);assert.equal(results.reduce((n,r)=>n+r.allocatedEntries,0),1);const state=await commitmentFacts(f);assert.equal(state.mappings.length,1);assert.equal(state.reservations.length,1);assert.equal(state.controls[0].reserved_quantity,4);assert.equal(state.order.lines[0].backorderedBaseQuantity,"6");
});
it("TC-031 concurrent cancellation observes allocation version then safely releases the worker mapping",async t=>{
 const f=await setup(t);await stock(f,0);await confirm(f);await topup(f,4);const a=await allocator(f),inventory=a.s.inventory,entered=Promise.withResolvers(),release=Promise.withResolvers();a.s.inventory={async reserveAvailableForSalesBackorderInTransaction(...args){const r=await inventory.reserveAvailableForSalesBackorderInTransaction(...args);entered.resolve();await release.promise;return r;}};
 const allocation=a.s.runBatch({maxEntries:1});await Promise.race([entered.promise,allocation.then(()=>{throw Error("allocation did not enter Inventory");})]);const lifecycle=new SalesOrderLifecycleService({...f,services:f.app.services}),request={claims:f.claims,id:f.request.id,input:{eventId:randomUUID(),version:3,reason:"客戶要求取消訂單"}},cancel=lifecycle.cancel(request);const rejection=assert.rejects(()=>cancel,{code:"VERSION_CONFLICT"});release.resolve();try{assert.equal((await allocation).allocatedBaseQuantity,"4");await rejection;}finally{release.resolve();await Promise.allSettled([allocation,cancel]);}
 const cancelled=await lifecycle.cancel({...request,input:{...request.input,eventId:randomUUID(),version:4}});assert.equal(cancelled.salesOrder.status,"CANCELLED");assert.equal(cancelled.salesOrder.lines[0].cancelledBaseQuantity,"10");const state=await commitmentFacts(f);assert.equal(state.controls[0].reserved_quantity,0);assert.equal(state.mappings[0].outstanding_base_quantity,0);assert.equal(state.reservations[0].status,"RELEASED");
});

async function registeredWorker(f){
 const config={...f.app.configuration,scheduler:{...f.app.configuration.scheduler,enabled:true,startupJitterRatio:0,jobs:{}}},sources={mysqldatabase:f.database,time:f.time,logging:{logger:f.logger}},services={require:key=>sources[key]};
 const scheduler=new SchedulerService({config,services}),runtime=new SalesJobRuntimeService({config,services});sources.scheduler=scheduler;sources.salesJobs=runtime;
 const job=new SalesBackorderAllocationJob({config,services});await job.initialize();await scheduler.start();f.beforeParents.push(()=>scheduler.stop());return {scheduler,runtime,job};
}
it("TC-031 technical retry persists bounded exponential cooldown across a new allocator and manual wake cannot bypass FIFO",async t=>{
 const f=await setup(t);await stock(f,0);await confirm(f);await topup(f,4);const a=await allocator(f),scope={warehouseId:f.warehouseId,skuId:f.skuId},before=await readSalesOrderDetail(f.db,f.request.id);
 const failing=()=>new SalesBackorderService({...f,authorizeSalesBackorder:a.authorizeSalesBackorder,inventory:{reserveAvailableForSalesBackorderInTransaction(){throw Error("synthetic unavailable");}}});
 for(const delay of [30000,60000,120000,240000,300000,300000]){await a.s.wake({claims:f.claims,input:scope});assert.equal((await failing().runBatch({scope,maxEntries:1})).deferred,1);const [[q]]=await f.db.query("SELECT next_attempt_at,last_attempt_at,last_error_code FROM sales_backorder_entries WHERE sales_order_id=?",[f.request.id]);assert.equal(Number(q.next_attempt_at)-Number(q.last_attempt_at),delay);assert.equal(q.last_error_code,"SALES_DEPENDENCY_UNAVAILABLE");assert.equal((await failing().runBatch({scope,maxEntries:1})).scanned,0);assert.deepEqual(await readSalesOrderDetail(f.db,f.request.id),before);}
});
it("TC-031 actual registered Scheduler runtime uses SQL cluster admission, overlap and the NULL reserve-only actor",async t=>{
 const f=await setup(t);await stock(f,0);await confirm(f);await topup(f,4);await prepareLease(f);await f.db.execute("UPDATE fr_job_leases SET owner='',expires_at=0 WHERE job_name=?",[name]);
 const first=await registeredWorker(f),second=await registeredWorker(f),entered=Promise.withResolvers(),release=Promise.withResolvers(),batch=first.runtime.backorder.runBatch.bind(first.runtime.backorder);
 first.runtime.backorder.runBatch=async options=>{assert.equal(options.signal,first.runtime.backorderPrincipal().signal);assert.equal(first.runtime.backorderPrincipal().leaseOwner,first.scheduler.owner);entered.resolve();await release.promise;return batch(options);};
 const work=first.scheduler.execute(first.scheduler.jobs.get(name));
 try{await waitForWorkerEntry(entered.promise,work);await first.scheduler.execute(first.scheduler.jobs.get(name));await second.scheduler.execute(second.scheduler.jobs.get(name));assert.equal(first.scheduler.stats.get(name).skippedOverlapping,1);assert.equal(second.scheduler.stats.get(name).skippedNotLeader,1);release.resolve();await work;}finally{release.resolve();await work;}
 const state=await commitmentFacts(f);assert.equal(first.scheduler.stats.get(name).runs,1);assert.equal(first.scheduler.stats.get(name).failures,0);assert.equal(state.mappings.length,1);assert.equal(state.controls[0].reserved_quantity,4);
 const [operations]=await f.db.query("SELECT actor_user_id,actor_label,command_type FROM inventory_operation_requests WHERE source_event_id=?",[state.mappings[0].source_event_id]);assert.equal(operations.length,2);assert.ok(operations.every(row=>row.actor_user_id===null&&row.actor_label===name&&row.command_type.startsWith("SALES_BACKORDER_")));assert.equal(first.runtime.backorderPrincipal(),null);
 await first.scheduler.stop();await assert.rejects(()=>first.runtime.wakeBackorders({claims:f.claims,input:{orderId:f.request.id}}),{code:"SALES_DEPENDENCY_UNAVAILABLE"});
});
it("TC-031 real Scheduler shutdown aborts an in-flight Inventory allocation, preserves FIFO demand and a new registered runtime retries safely",async t=>{
 const f=await setup(t);await stock(f,0);await confirm(f);await topup(f,4);await prepareLease(f);await f.db.execute("UPDATE fr_job_leases SET owner='',expires_at=0 WHERE job_name=?",[name]);const before=await commitmentFacts(f),first=await registeredWorker(f),entered=Promise.withResolvers(),inventory=first.runtime.backorder.inventory;
 first.runtime.backorder.inventory={async reserveAvailableForSalesBackorderInTransaction(...args){const result=await inventory.reserveAvailableForSalesBackorderInTransaction(...args),signal=first.runtime.backorderPrincipal().signal;entered.resolve();await new Promise((resolve,reject)=>{signal.addEventListener("abort",()=>reject(signal.reason),{once:true});});return result;}};
 const work=first.scheduler.execute(first.scheduler.jobs.get(name));try{await waitForWorkerEntry(entered.promise,work);assert.deepEqual(await first.scheduler.stop({timeoutMs:1000}),{stopped:true,drained:true});await work;}finally{await first.scheduler.stop();await work;}
 assert.equal(first.scheduler.running.size,0);assert.equal(first.runtime.backorderPrincipal(),null);assert.deepEqual(await commitmentFacts(f),before);const second=await registeredWorker(f);await second.scheduler.execute(second.scheduler.jobs.get(name));assert.equal(second.scheduler.stats.get(name).runs,1);assert.equal((await commitmentFacts(f)).mappings.length,1);assert.equal((await readSalesOrderDetail(f.db,f.request.id)).lines[0].reservedBaseQuantity,"4");
});
it("TC-031 actual manual wake HTTP validates scope/fresh permissions, invokes registered Scheduler and accepts before allocation completion",async t=>{
 const f=await setup(t,{backorderEnabled:true});await stock(f,0);await confirm(f);await topup(f,4);await prepareLease(f);await f.db.execute("UPDATE fr_job_leases SET owner='',expires_at=0 WHERE job_name=?",[name]);
 const {url}=await f.app.start(),token=await f.app.services.require("jwt").issue({roles:f.claims.claimedRoles,permissions:f.claims.claimedPermissions},{subject:String(f.userId),version:await f.app.services.require("tokenRevocation").currentVersion(String(f.userId)),authTime:Math.floor(f.now/1000)}),runtime=f.app.services.require("salesJobs"),scheduler=f.app.services.require("scheduler"),entered=Promise.withResolvers(),release=Promise.withResolvers(),batch=runtime.backorder.runBatch.bind(runtime.backorder);
 const request=(body,key=randomUUID())=>fetch(new URL("/api/v1/sales-backorders/allocations/run",url),{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json","Idempotency-Key":key},body:JSON.stringify(body)});
 for(const input of [{orderId:String(f.request.id)},{orderId:f.request.id,priority:0},{orderId:f.request.id,actorId:f.userId},{warehouseId:f.warehouseId},{}]){const response=await request(input);assert.equal(response.status,400);assert.equal((await response.json()).error.code,"SALES_INPUT_INVALID");}
 const absent=await request({orderId:2147483647});assert.equal(absent.status,404);assert.equal((await absent.json()).error.code,"SALES_ORDER_NOT_FOUND");
 runtime.backorder.runBatch=async options=>{entered.resolve();await release.promise;return batch(options);};const key=randomUUID();let worker;
 try{const response=await request({orderId:f.request.id},key);assert.equal(response.status,202);assert.deepEqual((await response.json()).data,{accepted:true});worker=scheduler.running.get(name)?.promise;assert.ok(worker);await waitForWorkerEntry(entered.promise,worker);assert.equal((await readSalesOrderDetail(f.db,f.request.id)).lines[0].reservedBaseQuantity,"0");const replay=await request({orderId:f.request.id},key);assert.equal(replay.status,202);assert.deepEqual((await replay.json()).data,{accepted:true});await f.db.execute("DELETE FROM role_permissions WHERE role_id=?",[f.roleId]);const revoked=await request({orderId:f.request.id},key);assert.equal(revoked.status,403);assert.equal((await revoked.json()).error.code,"PERMISSION_STALE");release.resolve();await worker;}finally{release.resolve();await worker;}
 const state=await commitmentFacts(f);assert.equal(state.mappings.length,1);assert.equal(state.order.lines[0].reservedBaseQuantity,"4");assert.equal(scheduler.stats.get(name).runs,1);
});
