import assert from "node:assert/strict";
import test from "node:test";
import {randomUUID,createHash} from "node:crypto";
import {mkdtemp,mkdir,writeFile,readFile,lstat,symlink,unlink,rm,chmod} from "node:fs/promises";
import path from "node:path";
import {migrationFixture} from "../sales/phase1/fixtures.js";
import {createApplication} from "../../src/framework/application/createApplication.js";
import {defaultConfigurationSource} from "../../src/framework/configuration/applicationConfiguration.js";
import {SalesFileRetentionJob} from "../../src/services/salesJobs/jobs/SalesFileRetentionJob.js";
import {SalesImportQueryService} from "../../src/modules/sales/SalesImportQueryService.js";
const integrationTest=process.env.DB_INTEGRATION_TESTS==='1'?test:test.skip,day=86400000;
async function fixture(t){const f=await migrationFixture(t,[]),source=defaultConfigurationSource(),app=await createApplication({configurationSource:{...source,application:{...source.application,port:0},scheduler:{...source.scheduler,startupJitterRatio:0,jobs:{...source.scheduler.jobs,'sales.importWorker':{enabled:false}}}}});t.after(()=>app.shutdown('sales_retention_complete'));const root=await mkdtemp(path.join('/private/tmp/','sales-retention-owned-'));t.after(()=>rm(root,{recursive:true,force:true}));const database=app.services.require('mysqldatabase'),scheduler=app.services.require('scheduler'),job=app.services.require('job.salesFileRetention');job.root=root;assert.ok(job instanceof SalesFileRetentionJob);const [[original]]=await f.db.query("SELECT * FROM fr_job_leases WHERE job_name='sales.fileRetention'");
 const label='retention-'+randomUUID().slice(0,8),roleId=await f.insert('roles',{name:label,created_at:f.now}),userId=await f.insert('users',{username:label,password_hash:'synthetic',display_name:'Synthetic',created_at:f.now,updated_at:f.now});await f.db.execute('INSERT INTO user_roles (user_id,role_id) VALUES (?,?)',[userId,roleId]);await f.db.execute("INSERT INTO role_permissions (role_id,permission_id) SELECT ?,id FROM permissions WHERE name='sales.view'",[roleId]);const claims={actorId:userId,claimedRoles:[label],claimedPermissions:['sales.view']};
 f.beforeParents.push(async()=>{await f.db.execute('DELETE FROM fr_token_versions WHERE subject=?',[String(userId)]);await f.db.execute('DELETE FROM role_permissions WHERE role_id=?',[roleId]);await f.db.execute('DELETE FROM user_roles WHERE user_id=?',[userId]);if(original)await f.db.execute("UPDATE fr_job_leases SET owner=?,acquired_at=?,expires_at=? WHERE job_name='sales.fileRetention'",[original.owner,original.acquired_at,original.expires_at]);else await f.db.execute("DELETE FROM fr_job_leases WHERE job_name='sales.fileRetention'");});
 async function seed({status='COMPLETED',age=91,sourceName='source.csv'}={}){const now=Date.now(),batch=`SI-202607-${String(Math.floor(Math.random()*900000)+100000)}`,directory=path.join(root,batch);await mkdir(directory,{mode:0o700});await writeFile(path.join(directory,'source.csv'),'synthetic',{mode:0o600});await writeFile(path.join(directory,'result.csv'),'synthetic-result',{mode:0o600});const id=await f.insert('sales_import_jobs',{batch_number:batch,template_version:'1.0',original_file_name:'synthetic.csv',source_file_path:`${batch}/${sourceName}`,result_file_path:`${batch}/result.csv`,file_sha256:createHash('sha256').update(batch).digest(),file_size_bytes:9,status,source_order_count:1,valid_count:1,created_by:userId,created_at:now-age*day,updated_at:now-age*day,completed_at:['COMPLETED','PARTIAL_SUCCESS','FAILED','CANCELLED'].includes(status)?now-age*day:null});const ext=randomUUID(),hash=createHash('sha256').update(ext).digest(),key=await f.insert('sales_external_order_keys',{channel_code:'RETENTION',external_order_id:ext,external_order_id_hash:hash,source_type:'CSV',payload_hash:'0'.repeat(64),status:'SUCCEEDED',sales_order_id:null,sales_order_number:'SO26000001',is_order_archived:1,claimed_at:now-8*365*day,updated_at:now-8*365*day});
 const child=await f.insert('sales_intake_orders',{import_job_id:id,source_type:'CSV',source_order_key:ext,source_order_key_hash:hash,channel_code:'RETENTION',external_order_id:ext,external_order_id_hash:hash,schema_version:'1.0',payload_hash:'0'.repeat(64),safe_payload:JSON.stringify({document:{notes:'synthetic'}}),first_row_no:2,last_row_no:2,line_count:1,status:status==='READY'?'VALID':status==='CANCELLED'?'VALID':'INVALID',processing_event_id:randomUUID(),external_order_key_id:key,sales_order_number:'SO26000001',created_at:now-age*day,updated_at:now-age*day,completed_at:null});await f.insert('sales_intake_errors',{intake_order_id:child,row_no:2,field_path:'quantity',error_code:'SALES_QUANTITY_INVALID',safe_message:'數量無效',created_at:now-age*day});return {id,batch,directory,child,key};}
 const {url}=await app.start();return {...f,app,database,scheduler,job,root,claims,seed,url,async run(){await scheduler.execute(scheduler.jobs.get('sales.fileRetention'));},async facts(id){return (await f.db.query('SELECT * FROM sales_import_jobs WHERE id=?',[id]))[0][0];}};
}
integrationTest('TC-041 actual discovered retention purges expired files/payload and HTTP410 while preserving structured results and eight-year key',async t=>{const f=await fixture(t),old=await f.seed(),fresh=await f.seed({age:89}),pending=await f.seed({status:'READY',age:91}),cancelled=await f.seed({status:'CANCELLED'});await f.run();assert.equal(f.scheduler.stats.get('sales.fileRetention').lastOutcome,'succeeded');for(const candidate of [old,cancelled]){assert.ok((await f.facts(candidate.id)).files_purged_at);assert.equal((await f.db.query('SELECT safe_payload FROM sales_intake_orders WHERE id=?',[candidate.child]))[0][0].safe_payload,null);await assert.rejects(()=>lstat(path.join(candidate.directory,'source.csv')),{code:'ENOENT'});assert.equal((await f.db.query('SELECT COUNT(*) AS n FROM sales_external_order_keys WHERE id=?',[candidate.key]))[0][0].n,1);assert.equal((await f.db.query('SELECT COUNT(*) AS n FROM sales_intake_errors WHERE intake_order_id=?',[candidate.child]))[0][0].n,1);}
 for(const candidate of [fresh,pending]){assert.equal((await f.facts(candidate.id)).files_purged_at,null);assert.equal(await readFile(path.join(candidate.directory,'source.csv'),'utf8'),'synthetic');}
 const query=new SalesImportQueryService({database:f.database});assert.equal((await query.get({claims:f.claims,id:old.id})).filesPurgedAt!==null,true);assert.equal((await query.orders({claims:f.claims,id:old.id})).items.length,1);const token=await f.app.services.require('jwt').issue({roles:f.claims.claimedRoles,permissions:f.claims.claimedPermissions},{subject:String(f.claims.actorId),version:await f.app.services.require('tokenRevocation').currentVersion(String(f.claims.actorId)),authTime:Math.floor(Date.now()/1000)}),url=new URL(`/api/v1/sales-imports/${old.id}/result`,f.url);const response=await fetch(url,{headers:{Authorization:`Bearer ${token}`}});assert.equal(response.status,410);assert.equal((await response.json()).error.code,'SALES_IMPORT_RESULT_EXPIRED');
});
integrationTest('TC-041 actual retention refuses symlink, traversal and0755 without touching outside file then recovers',async t=>{const f=await fixture(t),link=await f.seed(),traversal=await f.seed({sourceName:'../../outside.csv'}),mode=await f.seed(),outside=path.join(f.root,'outside.csv');await writeFile(outside,'keep',{mode:0o600});await unlink(path.join(link.directory,'source.csv'));await symlink(outside,path.join(link.directory,'source.csv'));await chmod(mode.directory,0o755);await f.run();assert.equal(f.scheduler.stats.get('sales.fileRetention').lastOutcome,'failed');assert.equal(await readFile(outside,'utf8'),'keep');for(const candidate of [link,traversal,mode])assert.equal((await f.facts(candidate.id)).files_purged_at,null);assert.equal((await lstat(path.join(link.directory,'source.csv'))).isSymbolicLink(),true);await unlink(path.join(link.directory,'source.csv'));await writeFile(path.join(link.directory,'source.csv'),'synthetic',{mode:0o600});await f.db.execute('UPDATE sales_import_jobs SET source_file_path=? WHERE id=?',[traversal.batch+'/source.csv',traversal.id]);await chmod(mode.directory,0o700);await f.run();assert.equal(f.scheduler.stats.get('sales.fileRetention').lastOutcome,'succeeded');for(const candidate of [link,traversal,mode])assert.ok((await f.facts(candidate.id)).files_purged_at);});
integrationTest('TC-041 purge deletion before failed marker transaction is safely retried against original structured facts',async t=>{const f=await fixture(t),old=await f.seed(),original=f.job.database;let failed=false;f.job.database={withTransaction(work,options){return original.withTransaction(tx=>work({query:tx.query.bind(tx),async execute(sql,args){if(!failed&&sql.includes("files_purged_at=?")){failed=true;throw Error('synthetic marker rollback');}return tx.execute(sql,args);}}),options);}};await f.run();assert.equal(f.scheduler.stats.get('sales.fileRetention').lastOutcome,'failed');assert.equal((await f.facts(old.id)).files_purged_at,null);await assert.rejects(()=>lstat(path.join(old.directory,'source.csv')),{code:'ENOENT'});f.job.database=original;await f.run();assert.ok((await f.facts(old.id)).files_purged_at);assert.equal((await f.db.query('SELECT processing_event_id FROM sales_intake_orders WHERE id=?',[old.child]))[0].length,1);assert.equal((await f.db.query('SELECT COUNT(*) AS n FROM sales_external_order_keys WHERE id=?',[old.key]))[0][0].n,1);});
integrationTest('TC-041 standalone Channel terminal payload expires but queued authority and original transport facts remain',async t=>{const f=await fixture(t),now=Date.now(),ids=[];for(const status of ['INVALID','QUEUED']){const ext=randomUUID(),hash=createHash('sha256').update(ext).digest();ids.push(await f.insert('sales_intake_orders',{import_job_id:null,source_type:'CHANNEL',source_order_key:ext,source_order_key_hash:hash,channel_code:'RETENTION',external_order_id:ext,external_order_id_hash:hash,schema_version:'1.0',transport_request_id:ext,transport_idempotency_key_hash:hash,payload_hash:'0'.repeat(64),safe_payload:JSON.stringify({channelIdentity:{code:'RETENTION',serviceId:'synthetic'}}),first_row_no:1,last_row_no:1,line_count:1,status,processing_event_id:randomUUID(),created_at:now-91*day,updated_at:now-91*day,completed_at:status==='INVALID'?now-91*day:null}));}await f.run();const [rows]=await f.db.query('SELECT id,status,safe_payload,payload_purged_at,transport_request_id,processing_event_id FROM sales_intake_orders WHERE id IN (?,?) ORDER BY id',ids);assert.equal(rows[0].safe_payload,null);assert.ok(rows[0].payload_purged_at);assert.ok(rows[0].transport_request_id);assert.ok(rows[0].processing_event_id);assert.ok(rows[1].safe_payload);assert.equal(rows[1].payload_purged_at,null);});
