import assert from "node:assert/strict";
import test from "node:test";
import {randomUUID,createHash} from "node:crypto";
import {setup,stock} from "../sales/phase2/fixtures.js";
import {InventoryReservationService} from "../../src/modules/inventory/InventoryReservationService.js";
const it=process.env.DB_INTEGRATION_TESTS==="1"?test:test.skip,name="sales.importWorker";
it("TC-038 Intake Inventory native owner chain, distinct replay, stale source and caller rollback preserve atomicity",async t=>{
 const f=await setup(t);await stock(f,4);const eventId=randomUUID(),externalId=randomUUID(),hash=createHash("sha256").update(externalId).digest(),payloadHash="0".repeat(64),signal=new AbortController().signal,leaseOwner=`test-${randomUUID()}`,claimToken=randomUUID(),now=f.time.nowMs(),[[original]]=await f.db.query("SELECT * FROM fr_job_leases WHERE job_name=?",[name]);
 await f.db.execute("INSERT INTO fr_job_leases (job_name,owner,acquired_at,expires_at) VALUES (?,?,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()+60) ON DUPLICATE KEY UPDATE owner=VALUES(owner),expires_at=VALUES(expires_at)",[name,leaseOwner]);
 const jobId=await f.insert("sales_import_jobs",{batch_number:"SI-261008-"+String(Math.floor(Math.random()*900000)+100000),template_version:"1.0",original_file_name:"synthetic.csv",source_file_path:"synthetic/source.csv",file_sha256:hash,file_size_bytes:1,status:"PROCESSING",created_by:f.userId,confirmed_by:f.userId,lease_owner:claimToken,lease_until:now+60000,created_at:now,updated_at:now});
 const intakeId=await f.insert("sales_intake_orders",{import_job_id:jobId,source_type:"CSV",source_order_key:externalId,source_order_key_hash:hash,channel_code:"SYNTHETIC",external_order_id:externalId,external_order_id_hash:hash,schema_version:"1.0",payload_hash:payloadHash,first_row_no:2,last_row_no:2,line_count:1,status:"PROCESSING",processing_event_id:eventId,created_at:now,updated_at:now});
 f.beforeParents.push(async()=>{await f.db.execute("DELETE FROM sales_orders WHERE id=?",[f.request.id]);if(original)await f.db.execute("UPDATE fr_job_leases SET owner=?,acquired_at=?,expires_at=? WHERE job_name=?",[original.owner,original.acquired_at,original.expires_at,name]);else await f.db.execute("DELETE FROM fr_job_leases WHERE job_name=?",[name]);});
 let enabled=true;const service=new InventoryReservationService({...f,authorizeSalesIntake:()=>enabled?{leaseOwner,signal}:null}),[[line]]=await f.db.query("SELECT id FROM sales_order_lines WHERE sales_order_id=?",[f.request.id]),command={actor:{userId:null,serviceName:name,claimedRoles:[],claimedPermissions:[name]},source:{documentId:String(f.request.id),eventId},correlationId:eventId,payload:{warehouseId:f.warehouseId,expectedOrderVersion:1,lines:[{sourceLineId:Number(line.id),skuId:f.skuId,orderedBaseQuantity:10,minimumRemainingDays:0}]}},rollback=Error("intentional caller rollback");
 await assert.rejects(()=>f.database.withTransaction(async tx=>{
  const [key]=await tx.execute("INSERT INTO sales_external_order_keys (channel_code,external_order_id,external_order_id_hash,source_type,payload_hash,status,claimed_at,updated_at) VALUES ('SYNTHETIC',?,?,'CSV',?,'PROCESSING',?,?)",[externalId,hash,payloadHash,now,now]);
  await tx.execute("INSERT INTO sales_operation_requests (event_id,command_type,target_type,target_id,request_hash,status,actor_user_id,actor_label,created_at,updated_at) VALUES (?,'PROCESS_INTAKE','INTAKE_ORDER',?,?,'IN_PROGRESS',?,'Synthetic',?,?)",[eventId,intakeId,payloadHash,f.userId,now,now]);
  await tx.execute("UPDATE sales_orders SET source_type='CSV',source_intake_order_id=?,external_order_key_id=?,channel_code_snapshot='SYNTHETIC',external_order_id_snapshot=?,confirmation_event_id=? WHERE id=?",[intakeId,key.insertId,externalId,eventId,f.request.id]);await tx.execute("UPDATE sales_intake_orders SET sales_order_id=?,external_order_key_id=? WHERE id=?",[f.request.id,key.insertId,intakeId]);
  const result=await service.reserveAvailableForSalesIntakeInTransaction(tx,command);assert.equal(result.lines[0].reservedBaseQuantity,4);assert.equal(result.lines[0].uncoveredBaseQuantity,6);assert.deepEqual(await service.reserveAvailableForSalesIntakeInTransaction(tx,command),result);const [operations]=await tx.query("SELECT command_type,actor_user_id,actor_label FROM inventory_operation_requests WHERE source_event_id=? ORDER BY id",[eventId]);assert.deepEqual(operations.map(r=>r.command_type),["SALES_INTAKE_BATCH_RESERVE","SALES_INTAKE_LINE_RESERVE"]);assert.ok(operations.every(r=>r.actor_user_id===null&&r.actor_label===name));
  enabled=false;await assert.rejects(()=>service.reserveAvailableForSalesIntakeInTransaction(tx,command),{code:"PERMISSION_STALE"});enabled=true;
  for(const [sql,args] of [["UPDATE sales_import_jobs SET lease_owner='not-a-uuid' WHERE id=?",[jobId]],["UPDATE sales_external_order_keys SET source_type='CHANNEL' WHERE id=?",[key.insertId]],["UPDATE sales_intake_orders SET processing_event_id=? WHERE id=?",[randomUUID(),intakeId]],["UPDATE sales_import_jobs SET lease_until=0 WHERE id=?",[jobId]],["UPDATE sales_intake_orders SET sales_order_id=NULL WHERE id=?",[intakeId]],["UPDATE sales_operation_requests SET target_id=? WHERE event_id=?",[Number.MAX_SAFE_INTEGER,eventId]]]){await tx.query("SAVEPOINT owner_probe");await tx.execute(sql,args);await assert.rejects(()=>service.reserveAvailableForSalesIntakeInTransaction(tx,command),{code:"INVENTORY_SOURCE_CONFLICT"});await tx.query("ROLLBACK TO SAVEPOINT owner_probe");}
  await tx.execute("UPDATE fr_job_leases SET expires_at=UNIX_TIMESTAMP() WHERE job_name=?",[name]);await assert.rejects(()=>service.reserveAvailableForSalesIntakeInTransaction(tx,command),{code:"PERMISSION_STALE"});throw rollback;
 }),error=>(error.cause??error)===rollback);
 const [[effects]]=await f.db.query("SELECT (SELECT COUNT(*) FROM inventory_operation_requests WHERE source_event_id=?) AS operations,(SELECT COUNT(*) FROM inventory_reservations WHERE warehouse_id=?) AS reservations,(SELECT COUNT(*) FROM sales_external_order_keys WHERE external_order_id_hash=?) AS external_keys",[eventId,f.warehouseId,hash]);assert.deepEqual(effects,{operations:0,reservations:0,external_keys:0});assert.equal((await f.db.query("SELECT source_type FROM sales_orders WHERE id=?",[f.request.id]))[0][0].source_type,"MANUAL");
});
